### ISSUE TITLE
etcd 3.5 db_size problem

### ISSUE THREAD

**Issue by mencutekin** [etcd-io/etcd#14329] opened 2022-08-10 19:10 UTC
### What happened?

I have 3-node etcd cluster version 3.5.2. I noticed a sitituation that endpoint's db_size is constantly growing. I have to perform compaction and defrag manually so that the db_size value cannot reach to limitation. I have not faced any similar problem in 3.2 version.

+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|      ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 10.201.64.106:2379 | 6af28eee6b8fd63a |   3.5.2 |   18 MB |      true |      false |         3 |    7509221 |            7509221 |        |
| 10.201.64.107:2379 | 8t2ae31d2c14413e |   3.5.2 |   18 MB |     false |      false |         3 |    7509221 |            7509221 |        |
| 10.222.82.121:2379 | c6131f42ed372576 |   3.5.2 |   18 MB |     false |      false |         3 |    7509221 |            7509221 |        |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

### What did you expect to happen?

I expect the db size to not increase that fast. Or I shouldn't do the defrag process manually.

### How can we reproduce it (as minimally and precisely as possible)?

-

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
etcdctl version: 3.5.2
API version: 3.5

</details>


### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here
 --name milano01 \
 --data-dir /var/lib/etcd \
 --initial-advertise-peer-urls http://10.201.64.106:2380 \
 --listen-peer-urls http://10.201.64.106:2380 \
 --listen-client-urls http://10.201.64.106:2379,http://127.0.0.1:2379 \
 --advertise-client-urls http://10.201.64.106:2379 \
 --initial-cluster-token etcd-cluster-1 \
 --initial-cluster milano01=http://10.201.64.106:2380,milano02=http://10.201.64.107:2380,milano03=http://10.222.82.121:2380 \
 --initial-cluster-state new \
 --heartbeat-interval 1000 \
 --election-timeout 5000

</details>


### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by ahrtr** [comment] 2022-08-18 06:39
This isn't an issue of etcd, instead it should be caused by the client side. You need to figure out what data the client is writing. 

Is the etcd  cluster running as the backend of apiserver?

**Comment by mencutekin** [comment] 2022-08-18 17:58
How can I figure out what data is written?
I am using etcd cluster for patroni management (postgresql database cluster)

**Comment by ahrtr** [comment] 2022-08-18 22:19
Please try to get some clues from the client side. You can also use [etcd-dump-db](https://github.com/etcd-io/etcd/tree/main/tools/etcd-dump-db) to dump all the data.

**Comment by george-angel** [comment] 2022-08-31 07:43
We have seen similar behaviour after upgrading v3.5.0 to v3.5.4.

ETCD is used as a backend for Kubernetes, the APIServer requests have not changed at all

![2022-08-31-173657_2560x1273_scrot](https://user-images.githubusercontent.com/1801067/187620962-672a8d13-3840-4963-9bb5-4633111ae67b.png)

But the ETCD DB size has started growing exponentially

![2022-08-31-173715_2560x942_scrot](https://user-images.githubusercontent.com/1801067/187621030-87e4025e-0bb7-46fa-ad6c-d5fdc84e8d89.png)

The change in pattern also coincides with the time we have released this change: https://github.com/utilitywarehouse/tf_kube_ignition/commit/8ff0d098a92d4433a936157ca3ec208a11521058

```
commit 2e8d2dae6396193a1cfd2dbe6161cbef2750b870
Author: George Angel <george-angel@users.noreply.github.com>
Date:   Thu Aug 18 19:01:30 2022 +1000

    Deployed fixed version of ETCD | prod-aws (#9666)
```

Which is 5 AM UTC.

**Comment by kvaikla** [comment] 2022-09-13 12:09
Hi
I have a similar issue (patroni and etcd), after migrating data to 3.5
[https://github.com/etcd-io/etcd/issues/14130](url)

br
Kaido

**Comment by ahrtr** [comment] 2022-09-14 08:54
I kept a 3-member etcd (3.5.4) cluster running for over 1 hour, and the db size is always 25KB. I also kept a 3-member etcd cluster (3.5.4) running as the K8s cluster (1.23.4) backend for over 1 hour, the db size is always 5.2MB. But there is no any traffic. 





> We have seen similar behaviour after upgrading v3.5.0 to v3.5.4.

Do you mean you did not see the db increasing on 3.5.0? 

I see that there is a steep decreasing of the db size in the diagram, did you perform the [compaction & deframentation](https://etcd.io/docs/v3.5/op-guide/maintenance/) operation at that time? @george-angel 

Could you use the [etcd-dump-db](https://github.com/etcd-io/etcd/tree/main/tools/etcd-dump-db) to check what data is consuming the db file? 

# Example commands

## List all buckets
```
$ ./etcd-dump-db list-bucket ~/tmp/etcd/infra1.etcd/ 
alarm
auth
authRoles
authUsers
cluster
key
lease
members
members_removed
meta
```

## List all key/values inside a bucket
```
$ ./etcd-dump-db iterate-bucket ~/tmp/etcd/infra1.etcd/ key --decode 
rev={main:183 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 183 | ver 181]
rev={main:182 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 182 | ver 180]
rev={main:181 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 181 | ver 179]
rev={main:180 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 180 | ver 178]
rev={main:179 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 179 | ver 177]
rev={main:178 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 178 | ver 176]
rev={main:177 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 177 | ver 175]
rev={main:176 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 176 | ver 174]
rev={main:175 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 175 | ver 173]
rev={main:174 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 174 | ver 172]
rev={main:173 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 173 | ver 171]
rev={main:172 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 172 | ver 170]
rev={main:171 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 171 | ver 169]
rev={main:170 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 170 | ver 168]
rev={main:169 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 169 | ver 167]
rev={main:168 sub:0}, value=[key "k2" | val "v2" | created 3 | mod 168 | ver 166]
......
```

**Comment by george-angel** [comment] 2022-09-14 23:03
Hey @ahrtr - thanks for replying, let me fill out some details.

> Do you mean you did not see the db size increasing on 3.5.0?

Correct, the change in behaviour appeared after 3.5.0 -> 3.5.4 upgrade.

> But there is no any traffic.

We are seeing the same behaviour, here is a Kubernetes cluster with the same configuration but much smaller (less controllers, less Nodes and Pods)

![2022-09-15-085758_2560x912_scrot](https://user-images.githubusercontent.com/1801067/190277509-405292fc-da94-4218-a769-cd63c20e6a05.png)

The memory growth is far more subtle. But for our larger clusters (that would be doing lots of reads and writes) and memory growth is a lot more obvious.

> I see that there is a steep decreasing of the db size in the diagram...

Thats right, we are running Kubernetes APIserver with default: `--etcd-compaction-interval duration     Default: 5m0s` and we have a "cronjob" that does `defrag` *daily*: https://github.com/utilitywarehouse/tf_kube_ignition/blob/master/resources/etcd-defrag.service#L9.

Previously we had defrag run *monthly*, but since the upgrade we had to change the frequency to *daily*. In https://user-images.githubusercontent.com/1801067/187621030-87e4025e-0bb7-46fa-ad6c-d5fdc84e8d89.png - this change is not yet implemented, so the drop is a *manual* defrag that we ran.

I had a go using `etcd-dump-db`, but so far getting:

```
$ sudo /tmp/./etcd-dump-db list-bucket /var/lib/etcd/
2022/09/14 22:47:02 failed to open bolt DB timeout
```

I will keep going with this and update if/when I mange to get it to work.

**Comment by ahrtr** [comment] 2022-09-15 00:17
> I had a go using `etcd-dump-db`, but so far getting:
> 
> ```
> $ sudo /tmp/./etcd-dump-db list-bucket /var/lib/etcd/
> 2022/09/14 22:47:02 failed to open bolt DB timeout
> ```

The boltDB file can only be opened by one program. So you need to stop the etcd instance/POD when running the `etcd-dumo-db` tool

**Comment by george-angel** [comment] 2022-09-15 02:43
Thanks @ahrtr 

There is a lot of data, I don't know what to look for:

```
$ grep -o 'key "[^"]*' /tmp/etcd-key-dump | sort | wc -l
26843
```

There are lot of things I would expect to be there, Events, Services, etc.

**Comment by ahrtr** [comment] 2022-09-15 02:55
The proposed test steps:
1. Perform a compaction & defragment operation in the beginning to reclaim the disk space as much as we can;
2. Get the max  revision by running command `etcdctl --endpoints=:2379 endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9].*'`, and note down the number (assuming x);
3. Play the traffic (run the test) for a couple of minutes;
4. Run the same command at step 2, and note the the number again (assuming y).
5. Stop the etcd instance/PODs;
6. Perform the command `./etcd-dump-db iterate-bucket ~/tmp/etcd/infra1.etcd/ key --decode `, and try to extract the records between x and y (check the field `main` in `rev={main:175 sub:0}`). 

Please get back here once you finish the steps above.

**Comment by george-angel** [comment] 2022-09-15 04:45
Thank you @ahrtr 

I did a defrag, noted the revision number, let it run for 6 minutes, noted revision again and then dumped the db. I then checked keys that had revision between x and y. I am grouping them by the path to remove specific keys.

```
14:09 - defrag
14:09 - $ etcdctl-wrapper endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9].*'
1754941972

14:15 - $ etcdctl-wrapper endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9].*'
1754946960
```

```
$ seq 1754941972 1754946960 | rg -f - /tmp/etcd-key-dump-1416 | rg -o 'key "/\w+/\w+' | sort | uniq -c
    151 key "/registry/autoscaling
      9 key "/registry/cronjobs
     37 key "/registry/deployments
     36 key "/registry/endpointslices
    303 key "/registry/events
     86 key "/registry/horizontalpodautoscalers
     18 key "/registry/jobs
      3 key "/registry/kube
   1404 key "/registry/kyverno
   2056 key "/registry/leases
    105 key "/registry/masterleases
     36 key "/registry/minions
     11 key "/registry/poddisruptionbudgets
    314 key "/registry/pods
     37 key "/registry/replicasets
     22 key "/registry/services
    391 key "/registry/wgpolicyk8s
```

**Comment by ahrtr** [comment] 2022-09-15 05:15
Thanks @george-angel for the feedback.

This is a big step, because we have already figured out what data is consuming the disk space. 

The next step is to double confirm whether it's expected. If it's not expected, why there are so many objects. You might need to figure this out from K8s perspective. Proposed action is to do the same test proposed in https://github.com/etcd-io/etcd/issues/14329#issuecomment-1247517788 against etcd 3.5.0, and then compare the test results, so as to narrow down the scope of the issue. The purpose is to figure out which objects' numbers have a big difference between 3.5.0 and 3.5.4.

**Comment by george-angel** [comment] 2022-09-16 05:00
It looks very similar:

```
$ seq 1755013465 1755019135 | rg -f - /tmp/etcd-key-dump-v3.5.0-T1616 | rg -o 'key "/\w+/\w+' | sort | uniq -c
     76 key "/registry/autoscaling
      9 key "/registry/cronjobs
     16 key "/registry/daemonsets
     41 key "/registry/deployments
     38 key "/registry/endpointslices
    620 key "/registry/events
     86 key "/registry/horizontalpodautoscalers
     18 key "/registry/jobs
      2 key "/registry/kube
   1695 key "/registry/kyverno
   2018 key "/registry/leases
    102 key "/registry/masterleases
     43 key "/registry/minions
     20 key "/registry/poddisruptionbudgets
    427 key "/registry/pods
     41 key "/registry/replicasets
     16 key "/registry/services
     20 key "/registry/statefulsets
    383 key "/registry/wgpolicyk8s
```

@ahrtr we have done more digging and looked at other environments and concluded this is indeed not a ETCD behaviour. Zooming out, we think we can correlate our spikes with Kyverno deployment / updates.

Thanks a lot for your help, we are going to pursue this further, but its outside of the scope of this issue. Thanks again for your help debugging.

**Comment by ahrtr** [comment] 2022-09-16 05:47
> It looks very similar:

Did you only replace etcd 3.5.4 with 3.5.0, and kept all others unchanged? Previously you mentioned` the change in behaviour appeared after 3.5.0 -> 3.5.4 upgrade.`, I guess that other components/services might also upgraded at that time.

**Comment by george-angel** [comment] 2022-09-16 07:29
> I guess that other components/services might also upgraded at that time.

No, in *that* environment the correlation is *only* with ETCD update, but in other environments its not necessarily as pronounced.

Here we deployed ETCD v3.5.4 on August 16th:

![2022-09-16-172641_2560x912_scrot](https://user-images.githubusercontent.com/1801067/190581411-d7a8c4d0-ecff-4f92-ac20-30df76057472.png)

So I'm not certain why that environment is showing such a strong correlation (deployed August 18th)

![2022-09-16-172840_2560x918_scrot](https://user-images.githubusercontent.com/1801067/190581708-173c1af0-2b4a-4df3-b448-bfaf23d6a4c8.png)

**Comment by ahrtr** [comment] 2022-09-16 07:50
Some points/suggestions:
1. We have already confirmed that etcd 3.5.4's db size will not increase if there is no traffic, no matter it's the back-end of apiserver. So the increasing of db dize must be caused by client side traffic. 
2. When exactly did you enable the daily `defrag` "cronjob" in both environment? It looks like the job was enabled at about Aug 24th in the first diagram, while it's about Sept 8th in the second diagram? Please just to double check in case we miss some basic info.

**Comment by george-angel** [comment] 2022-09-16 08:17
Sure,

First diagram is our **dev-aws** environment, ETCD v3.5.4 was deployed `Tue Aug 16 19:34:36 2022 +1000` and the daily defrag was deployed: `Wed Aug 24 17:09:03 2022 +1000`

Second diagram is **prod-aws**, ETCD v3.5.4 was deployed: `Thu Aug 18 19:01:30 2022 +1000` and daily defrag: `Wed Sep 7 09:15:43 2022 +0100`

The SystemD timer is "daily": https://github.com/utilitywarehouse/tf_kube_ignition/blob/master/etcd.tf#L164

**Comment by ahrtr** [comment] 2022-09-16 08:25
The timing of deploying the `defrag` daily job makes sense. It explains why you see the huge db increasing in the second diagram.
1. The disk space wasn't reclaimed at all before deploying the defrag daily job at Sep 7, so you saw the continuous db size increase;
2. The different amplitude between two environments might be due to different traffic rate.

**Comment by ahrtr** [comment] 2022-09-16 08:28
It seems we are all good now?

**Comment by george-angel** [comment] 2022-09-16 08:29
:D For me - yes, we'll take our issue elsewhere, I can't speak for others

**Comment by ahrtr** [comment] 2022-09-16 08:30
> I have not faced any similar problem in 3.2 version.

@mencutekin I believe the K8s and probably some other services were also upgraded when you upgraded the etcd to 3.5.2? Please note that 3.5.2 isn't recommended for production use any more.  FYI. [data inconsistency issue](https://github.com/ahrtr/etcd-issues/tree/master/issues/13766)

**Comment by ahrtr** [comment] 2022-09-16 08:33
@mencutekin Please follow the discussion above to do similar analysis. I am closing this ticket. Please feel free to reopen or raise new issue if you still have any concern.

**Closed by ahrtr** 2022-09-16 08:33 UTC
