### ISSUE TITLE
Errors not logged or returned

### ISSUE THREAD

**Issue by lilic** [etcd-io/etcd#12884] opened 2021-04-22 07:37 UTC
While looking at some code I noticed that in https://github.com/etcd-io/etcd/blob/cc52d994b7e44572a69ea37a6439d3212084046a/client/v3/lease.go#L299 the error is not logged. And the function does return valid errors which are not returned or logged: https://github.com/etcd-io/etcd/blob/cc52d994b7e44572a69ea37a6439d3212084046a/client/v3/lease.go#L427

So I ran `golangci-lint run --disable-all -E errcheck` just out of curiosity and it found a few valid places, in my humble opinion, where the error should be either logged or returned. 

I am wondering is there a specific reason against at least logging those errors or is it just by accident that this happened. If we want them, I am happy to contribute those changes, just wanted to make sure before going ahead with it, thank you!

**Comment by seeker89** [comment] 2021-04-22 17:31
Duplicate of https://github.com/etcd-io/etcd/issues/12712

**Comment by gyuho** [comment] 2021-04-22 18:35
Yeah we must have missed this. Can we just warn-log if we don't do anything?

**Comment by lilic** [comment] 2021-04-23 15:06
Yes that makes sense, like in the case above we would wrap it and warn log is what you were thinking?

**Closed** 2021-06-02 16:05 UTC
