### ISSUE TITLE
clientv3: clientv3.New() won't return error when no endpoint is available

### ISSUE THREAD

**Issue by yudai** [etcd-io/etcd#9877] opened 2018-06-21 21:16 UTC
What's observed
-----------------

With `clientv3` on the master branch (7648841bad1ef56d83e568ae006f0bb2dc9e917a), `clientv3.New()` won't return any error even when no endpoint is available to connect.

The following reproduction code doesn't panic with master, while the same code with v3.3.x panics.

```
conf := clientv3.Config{
    Endpoints:   []string{"invalid_endpoint:2379"},
    DialTimeout: 10 * time.Second,
}
client, err := clientv3.New(conf)
if err != nil {
    panic("connection failed")
}
```

Breaking Change?
-------------------

I assume this behavior change has been introduced along with the new load balancer. It makes sense that the load balancer internally handles connection errors and hide them from users, because the load balancer is responsible for endpoint selection and reconnection.
(I myself is fine with this behavior, since following requests will fail when no endpoint is available and we can detect the problem at that timing)

However, this looks a breaking change for users. I assume some code has different error handlers when no endpoint is available at the startup of applications (like just die instead of retry).

I therefore think that at least this change is mentioned in the CHANGELOG as a breaking change.

**Comment by gyuho** [comment] 2018-06-21 21:33
> won't return any error even when no endpoint is available to connect.

I misread, somehow. I will investigate more.

**Comment by gyuho** [comment] 2018-06-21 23:10
Confirmed `DialOptions: []grpc.DialOption{grpc.WithBlock()},` would return errors like old client, but without this dial option, connect happens in background returning the client object before initial connection.

We plan to document this clearly (ref https://github.com/coreos/etcd/issues/9829). Also, need more research about enabling it by default (since you cannot disable `WithBlock` once configured).

**Comment by philippgille** [comment] 2018-11-13 20:48
Using `DialOptions: []grpc.DialOption{grpc.WithBlock()},` in my code leads to the following compile error: `cannot use []"google.golang.org/grpc".DialOption literal (type []"google.golang.org/grpc".DialOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".DialOption in field value` (note: I'm a Go beginner)

**Comment by bblay** [comment] 2019-01-29 11:38
@philippgille, based on [this comment](https://github.com/etcd-io/etcd/issues/9829#issuecomment-439545865), I solved the problem like this:
```
	clientConfig := clientv3.Config{
		Endpoints:   []string{"http://" + *etcdHost},
		DialTimeout: 2 * time.Second,
	}

	etcd, err := clientv3.New(clientConfig)
	if err != nil {
		return nil, errors.Wrap(err, "could not connect to etcd")
	}

	timeoutCtx, cancel := context.WithTimeout(context.Background(), 2 * time.Second)
	defer cancel()
	_, err = etcd.Status(timeoutCtx, clientConfig.Endpoints[0])
	if err != nil {
		return nil, errors.Wrapf(err, "error checking etcd status: %v", err)
	}
```

**Comment by gyuho** [comment] 2019-08-05 06:52
Closing via https://github.com/etcd-io/etcd/commit/4b0af5b4ac160e66cd7af5ef93e94e9d4498b41a

**Closed by gyuho** 2019-08-05 06:52 UTC
Labels: Release-Note, area/clientv3, area/doc

**Comment by Victor2333** [comment] 2019-10-28 08:42
> Using `DialOptions: []grpc.DialOption{grpc.WithBlock()},` in my code leads to the following compile error: `cannot use []"google.golang.org/grpc".DialOption literal (type []"google.golang.org/grpc".DialOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".DialOption in field value` (note: I'm a Go beginner)

This problem is because GO is trying to find grpc function from etcd library vendor path. I solved this problem by using [dep](https://golang.github.io/dep/) GO package manager. You need to move all your dependency to vendor folder which is in your project root folder maybe will solve the problem.
