### ISSUE TITLE
etcd 3.3.x benign TLS error when etcdctl uses 3 --endpoints values 

### ISSUE THREAD

**Issue by robertglen** [etcd-io/etcd#10040] opened 2018-08-28 20:39 UTC
Server version: 3.3.9
Client version: 3.3.9

Scenario:  When calling etcdctl --endpoints=<https://ip1:2379,https://ip2:2379,https://ip3:2379>  to get data... an TLS connection error is observed on one of the three servers from --endpoints in its log.

The etcdctl command returns successfully, immediately.  From client perspective, you would never know an issue has occurred.  But on one of the 3 servers, the folliowing error is observed:

> Aug 28 20:33:02 ip-10-10-19-105 etcd[9499]: rejected connection from "10.10.15.50:33718" (error "EOF", ServerName "")

The error will appear on just one of the 3 servers, never more, but it can move from server to server with subsequent retries by etcdctl.

**INTERESTING FACTS**

- when --endpoints value in etcdctl only specifies 1 or 2 of the 3 IPs, the error is never observed on the servers
- when --endpoints specifies 3 values, one of which is intentionally invalid (incorrect IP address), the error is never observed on either of the 2 valid servers.
- in each case above, the etcdctl returns data successfully, instantly

**Comment by hexfusion** [comment] 2018-09-23 16:34
@robertglen just getting a chance to get around to this. I can replicate if I append a comma to the last endpoint like this. In which case it doesn't matter if I have even 1 endpoint I will see simular output.
```
etcdctl --endpoints https://ip1:2379,https://ip2:2379,https://ip3:2379,   --key cert/client-key.pem  --cacert cert/ca.pem  --cert cert/client.pem put foo bar
```

Can you manually make the call using --endpoints flag explicitly and see if that was the cause. I can not replicate without the extra comma.

**Comment by hexfusion** [comment] 2018-10-12 17:40
@robertglen I am going to close this if you can provide more information or are still having the problem please let me know in this ticket and I can reopen.

**Closed by hexfusion** 2018-10-12 17:40 UTC
Labels: Support/Question, clientv3

**Comment by jsok** [comment] 2019-01-15 23:48
This is a duplicate of https://github.com/etcd-io/etcd/issues/9949
