### ISSUE TITLE
How to deal with programing by clientv3 library when one etcd node is down

### ISSUE THREAD

**Issue by steedyu** [etcd-io/etcd#10507] opened 2019-02-28 09:42 UTC
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

for example:
cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"127.0.0.1:2379", "127.0.0.2:22379", "127.0.0.3:32379"},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		fmt.Println("connect failed, err:", err)
		return
	}

	fmt.Println("connect succ")
	defer cli.Close()

//设置1秒超时，访问etcd有超时控制
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	//操作etcd
	_, err = cli.Put(ctx, "/logagent/conf/", "sample_value")
	if err != nil {
		fmt.Println(err)
	}
	//操作完毕，取消etcd
	cancel()
	if err != nil {
		fmt.Println("put failed, err:", err)
		return
	}
	//取值，设置超时为1秒
	ctx, cancel = context.WithTimeout(context.Background(), time.Second)
	resp, err := cli.Get(ctx, "/logagent/conf/")
	cancel()
	if err != nil {
		fmt.Println("get failed, err:", err)
		return
	}
	for _, ev := range resp.Kvs {
		fmt.Printf("%s : %s\n", ev.Key, ev.Value)
	}

	mresp, err := cli.MemberList(context.TODO())
	for _, m := range mresp.Members {
		fmt.Println(m.ClientURLs,m.PeerURLs,m.Name,m.ID)
	}

and then use variavle cli to put,get,delete,watch in etcd, but when 127.0.0.1:2379 will be down, the clie will not work. and the error "Etcd ctx is attached with a deadline is exceeded: context deadline exceeded" will throw.

the clientv3 driver seem not to change cli to fine etcd node?

I want to know how to deal in this condtion?

thanks

**Comment by hexfusion** [comment] 2019-03-01 13:32
@steedyu I believe this is duplicate of https://github.com/etcd-io/etcd/issues/9949 lets follow here. You can also track efforts for resolution here https://github.com/etcd-io/etcd/pull/10489.

**Closed by hexfusion** 2019-03-01 13:32 UTC

**Comment by lwcbest** [comment] 2021-03-17 12:49
> Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.
> 
> for example:
> cli, err := clientv3.New(clientv3.Config{
> Endpoints: []string{"127.0.0.1:2379", "127.0.0.2:22379", "127.0.0.3:32379"},
> DialTimeout: 5 * time.Second,
> })
> if err != nil {
> fmt.Println("connect failed, err:", err)
> return
> }
> 
> ```
> fmt.Println("connect succ")
> defer cli.Close()
> ```
> 
> //设置1秒超时，访问etcd有超时控制
> ctx, cancel := context.WithTimeout(context.Background(), time.Second)
> //操作etcd
> _, err = cli.Put(ctx, "/logagent/conf/", "sample_value")
> if err != nil {
> fmt.Println(err)
> }
> //操作完毕，取消etcd
> cancel()
> if err != nil {
> fmt.Println("put failed, err:", err)
> return
> }
> //取值，设置超时为1秒
> ctx, cancel = context.WithTimeout(context.Background(), time.Second)
> resp, err := cli.Get(ctx, "/logagent/conf/")
> cancel()
> if err != nil {
> fmt.Println("get failed, err:", err)
> return
> }
> for _, ev := range resp.Kvs {
> fmt.Printf("%s : %s\n", ev.Key, ev.Value)
> }
> 
> ```
> mresp, err := cli.MemberList(context.TODO())
> for _, m := range mresp.Members {
> 	fmt.Println(m.ClientURLs,m.PeerURLs,m.Name,m.ID)
> }
> ```
> 
> and then use variavle cli to put,get,delete,watch in etcd, but when 127.0.0.1:2379 will be down, the clie will not work. and the error "Etcd ctx is attached with a deadline is exceeded: context deadline exceeded" will throw.
> 
> the clientv3 driver seem not to change cli to fine etcd node?
> 
> I want to know how to deal in this condtion?
> 
> thanks

I get the same issue from my env，how to resolve this issue？

**Comment by ptabor** [comment] 2021-03-17 13:06
If you supplied multiple endpoints, etcd client should be performing round-robin load-balancing between the reachable endpoints. 
You can get error from time to time, but if you retry, you should get answer from healthy node if present. 

Otherwise please contribute a repro-test in this package: 
https://github.com/etcd-io/etcd/blob/master/tests/integration/clientv3/connectivity/network_partition_test.go
