### ISSUE TITLE
embed: Can't restart etcd

### ISSUE THREAD

**Issue by purpleidea** [etcd-io/etcd#6042] opened 2016-07-26 00:10 UTC
Etcd now has an embed API. Sweet :)

I believe there is still a bind problem when starting a server, then stopping it, and then starting it again. On the second start, you'll get a `bind: address already in use` error because the listen isn't closed properly.

Opening this issue at the request of @heyitsanthony 

I think this _may_ be casually related to https://github.com/coreos/etcd/issues/2920

Thanks!

**Comment by gyuho** [comment] 2016-07-26 00:14
Can you provide code snippet to reproduce? Thanks.

**Comment by purpleidea** [comment] 2016-07-26 00:19
@gyuho Fair enough, I don't have a trivial snippet at the moment, I'll reopen when I get one. Thanks!

**Comment by purpleidea** [comment] 2016-10-28 07:08
I forget if this is related to: https://github.com/golang/go/issues/4674 or not.

**Comment by purpleidea** [comment] 2019-04-11 20:24
Apologies for the delay, but I can reliably reproduce this issue, so I will re-open this. I have an easy POC inside of https://github.com/purpleidea/mgmt/

**Comment by purpleidea** [comment] 2019-04-11 21:31
Here is the reproducer:

## start up three members...
```
./mgmt run --hostname h1 --tmp-prefix --no-pgp empty
./mgmt run --hostname h2 --tmp-prefix --no-pgp --seeds http://127.0.0.1:2379 --client-urls http://127.0.0.1:2381 --server-urls http://127.0.0.1:2382 empty
./mgmt run --hostname h3 --tmp-prefix --no-pgp --seeds http://127.0.0.1:2379 --client-urls http://127.0.0.1:2383 --server-urls http://127.0.0.1:2384 empty
```

## tell the ideal cluster size to be three...
```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 put /_mgmt/chooser/dynamicsize/idealclustersize 3
```
## check that it is...
```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 member list
```

## add two more clients...
```
./mgmt run --hostname h4 --tmp-prefix --no-pgp --seeds http://127.0.0.1:2379 --client-urls http://127.0.0.1:2385 --server-urls http://127.0.0.1:2386 empty
./mgmt run --hostname h5 --tmp-prefix --no-pgp --seeds http://127.0.0.1:2379 --client-urls http://127.0.0.1:2387 --server-urls http://127.0.0.1:2388 empty
```

## tell the cluster size to be 4...
```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 put /_mgmt/chooser/dynamicsize/idealclustersize 4
```

## one more member will be started now...
```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 member list
```

## set it back to three...
```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 put /_mgmt/chooser/dynamicsize/idealclustersize 3
```
## make note of who shutdown...
```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 member list
```

## bring it back to 4...
```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 put /_mgmt/chooser/dynamicsize/idealclustersize 4
```
## you'll most likely have one that previously started, try to start again... repeat the above 3->4->3 if not.
```
ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 member list
```
## in the logs of that member:
```
main.go:385: etcd: runtime error: listen tcp 127.0.0.1:2384: bind: address already in use
server start failed
```

I believe I am using the embed API correctly, but if there is some additional shutdown/unbind step that I should be performing that I am not, then please let me know. Thanks!

**Comment by purpleidea** [comment] 2020-04-07 05:20
hi bot! please stop pinging here

**Comment by cretz** [comment] 2020-07-06 15:12
Bump, I don't believe this is resolved (IIRC in my integration tests cannot stop and start up embedded etcd again due to this issue). At the least deserves confirmation that's fixed before closing.

**Comment by purpleidea** [comment] 2020-07-06 15:18
@cretz It's not fixed last I checked, but I'm giving up fighting with the bots, it's very end-user hostile I think. One bump should be enough for the lifetime of the bug. And the bot bugged about eight others today. :/

**Comment by purpleidea** [comment] 2020-10-04 16:14
Stop closing this bot. This is important.

**Comment by ptabor** [comment] 2020-10-05 08:34
I believe it might be about (etcd not using) 'SO_REUSEADDR'. Without this setting port is 'locked' for additional 60-120s,
to avoid getting left-over communication from previous customers.

That's pretty good article about this: 
  https://stackoverflow.com/questions/3229860/what-is-the-meaning-of-so-reuseaddr-setsockopt-option-linux/3233022#3233022
  and https://hea-www.harvard.edu/~fine/Tech/addrinuse.html

**Comment by purpleidea** [comment] 2020-11-26 23:04
Think you can send a patch to fix this?

**Comment by purpleidea** [comment] 2021-02-25 19:52
bot

**Comment by ptabor** [comment] 2021-04-05 21:44
I think / hope it got fixed in: 

 https://github.com/etcd-io/etcd/pull/12702

Please test and reopen.

**Closed by ptabor** 2021-04-05 21:44 UTC

**Comment by purpleidea** [comment] 2021-04-07 04:49
@ptabor Fantastic news, thanks! I'll test in 3.5

**Comment by Quentin-M** [comment] 2021-05-06 02:22
This is amazing, thanks for doing this!
