### ISSUE TITLE
Disable the EXPECT_DEBUG log in github workflow

### ISSUE THREAD

**Issue by ahrtr** [etcd-io/etcd#16664] opened 2023-09-29 14:31 UTC
### What would you like to be added?

Disable the EXPECT_DEBUG log in e2e test

https://github.com/etcd-io/etcd/blob/6521c9e224ff27a0e436d81fe77973d3cd70b0e1/.github/workflows/e2e.yaml#L38

https://github.com/etcd-io/etcd/blob/6521c9e224ff27a0e436d81fe77973d3cd70b0e1/.github/workflows/e2e.yaml#L41

### Why is this needed?

The log is always been truncated due to its large size. Each time when I debug a failed test case, I need to download the log. It's really boring.

**Comment by serathius** [comment] 2023-09-29 15:00
True, however how do we debug the issue if we cannot reproduce it locally. Robustness tests have the same issue. Is downloading the file so boring that we need to reduce debuggability of CI? 

I was thinking about a middle ground (never gotten to implement it), having expect debug writing to files instead of spamming the stdout. We can upload the files to GitHub in a similar way to robustness reports. Downside is lack of log correlation, not all logs have timestamp.

**Comment by serathius** [comment] 2023-09-29 15:00
Bug I filed https://github.com/etcd-io/etcd/issues/15079

**Comment by jmhbnz** [comment] 2024-08-12 09:13
Closing alongside https://github.com/etcd-io/etcd/issues/15079 as not being a priority currently. Now that we have migrated to prow for e2e and robustness tests it's much easier to review large volumes of log output for a failed test.

**Closed by jmhbnz** 2024-08-12 09:13 UTC
Labels: area/testing, type/feature, area/tooling
