### ISSUE TITLE
Flaked integration/clientv3/examples ExampleCluster_memberAddAsLearner 

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#14040] opened 2022-05-13 13:41 UTC
https://github.com/etcd-io/etcd/runs/6423405520

**Comment by lavacat** [comment] 2022-05-16 04:39
I'll take a look at this

**Comment by lavacat** [comment] 2022-05-19 20:20
Quick update on this issue:

Found another run of this test that failed https://github.com/etcd-io/etcd/runs/6441619707?check_suite_focus=true

In both cases, we see the following logs:

`2022/05/13 13:11:47 2022-05-13T13:11:47.769Z	INFO	m0	applied a configuration change through raft	{"member": "m0", "local-member-id": "b81308bc4e5da240", "raft-conf-change": "ConfChangeAddLearnerNode", "raft-conf-change-node-id": "517ae5b12ac546a2"}
2022/05/13 13:11:47 2022-05-13T13:11:47.770Z	INFO	m0.raft	b81308bc4e5da240 ignoring conf change {ConfChangeRemoveNode 5871257613320406690 [] 11691486184239052569} at config voters=(12662322919470357889 13263954932397875776 18388213170794053236) learners=(5871257613320406690): possible unapplied conf change at index 25 (applied to 24)	{"member": "m0"}`

The problem is that raftLog.applied can be advanced after request is done. It's not synchronized with EtcdServer.appliedIndex increment in EtcdServer.apply

Looking for a good fix

**Comment by serathius** [comment] 2022-05-20 07:44
Nice find!

**Comment by halegreen** [comment] 2022-11-07 15:31
want to working on this while the run log is expired, can I see the log any where else? 

https://github.com/etcd-io/etcd/runs/6423405520 

<img width="656" alt="Screen Shot 2022-11-07 at 11 29 47 PM" src="https://user-images.githubusercontent.com/13792102/200349449-4789a1e9-7646-48e3-bdb6-7394509b9ee6.png">

**Comment by lavacat** [comment] 2022-11-22 07:56
@halegreen I don't have log from CI, but imo the root cause was `ignoring conf change ... possible unapplied conf change at index` that causes second ProposeConfChange to timeout. I've used TestMemberAddRemoveFail (see below) to reproduce.

My theory is that flakiness was eliminated by https://github.com/etcd-io/etcd/commit/73029fe89fece14af3a205490803b5b337c688a7 because it reduced time between [applying](https://github.com/etcd-io/etcd/blob/main/server/etcdserver/raft.go#L213) and calling [r.Advance()](https://github.com/etcd-io/etcd/blob/main/server/etcdserver/raft.go#L309).

But if you add artificial delay before `r.Advance()` you can still reproduce it.
```
diff --git a/server/etcdserver/raft.go b/server/etcdserver/raft.go
index 704e45a7a..925a3c19d 100644
--- a/server/etcdserver/raft.go
+++ b/server/etcdserver/raft.go
@@ -305,7 +305,7 @@ func (r *raftNode) start(rh *raftReadyHandler) {
                                        // leader already processed 'MsgSnap' and signaled
                                        notifyc <- struct{}{}
                                }
-
+                               time.Sleep(10 * time.Millisecond)
                                r.Advance()
                        case <-r.stopped:
                                return
diff --git a/tests/integration/cluster_test.go b/tests/integration/cluster_test.go
index 30996a557..6b8594995 100644
--- a/tests/integration/cluster_test.go
+++ b/tests/integration/cluster_test.go
@@ -58,6 +58,38 @@ func TestTLSClusterOf3(t *testing.T) {
        clusterMustProgress(t, c.Members)
 }

+func TestMemberAddRemoveFail(t *testing.T) {
+       integration.BeforeTest(t)
+
+       clus := integration.NewCluster(t, &integration.ClusterConfig{Size: 1})
+       defer clus.Terminate(t)
+
+       capi := clus.RandClient()
+
+       urls := []string{"http://127.0.0.1:1234"}
+       resp, err := capi.MemberAddAsLearner(context.Background(), urls)
+       if err != nil {
+               t.Fatalf("failed to add member %v", err)
+       }
+
+       _, err = capi.MemberRemove(context.Background(), resp.Member.ID)
+       if err != nil {
+               t.Fatal(err)
+       }
+
+       urls = []string{"http://127.0.0.1:1235"}
+       resp, err = capi.MemberAddAsLearner(context.Background(), urls)
+       if err != nil {
+               t.Fatalf("failed to add member %v", err)
+       }
+
+       _, err = capi.MemberRemove(context.Background(), resp.Member.ID)
+       if err != nil {
+               t.Fatal(err)
+       }
+}
+
 // Test that a cluster can progress when using separate client and server certs when peering. This supports certificate
 // authorities that don't issue dual-usage certificates.
 func TestTLSClusterOf3WithSpecificUsage(t *testing.T) {
```
This happens because `EtcdServer.configure` will return to the client but `raftLog.appliedTo` isn't called yet. Then next `EtcdServer.configure` will generate a new proposal that will trigger `alreadyPending` [check](https://github.com/etcd-io/etcd/blob/main/raft/raft.go#L1088).

I don't think this is a bug. Raft docs say `Apply Snapshot (if any) and CommittedEntries to the state machine. ... ` https://github.com/etcd-io/etcd/blob/main/raft/README.md
and then there is an example of `process(entry)` that doesn't wait for `r.Advance`.

The worst case if `r.Advance` isn't called, node won't be able to process future proposals, but that doesn't break raft guarantees.

I'm not raft expect, so might be wrong about this. Please double check.

**Comment by lavacat** [comment] 2022-11-22 07:59
One improvement is to add `ErrProposalDropped` for `EntryConfChange` in raft to fast-fail and not wait for timeout. I'll add an issue and draft PR for this.

**Comment by chaochn47** [comment] 2023-10-22 22:31
Closed by https://github.com/etcd-io/etcd/pull/15708

**Closed** 2023-10-22 22:32 UTC
Labels: help wanted, type/flake, stage/tracked
