### ISSUE TITLE
Small number of high latency requests after a leader election

### ISSUE THREAD

**Issue by Cjen1** [etcd-io/etcd#12680] opened 2021-02-09 17:35 UTC
I've recently been testing etcd's availability around leader failures.

If I create a new client is follows: 
```
  cli_v3, err := clientv3.New(clientv3.Config{
          Endpoints:            endpoints,
          DialTimeout:          dialTimeout,
          DialKeepAliveTime:    dialTimeout / 2,
          DialKeepAliveTimeout: dialTimeout * 2,
          AutoSyncInterval:     dialTimeout / 2,
  })
```

And the load generator dispatches 1000 requests per second, using a new goroutine for each requests such that each request is applied asynchronously.

In a three node configuration when I kill the leader 20s into the test (it restarts at 40s), I observe the following odd behaviour:

![etcd-leader](https://user-images.githubusercontent.com/11444677/107401458-cdad7f80-6afa-11eb-98d1-82faf129a05e.png)

This shows the latency of requests dispatched at a given point in time.

At 20s the leader is killed and a leader election occurs, thus requests submitted during this period are stalled until the election completes. This explains the lack of requests submitted between 20s and 21s which have latencies lower than a 100ms.

However after the election there is a subset of requests (~10%-15%) which are stalled for a further about 8s (the curving down line of high latency requests).

Are there any possible reasons for this? I've found it to be relatively reproducible, but can't find a possible reason for it.

(The nodes are all running on my local machine. The nodes and the client are running etcd v3.4.14)

**Comment by ptabor** [comment] 2021-02-09 18:09
It's aligned with my recent observation on 1.4.13. 

What I found is that the node that is follower and becoming a leader during the election has some troubles with responding to the read-only requests it used to be serving. Can you check if the 'delayed' requests are 'served' by the 'new leader' or any of the nodes ?

**Comment by Cjen1** [comment] 2021-02-09 21:21
So I'm not actually sure and have had difficulty trying to figure this kind of thing out in the past. Specifically trying to track which node a request is dispatched to, has been troublesome, is there an endpoint which I can hook into for it?

Additionally this is should be a write-only workload (just `client.Put` requests).

**Comment by ptabor** [comment] 2021-02-09 21:46
You can have 3 concurrently running clients each of them connecting to specific etcd node.

**Comment by Cjen1** [comment] 2021-02-17 17:14
Hi I managed to get all that working today. It seems that you were correct, the delayed requests do seem to be served by the new leader.

![image](https://user-images.githubusercontent.com/11444677/108240902-31f7c100-7143-11eb-8a7f-d51abcbe6c97.png)

![image](https://user-images.githubusercontent.com/11444677/108240934-3ae89280-7143-11eb-9a2f-27098a3f2989.png)

(leader killed at 20s, that process is restarted at 40s)

Afaict the original leader is "10.0.0.1", and "10.0.0.2" is subsequently elected.

**Comment by wpedrak** [comment] 2021-03-04 15:41
It might be caused by dropping request on 

https://github.com/etcd-io/etcd/blob/aefbd226b8a7b50f4d645f744d2356e0a5d3231a/raft/raft.go#L1075-L1078

as later on we wait for response (and didn't get one) in

https://github.com/etcd-io/etcd/blob/aefbd226b8a7b50f4d645f744d2356e0a5d3231a/server/etcdserver/v3_server.go#L754

thus nothing is happening till timeout.

On my local setup, commenting out `return nil` in first file is resolving timeout issue (but is still not a solution, as this `if` is there for a reason: https://github.com/etcd-io/etcd/issues/7331).

**Comment by Cjen1** [comment] 2021-03-04 16:24
@wpedrak I think that the `if` is there for the `Leader Completeness Property` (Section 8 of the Raft paper).

Is it possible to do a case split kind of thing? So in the standard case, everything normal, in the `!committedEntryInCurrentTerm()` case waiting on that condition itself.

**Comment by ptabor** [comment] 2021-03-04 16:58
@Cjen1 Could you please rerun your test with the if commented out to confirm that root-cause. 

Agree that we should somehow delay execution of the code
https://github.com/etcd-io/etcd/blob/aefbd226b8a7b50f4d645f744d2356e0a5d3231a/raft/raft.go#L1083-L1093 till the post-commit. 

https://github.com/etcd-io/etcd/blob/aefbd226b8a7b50f4d645f744d2356e0a5d3231a/raft/raft.go#L509
Seems to be always executed post-commit. 

I don't know whether in clusters without any RW traffic, we can assume a commit soon after election, that would drain the queued 'readIndex' updates.

**Comment by wpedrak** [comment] 2021-03-11 16:19
Hi @Cjen1 ,

I've just submitted PR which might fix your issue. Once you have time, please have a look at https://github.com/etcd-io/etcd/pull/12762.

**Comment by Cjen1** [comment] 2021-03-17 12:31
@wpedrak below are repeats of the test using the fixes. It appears that they work as expected.

As a minor point, I don't think that the current build from source instructions are correct, I had a devil of a time building your branches.
What worked was abusing `make compile-with-docker-test` to have a working build environment.

For interpretation's sake, there are three repeats of each of the tests (etcd, etcd with postponing the reads, etcd with retrying the reads after 500ms).

![visualization](https://user-images.githubusercontent.com/11444677/111467241-1d93ed80-871c-11eb-9b7d-2ef360c0620d.png)

**Comment by wpedrak** [comment] 2021-03-17 13:33
@Cjen1 great to hear that it works for you. Could you elaborate on build issues you encountered? I've just did
```
git clone git@github.com:wpedrak/etcd.git tmp-etcd
cd tmp-etcd
git checkout read_index_retry
./build.sh
```
and it went through without any issue.

**Comment by Cjen1** [comment] 2021-03-17 13:54
I was getting a build directory wasn't `etcd/v3` error.
Specifically its the first check in `scripts/test_lib.sh`
```
if [[ "$(go list)" != "${ROOT_MODULE}/v3" ]]; then
  echo "must be run from '${ROOT_MODULE}/v3' module directory"
  exit 255
fi
```

(this was from within the `~/go/go.etcd.io/etcd` folder with your branch checked out).

I think it might have been related to using an older version of golang (v1.11.5), but I don't know enough about go's tooling to fix it.

**Comment by ptabor** [comment] 2021-03-17 14:01
For the master branch we expect golang-1.15+. 
I think that 1.11 didn't yet understood modules (by default).

**Closed** 2021-03-23 14:57 UTC
Labels: Investigating, important
