### ISSUE TITLE
Data inconsistency in etcd version 3.5.0 (3.5.x rollback> 3.4 upgrade-> 3.5) story

### ISSUE THREAD

**Issue by moonovo** [etcd-io/etcd#13514] opened 2021-12-01 14:18 UTC
When I enter the following command:
```
ETCDCTL_API=3  etcdctl --endpoints https://192.168.2.2:4003 get /Canal/can/locks/health-host-192-168-2-2 -w json; ETCDCTL_API=3  etcdctl --endpoints https://192.168.2.3:4003 get /Canal/can/locks/health-host-192-168-2-2 -w json; ETCDCTL_API=3  etcdctl --endpoints https://192.168.2.4:4003 get /Canal/can/locks/health-host-192-168-2-2 -w json; 
```
I get the response:
```
{"header":{"cluster_id":5771341481381694818,"member_id":8096206227661897536,"revision":973575,"raft_term":16},"kvs":[{"key":"L0NhbmFsL2Nhbi9sb2Nrcy9oZWFsdGgtaG9zdC0xOTItMTY4LTItMg==","create_revision":2,"mod_revision":973561,"version":122303,"value":"eyJraW5kIjoiTG9jayIsImFwaVZlcnNpb24iOiJjYW4vdjFhbHBoYTEiLCJtZXRhZGF0YSI6eyJuYW1lIjoiaGVhbHRoLWhvc3QtMTkyLTE2OC0yLTIiLCJjcmVhdGlvblRpbWVzdGFtcCI6IjIwMjEtMTItMDFUMjE6NTg6NTdaIn0sImxvY2tpZCI6ImhlYWx0aC1ob3N0LTE5Mi0xNjgtMi0yIn0K"}],"count":1}
{"header":{"cluster_id":5771341481381694818,"member_id":14749687755696706107,"revision":973575,"raft_term":16},"kvs":[{"key":"L0NhbmFsL2Nhbi9sb2Nrcy9oZWFsdGgtaG9zdC0xOTItMTY4LTItMg==","create_revision":2,"mod_revision":973561,"version":122303,"value":"eyJraW5kIjoiTG9jayIsImFwaVZlcnNpb24iOiJjYW4vdjFhbHBoYTEiLCJtZXRhZGF0YSI6eyJuYW1lIjoiaGVhbHRoLWhvc3QtMTkyLTE2OC0yLTIiLCJjcmVhdGlvblRpbWVzdGFtcCI6IjIwMjEtMTItMDFUMjE6NTg6NTdaIn0sImxvY2tpZCI6ImhlYWx0aC1ob3N0LTE5Mi0xNjgtMi0yIn0K"}],"count":1}
{"header":{"cluster_id":5771341481381694818,"member_id":9436515569532730235,"revision":922759,"raft_term":16},"kvs":[{"key":"L0NhbmFsL2Nhbi9sb2Nrcy9oZWFsdGgtaG9zdC0xOTItMTY4LTItMg==","create_revision":2,"mod_revision":922630,"version":120692,"value":"eyJraW5kIjoiTG9jayIsImFwaVZlcnNpb24iOiJjYW4vdjFhbHBoYTEiLCJtZXRhZGF0YSI6eyJuYW1lIjoiaGVhbHRoLWhvc3QtMTkyLTE2OC0yLTIiLCJjcmVhdGlvblRpbWVzdGFtcCI6IjIwMjEtMTItMDFUMjE6NTQ6MzFaIn0sImxvY2tpZCI6ImhlYWx0aC1ob3N0LTE5Mi0xNjgtMi0yIn0K"}],"count":1}
```
 different `mod_revision` and `version` on 192.168.2.4 node

Reproduce Procedure:
1. reboot the three nodes.
2. when the 192.168.2.4 node starts up, it may have replaced the old etcd data into the etcd data directory, I guess.

If the second point is true, there will be data inconsistency? why can the node with broken data added to the etcd cluster?

**Comment by moonovo** [comment] 2021-12-01 14:24
log on 192.168.2.4 node:
```
{"level":"info","ts":"2021-11-30T23:55:26.032Z","caller":"etcdmain/etcd.go:72","msg":"Running: ","args":["etcd"]}
{"level":"info","ts":"2021-11-30T23:55:26.032Z","caller":"etcdmain/etcd.go:99","msg":"failed to detect default host","error":"could not find default route"}
{"level":"warn","ts":"2021-11-30T23:55:26.033Z","caller":"etcdmain/etcd.go:445","msg":"found invalid file under data directory","filename":"config.ini","data-dir":"/var/etcd-data/etcd-network/etcd-network-2/"}
{"level":"info","ts":"2021-11-30T23:55:26.033Z","caller":"etcdmain/etcd.go:115","msg":"server has been already initialized","data-dir":"/var/etcd-data/etcd-network/etcd-network-2/","dir-type":"member"}
{"level":"info","ts":"2021-11-30T23:55:26.033Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["https://192.168.2.4:2382"]}{"level":"info","ts":"2021-11-30T23:55:26.033Z","caller":"embed/etcd.go:488","msg":"starting with peer TLS","tls-info":"cert = /srv/kubernetes/common_server.cer, key = /srv/kubernetes/common_server_key.pem, client-cert=, client-key=, trusted-ca = /srv/kubernetes/ca.cer, client-cert-auth = true, crl-file = /srv/kubernetes/paas.crl","cipher-suites":[]}
{"level":"info","ts":"2021-11-30T23:55:26.038Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["https://127.0.0.1:4003","https://192.168.2.4:4003"]}
{"level":"info","ts":"2021-11-30T23:55:26.038Z","caller":"embed/etcd.go:317","msg":"starting an etcd server","etcd-version":"3.5.0","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.17.3","go-os":"linux","go-arch":"arm64","max-cpu-set":126,"max-cpu-available":126,"member-initialized":true,"name":"etcd-network-2","data-dir":"/var/etcd-data/etcd-network/etcd-network-2/","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/etcd-data/etcd-network/etcd-network-2/member","force-new-cluster":false,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":50000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["https://192.168.2.4:2382"],"listen-peer-urls":["https://192.168.2.4:2382"],"advertise-client-urls":["https://192.168.2.4:4003"],"listen-client-urls":["https://127.0.0.1:4003","https://192.168.2.4:4003"],"listen-metrics-urls":["https://192.168.2.4:4007"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"existing","initial-cluster-token":"","quota-size-bytes":8589934592,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
{"level":"info","ts":"2021-11-30T23:55:26.039Z","caller":"etcdserver/backend.go:44","msg":"setting backend batch interval","batch interval":"1s"}
{"level":"info","ts":"2021-11-30T23:55:26.044Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/var/etcd-data/etcd-network/etcd-network-2/member/snap/db","took":"5.33725ms"}
{"level":"info","ts":"2021-11-30T23:55:26.081Z","caller":"etcdserver/server.go:512","msg":"recovered v2 store from snapshot","snapshot-index":3,"snapshot-size":"7.6 kB"}
{"level":"info","ts":"2021-11-30T23:55:26.081Z","caller":"etcdserver/server.go:522","msg":"recovered v3 backend from snapshot","backend-size-bytes":1585152,"backend-size":"1.6 MB","backend-size-in-use-bytes":741376,"backend-size-in-use":"741 kB"}{"level":"info","ts":"2021-11-30T23:55:26.126Z","caller":"etcdserver/raft.go:483","msg":"restarting local member","cluster-id":"5017ec7fdb3b8d62","local-member-id":"82f53ce9e770fb7b","commit-index":18711}
{"level":"info","ts":"2021-11-30T23:55:26.127Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"82f53ce9e770fb7b switched to configuration voters=(8096206227661897536 9436515569532730235 14749687755696706107)"}
{"level":"info","ts":"2021-11-30T23:55:26.127Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"82f53ce9e770fb7b became follower at term 15"}
{"level":"info","ts":"2021-11-30T23:55:26.127Z","logger":"raft","caller":"etcdserver/zap_raft.go:77","msg":"newRaft 82f53ce9e770fb7b [peers: [705b80ab2417bf40,82f53ce9e770fb7b,ccb16addda3b123b], term: 15, commit: 18711, applied: 3, lastindex: 18712, lastterm: 15]"}
{"level":"info","ts":"2021-11-30T23:55:26.127Z","caller":"membership/cluster.go:278","msg":"recovered/added member from store","cluster-id":"5017ec7fdb3b8d62","local-member-id":"82f53ce9e770fb7b","recovered-remote-peer-id":"705b80ab2417bf40","recovered-remote-peer-urls":["https://192.168.2.2:2382"]}
{"level":"info","ts":"2021-11-30T23:55:26.127Z","caller":"membership/cluster.go:278","msg":"recovered/added member from store","cluster-id":"5017ec7fdb3b8d62","local-member-id":"82f53ce9e770fb7b","recovered-remote-peer-id":"82f53ce9e770fb7b","recovered-remote-peer-urls":["https://192.168.2.4:2382"]}
{"level":"info","ts":"2021-11-30T23:55:26.127Z","caller":"membership/cluster.go:278","msg":"recovered/added member from store","cluster-id":"5017ec7fdb3b8d62","local-member-id":"82f53ce9e770fb7b","recovered-remote-peer-id":"ccb16addda3b123b","recovered-remote-peer-urls":["https://192.168.2.3:2382"]}
{"level":"warn","ts":"2021-11-30T23:55:26.128Z","caller":"auth/store.go:1222","msg":"simple token is not cryptographically signed"}
{"level":"info","ts":"2021-11-30T23:55:26.128Z","caller":"mvcc/kvstore.go:345","msg":"restored last compact revision","meta-bucket-name":"meta","meta-bucket-name-key":"finishedCompactRev","restored-compact-revision":902975}
{"level":"info","ts":"2021-11-30T23:55:26.129Z","caller":"mvcc/kvstore.go:415","msg":"kvstore restored","current-rev":903627}
{"level":"info","ts":"2021-11-30T23:55:26.129Z","caller":"etcdserver/quota.go:117","msg":"enabled backend quota","quota-name":"v3-applier","quota-size-bytes":8589934592,"quota-size":"8.6 GB"}
{"level":"info","ts":"2021-11-30T23:55:26.134Z","caller":"rafthttp/peer.go:133","msg":"starting remote peer","remote-peer-id":"705b80ab2417bf40"}
{"level":"info","ts":"2021-11-30T23:55:26.134Z","caller":"rafthttp/pipeline.go:72","msg":"started HTTP pipelining with remote peer","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"705b80ab2417bf40"}
{"level":"info","ts":"2021-11-30T23:55:26.134Z","caller":"rafthttp/stream.go:169","msg":"started stream writer with remote peer","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"705b80ab2417bf40"}
{"level":"info","ts":"2021-11-30T23:55:26.134Z","caller":"rafthttp/stream.go:169","msg":"started stream writer with remote peer","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"705b80ab2417bf40"}
{"level":"info","ts":"2021-11-30T23:55:26.135Z","caller":"rafthttp/peer.go:137","msg":"started remote peer","remote-peer-id":"705b80ab2417bf40"}
{"level":"info","ts":"2021-11-30T23:55:26.135Z","caller":"rafthttp/transport.go:317","msg":"added remote peer","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"705b80ab2417bf40","remote-peer-urls":["https://192.168.2.2:2382"]}
{"level":"info","ts":"2021-11-30T23:55:26.135Z","caller":"rafthttp/stream.go:395","msg":"started stream reader with remote peer","stream-reader-type":"stream Message","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"705b80ab2417bf40"}
{"level":"info","ts":"2021-11-30T23:55:26.135Z","caller":"rafthttp/peer.go:133","msg":"starting remote peer","remote-peer-id":"ccb16addda3b123b"}
{"level":"info","ts":"2021-11-30T23:55:26.135Z","caller":"rafthttp/pipeline.go:72","msg":"started HTTP pipelining with remote peer","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"ccb16addda3b123b"}
{"level":"info","ts":"2021-11-30T23:55:26.135Z","caller":"rafthttp/stream.go:395","msg":"started stream reader with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"705b80ab2417bf40"}
{"level":"info","ts":"2021-11-30T23:55:26.136Z","caller":"rafthttp/stream.go:169","msg":"started stream writer with remote peer","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"ccb16addda3b123b"}
{"level":"info","ts":"2021-11-30T23:55:26.137Z","caller":"rafthttp/stream.go:169","msg":"started stream writer with remote peer","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"ccb16addda3b123b"}
{"level":"info","ts":"2021-11-30T23:55:26.137Z","caller":"rafthttp/peer.go:137","msg":"started remote peer","remote-peer-id":"ccb16addda3b123b"}
{"level":"info","ts":"2021-11-30T23:55:26.137Z","caller":"rafthttp/stream.go:395","msg":"started stream reader with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"ccb16addda3b123b"}
{"level":"info","ts":"2021-11-30T23:55:26.137Z","caller":"rafthttp/transport.go:317","msg":"added remote peer","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"ccb16addda3b123b","remote-peer-urls":["https://192.168.2.3:2382"]}
{"level":"info","ts":"2021-11-30T23:55:26.137Z","caller":"rafthttp/stream.go:395","msg":"started stream reader with remote peer","stream-reader-type":"stream Message","local-member-id":"82f53ce9e770fb7b","remote-peer-id":"ccb16addda3b123b"}
{"level":"info","ts":"2021-11-30T23:55:26.139Z","caller":"etcdserver/server.go:861","msg":"starting etcd server","local-member-id":"82f53ce9e770fb7b","local-server-version":"3.5.0","cluster-version":"to_be_decided"}
{"level":"info","ts":"2021-11-30T23:55:26.139Z","caller":"etcdserver/server.go:762","msg":"starting initial election tick advance","election-ticks":10}
{"level":"info","ts":"2021-11-30T23:55:26.140Z","caller":"membership/cluster.go:584","msg":"set initial cluster version","cluster-id":"5017ec7fdb3b8d62","local-member-id":"82f53ce9e770fb7b","cluster-version":"3.4"}
{"level":"info","ts":"2021-11-30T23:55:26.140Z","caller":"api/capability.go:75","msg":"enabled capabilities for version","cluster-version":"3.4"}
{"level":"info","ts":"2021-11-30T23:55:26.144Z","caller":"embed/etcd.go:697","msg":"starting with client TLS","tls-info":"cert = /srv/kubernetes/common_server.cer, key = /srv/kubernetes/common_server_key.pem, client-cert=, client-key=, trusted-ca = /srv/kubernetes/ca.cer, client-cert-auth = true, crl-file = /srv/kubernetes/paas.crl","cipher-suites":[]}
{"level":"info","ts":"2021-11-30T23:55:26.144Z","caller":"embed/etcd.go:590","msg":"serving peer traffic","address":"192.168.2.4:2382"}
{"level":"info","ts":"2021-11-30T23:55:26.144Z","caller":"embed/etcd.go:562","msg":"cmux::serve","address":"192.168.2.4:2382"}
{"level":"info","ts":"2021-11-30T23:55:26.146Z","caller":"embed/etcd.go:286","msg":"now serving peer/client/metrics","local-member-id":"82f53ce9e770fb7b","initial-advertise-peer-urls":["https://192.168.2.4:2382"],"listen-peer-urls":["https://192.168.2.4:2382"],"advertise-client-urls":["https://192.168.2.4:4003"],"listen-client-urls":["https://127.0.0.1:4003","https://192.168.2.4:4003"],"listen-metrics-urls":["https://192.168.2.4:4007"]}
{"level":"info","ts":"2021-11-30T23:55:26.146Z","caller":"embed/etcd.go:772","msg":"serving metrics","address":"https://192.168.2.4:4007"}

```

**Comment by ptabor** [comment] 2021-12-07 16:32
Interesting. What's the exact etcd version. 

In general the behavior you are describing might happen in:  `--consistency="s"` serializable mode (that is NOT the default for etcdctl get), but should NOT happen in the `--consistency="l"` mode (the default ONE), where the 
reader should get from the leader the index of 'head revision' first and only if the replica is synced to the revision answer the request. 

Last changes around the logic I'm aware of were in:  https://github.com/etcd-io/etcd/pull/12762  (@wpedrak FYI)

Things to verify
 - [ ] is it a difference between 3.4.x and 3.5.0 ? 
 - [ ] is --consistency=linearizable correctly passed from etcdctl to the server.

**Comment by ahrtr** [comment] 2021-12-08 22:44
I am also thinking probably the the 3 members are not belong to the same cluster at all. Could you execute the following commands to double confirm?

```
etcdctl --endpoints https://192.168.2.4:4003 member list -w table
etcdctl --endpoints https://192.168.2.4:4003 endpoint status -w table
etcdctl --endpoints https://192.168.2.4:4003 endpoint heath -w table
```

Please also double confirm the etcd and etcdctl versions using command `etcd --version` and `etcdctl version`

**Comment by moonovo** [comment] 2021-12-09 13:19
The fault in the environment has been rectified. My way of avoiding it: the client still uses clientv3 of the etcd 3.4 version. After I downgraded the etcd server version to 3.4.15, the problem does not occur again.

**Comment by moonovo** [comment] 2021-12-09 13:54
I can't restart etcd because when I do, I get the panic:  [failed to recover v3 backend from snapshot](https://github.com/etcd-io/etcd/blob/73080a716634f45d50d0593e0454ed3206a52f5b/server/etcdserver/server.go#L515):

**Comment by bigfudan** [comment] 2021-12-25 04:05
wow, I have meet the same question, have U fixed it?

**Comment by serathius** [comment] 2022-01-10 16:35
I'm unable to reproduce this with Etcd v3.5.1 and etcdctl v3.4 and v3.5. I run 3 member cluster where each member restarts every 10 seconds with a periodic get revision (every 1 second) and etcdctl check perf to generate load. I have never seen an inconsistent read. 

Can you provide more detailed reproduction steps?

**Comment by serathius** [comment] 2022-01-10 16:36
This is a blocker for v3.5.2 so I will focus on this. Help would be appreciated!

**Comment by ptabor** [comment] 2022-01-11 12:32
@moonovo 
> when the 192.168.2.4 node starts up, it may have replaced the old etcd data into the etcd data directory, I guess.

1. What do you mean by 'get replaced' is there process that touches the files... or just etcd put operation that hits the server between shutdown. 

2. Does this problem happened once or you are reliably able to reproduce it  ?
   How frequently it happens (per how many tries) ? Can you, please, share a script to reproduce it...

3. Does the problem disappears after some time from restart... (i.e. it's flake during restart) and eventually the lagging replica catches up the leader...   or the server lands in such persistent disconnect ?

> I can't restart etcd because when I do, I get the panic: failed to recover v3 backend from snapshot， the error is "failed to find database snapshot file (snap: snapshot file doesn't exist)"

4. That's even more scary. Does it mean every time you repro the problem: the-lagging-one/the-not-lagging-ones/all nodes cannot be restarted ? How do you restart the nodes (kill signal ? Ctrl-C ?) ?

5. Is it the same state you keep working on... or it's reproductionable from the 'empty' inital state ?

**Comment by serathius** [comment] 2022-01-11 16:03
Wrote a test that concurrently writes, reads and inject failures (partitions or restarts) and ensures that reads get monotonic revision. Didn't see any inconsistencies. https://github.com/etcd-io/etcd/pull/13584

Without more details from @moonovo  I will not be able to reproduce it.

**Comment by serathius** [comment] 2022-01-12 12:04
With a test specific for this problem and no reproduction I'm inclined to remove this as a blocker for v3.5.2 release.

**Comment by moonovo** [comment] 2022-01-18 13:31
This issue can be closed. I found the reason why consistency_index was not updated, but I did not find the reason why revision was inconsistent.
The reason why consistency_index is not updated is that the term field is added to the meta bucket after the upgrade from 3.4.15 to 3.5.0,
Then we rolled back from 3.5.0 to 3.4.15(we backup and restore, the raft term starts from 1.) The term field is not updated in 3.4.15,
After the version is upgraded to 3.5.0 again, consistency_index is not updated because the term in db is greater than the raft term.

**Comment by ptabor** [comment] 2022-01-18 14:08
Thank you @moonovo. That's a good story for rollback->rollforward safety, that @serathius 
was looking into.  Starting from 3.6 with versioning the rollback should be explicit and drop the 3.5 content. 

I think in 3.5 the server should during bootstrap reconcile Term between WAL logs and bbolt considering bbolt to be authoritative source of truth.

**Comment by chaochn47** [comment] 2022-03-28 06:52
Thanks @ptabor for calling this out in the "3.5 inconsistency issue" email thread !!!!

This issue looks worrying that makes 3.5.x rollback a risky operation. I've got a reproduction (manual testing)[reproduction.log](https://github.com/etcd-io/etcd/files/8360244/reproduction.log) after following the provided description from @moonovo . 
```bash
etcd_endpoints=http://127.0.0.1:2379,http://127.0.0.1:22379,http://127.0.0.1:32379
 
echo $etcd_endpoints | tr ',' '\n' | xargs -I '{}' etcdctl --endpoints '{}' get foo -w json
{"header":{"cluster_id":9108655428580501207,"member_id":16513504468151473617,"revision":5,"raft_term":3},"kvs":[{"key":"Zm9v","create_revision":2,"mod_revision":5,"version":4,"value":"ZXJyb3I="}],"count":1}
{"header":{"cluster_id":9108655428580501207,"member_id":17404356270211841594,"revision":5,"raft_term":3},"kvs":[{"key":"Zm9v","create_revision":2,"mod_revision":5,"version":4,"value":"ZXJyb3I="}],"count":1}
{"header":{"cluster_id":9108655428580501207,"member_id":463034352321715000,"revision":9,"raft_term":3},"kvs":[{"key":"Zm9v","create_revision":2,"mod_revision":9,"version":8,"value":"ZXJyb3I="}],"count":1}
```

To answer your question @moonovo
> but I did not find the reason why revision was inconsistent

The lagging-behind consistent_index node will re-apply some raft entries when it restarts. (the consistent_index will be reloaded from disk and unnecessarily reply because this following code)
https://github.com/etcd-io/etcd/blob/99018a77bea9a9d29962e5169876c64e02739c52/server/etcdserver/server.go#L2156-L2163

Also the initial-corruption-check feature was broken like that. /cc @serathius 
```
{"level":"warn","ts":"2022-03-28T06:05:40.650Z","caller":"etcdserver/corrupt.go:289","msg":"failed hash kv request","local-member-id":"66d074a48f05b38","requested-revision":7,"remote-peer-endpoint":"http://127.0.0.1:12382","error":"Get \"http://127.0.0.1:12382/members/hashkv\": EOF"}
{"level":"warn","ts":"2022-03-28T06:05:40.650Z","caller":"etcdserver/corrupt.go:289","msg":"failed hash kv request","local-member-id":"66d074a48f05b38","requested-revision":7,"remote-peer-endpoint":"http://127.0.0.1:22382","error":"Get \"http://127.0.0.1:22382/members/hashkv\": EOF"}
{"level":"info","ts":"2022-03-28T06:05:40.650Z","caller":"etcdserver/corrupt.go:116","msg":"initial corruption checking passed; no corruption","local-member-id":"66d074a48f05b38"}
```

**Comment by ahrtr** [comment] 2022-03-29 23:25
Please refer to discussion in [pull/13844](https://github.com/etcd-io/etcd/pull/13844) and [issues/13766](https://github.com/etcd-io/etcd/issues/13766)

**Comment by michaljasionowski** [comment] 2022-03-30 11:43
Thanks @chaochn47, that was very helpful. I managed to reproduce it as well
```
{"header":{"cluster_id":9108655428580501207,"member_id":16513504468151473617,"revision":4,"raft_term":5},"kvs":[{"key":"Zm9v","create_revision":2,"mod_revision":4,"version":3,"value":"ZXJyb3I="}],"count":1}
{"header":{"cluster_id":9108655428580501207,"member_id":17404356270211841594,"revision":4,"raft_term":5},"kvs":[{"key":"Zm9v","create_revision":2,"mod_revision":4,"version":3,"value":"ZXJyb3I="}],"count":1}
{"header":{"cluster_id":9108655428580501207,"member_id":17604630397935920175,"revision":5,"raft_term":5},"kvs":[{"key":"Zm9v","create_revision":2,"mod_revision":5,"version":4,"value":"ZXJyb3I="}],"count":1}
```
and also initial corruption check passed
```
{"level":"info","ts":"2022-03-30T09:54:41.238Z","caller":"etcdserver/corrupt.go:116","msg":"initial corruption checking passed; no corruption","local-member-id":"f4503612d703a42f"}
```

**Comment by michaljasionowski** [comment] 2022-04-01 11:28
This the script I used for reproduction: [upgradedowngrade.log](https://github.com/etcd-io/etcd/files/8397249/upgradedowngrade.log). It sets 3 ariables at the beginning that have to be updated

**Comment by serathius** [comment] 2022-04-06 14:39
I have been looking into this issue and found a strange behavior, looks like etcd v3.5.2 upon restart reapplies entries. Each restart results in etcd reapplying the last entry. I have simplified the script provided by @michaljasionowski 
 [script.txt](https://github.com/etcd-io/etcd/files/8427001/script.txt)

If we look at data dir of:

* WAL is identical between all instances
```
./bin/tools/etcd-dump-logs step5
Snapshot:
term=1 index=3 nodes=[a23bb980081aa72d e52bc0d24cfe95d1 f188b1d0c651be3a] confstate={"voters":[11690141217313171245,16513504468151473617,17404356270211841594],"auto_leave":false}
Start dumping log entries from snapshot.
WAL metadata:
nodeID=a23bb980081aa72d clusterID=7e6871da41f966d7 term=2 commitIndex=12 vote=e52bc0d24cfe95d1
WAL entries:
lastIndex=12
term	     index	type	data
   2	         4	norm	
   2	         5	norm	method=PUT path="/0/members/e52bc0d24cfe95d1/attributes" val="{\"name\":\"infra1\",\"clientURLs\":[\"http://127.0.0.1:2379\"]}"
   2	         6	norm	method=PUT path="/0/members/a23bb980081aa72d/attributes" val="{\"name\":\"infra3\",\"clientURLs\":[\"http://127.0.0.1:32379\"]}"
   2	         7	norm	method=PUT path="/0/members/f188b1d0c651be3a/attributes" val="{\"name\":\"infra2\",\"clientURLs\":[\"http://127.0.0.1:22379\"]}"
   2	         8	norm	method=PUT path="/0/version" val="3.4.0"
   2	         9	norm	header:<ID:12046425309767173124 > put:<key:"foo" value:"bar1" > 
   2	        10	norm	method=PUT path="/0/members/a23bb980081aa72d/attributes" val="{\"name\":\"infra3\",\"clientURLs\":[\"http://127.0.0.1:32379\"]}"
   2	        11	norm	header:<ID:12046425309769246980 > put:<key:"foo" value:"bar2" > 
   2	        12	norm	method=PUT path="/0/members/a23bb980081aa72d/attributes" val="{\"name\":\"infra3\",\"clientURLs\":[\"http://127.0.0.1:32379\"]}"

Entry types (Normal,ConfigChange) count is : 9
```
* Corrupted etcd v3.5 has duplicated apply of last put:

```
./bin/tools/etcd-dump-db iterate-bucket step5 key --decode
rev={main:4 sub:0}, value=[key "foo" | val "bar2" | created 2 | mod 4 | ver 3]
rev={main:3 sub:0}, value=[key "foo" | val "bar2" | created 2 | mod 3 | ver 2]
rev={main:2 sub:0}, value=[key "foo" | val "bar1" | created 2 | mod 2 | ver 1]
```

Current guess is that this is caused by outdated term value caused by downgrade. cc @ptabor

**Comment by serathius** [comment] 2022-04-06 15:31
Looks like corruption happens before the restart, restarting just causes etcd to reapply the entries. `consistent_index` in db equals `9`, which is WAL entry before `put foo bar`, however looks like the apply was already executed. The `foo` = bar` is already present in key bucket. 
```
etcd $ ./bin/tools/etcd-dump-logs step4
Snapshot:
term=1 index=3 nodes=[a23bb980081aa72d e52bc0d24cfe95d1 f188b1d0c651be3a] confstate={"voters":[11690141217313171245,16513504468151473617,17404356270211841594],"auto_leave":false}
Start dumping log entries from snapshot.
WAL metadata:
nodeID=a23bb980081aa72d clusterID=7e6871da41f966d7 term=2 commitIndex=10 vote=e52bc0d24cfe95d1
WAL entries:
lastIndex=11
term	     index	type	data
   2	         4	norm	
   2	         5	norm	method=PUT path="/0/members/e52bc0d24cfe95d1/attributes" val="{\"name\":\"infra1\",\"clientURLs\":[\"http://127.0.0.1:2379\"]}"
   2	         6	norm	method=PUT path="/0/members/a23bb980081aa72d/attributes" val="{\"name\":\"infra3\",\"clientURLs\":[\"http://127.0.0.1:32379\"]}"
   2	         7	norm	method=PUT path="/0/members/f188b1d0c651be3a/attributes" val="{\"name\":\"infra2\",\"clientURLs\":[\"http://127.0.0.1:22379\"]}"
   2	         8	norm	method=PUT path="/0/version" val="3.4.0"
   2	         9	norm	header:<ID:12046425313434587396 > put:<key:"foo" value:"bar1" > 
   2	        10	norm	method=PUT path="/0/members/a23bb980081aa72d/attributes" val="{\"name\":\"infra3\",\"clientURLs\":[\"http://127.0.0.1:32379\"]}"
   2	        11	norm	header:<ID:12046425313437170180 > put:<key:"foo" value:"bar2" > 

Entry types (Normal,ConfigChange) count is : 8
```

```
etcd $ ./bin/tools/etcd-dump-db iterate-bucket step4 key --decode
rev={main:3 sub:0}, value=[key "foo" | val "bar2" | created 2 | mod 3 | ver 2]
rev={main:2 sub:0}, value=[key "foo" | val "bar1" | created 2 | mod 2 | ver 1]
```

```
etcd $ ./bin/tools/etcd-dump-db iterate-bucket step4 meta --decode
key="term", value=3
key="consistent_index", value=9
key="confState", value="{\"voters\":[15985099378392235387],\"auto_leave\":false}"
```

**Comment by serathius** [comment] 2022-04-06 15:32
cc @ahrtr

**Comment by serathius** [comment] 2022-04-07 10:26
The cause of corruption is https://github.com/etcd-io/etcd/blob/451ea5406edff59c1c881833ed7ba32cb9253f01/server/storage/schema/cindex.go#L66-L69

Outdated term field (caused by downgrade) results in etcd applying the record without updating CI. The case is artificial because downgrades are not officially supported, but this brought up two issues that are not related to downgrades. Still thinking what exactly is the problem that should be fixed:
 * Etcd v3.5 trusting term stored in DB and not one in WAL. This doesn't seem safe in v3.5, possibly should be delayed to v3.6?
 * Etcd applying the entry without even though CI update "failed".

Possibly both cases would be worth fixing. cc @spzala @ahrtr @ptabor for opinion.

**Comment by serathius** [comment] 2022-04-07 11:37
Looks like both issues were introduced here https://github.com/etcd-io/etcd/pull/12855#commitcomment-70713670 when we merged migrator CI update logic with apply one.

**Comment by ptabor** [comment] 2022-04-07 12:29
Intuitively applyEntries should get never executed if we are in the wrong term. 
Applies should happen only up to the last 'HardState' found in the WAL log and it should determine whether entry is a subject to apply or not.  
So I think it's harmful defense in depth, but will need to deeper dive from the original logic from pre-refactoring to confirm.

**Closed** 2022-04-07 19:12 UTC
Labels: Help Wanted, important
