### ISSUE TITLE
Access etcd service through the client, the error shows "rejected connection"

### ISSUE THREAD

**Issue by SingleThread** [etcd-io/etcd#13801] opened 2022-03-15 03:34 UTC
### What happened?

Access etcd service through the client, the error shows "rejected connection"
{"level":"warn","ts":"2022-03-15T03:02:56.740Z","caller":"embed/config_logging.go:169","msg":"rejected connection","remote-addr":"*.*.*.*:*","server-name":"","error":"EOF"}

### What did you expect to happen?

Client call succeeded

### How can we reproduce it (as minimally and precisely as possible)?

I would like to know under what circumstances this error occurs

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by gengzongjie** [comment] 2022-04-20 07:00
It looks like can't be reproduced

**Comment by donalhunt** [comment] 2022-05-06 10:17
Queries related to this error seem to show up from time to time on the issue tracker (none seem to have a definitive answer).

I have a 3-node cluster which is showing signs of the same issue on version 3.5.1.
Currently debugging but suspect the issue is on the client side (we're using https://github.com/IBM/etcd-java) rather than the server side.

Will share any findings here.

**Comment by serathius** [comment] 2022-09-28 08:32
Closing as part of migration of issues labeled as questions to GitHub discussions. 
GitHub discussions makes it easier for the whole community to provide answered.

If you think your question is still relevant, feel free to ask at https://github.com/etcd-io/etcd/discussions

**Closed by serathius** 2022-09-28 08:32 UTC
Labels: type/question

**Comment by RanjithNKtrr** [comment] 2023-12-01 08:57
@donalhunt Did you got any findings for this? I am seeing lot of similar warnings in etcd pods.
