### ISSUE TITLE
occasionally lease expire but other etcd rpc is ok

### ISSUE THREAD

**Issue by hyfrey** [etcd-io/etcd#9604] opened 2018-04-23 12:25 UTC
We are using etcd lease to track process liveness. There are thousands of etcd clients deployed globally,  three etcd servers deployed in one data center. We encounter occasionally lease expire of some processes, we can see from logs [etcd_session_expire.log](https://github.com/coreos/etcd/files/1938113/etcd_session_expire.log) that etcd client keep send LeaseKeepAlive message to etcd server but doesn't receive response, until lease expire. However, there is no problem with MemberList method, it can return the newest etcd server nodes.  This happen several times per month.

etcd client version: v3.3.2
etcd server version: v.3.3.2

**Comment by gyuho** [comment] 2018-04-23 20:56
> We encounter occasionally lease expire of some processes, we can see from logs etcd_session_expire.log that etcd client keep send LeaseKeepAlive message to etcd server but doesn't receive response, until lease expire.

Which line exactly shows this behavior? Can you pinpoint lines from the file?

**Comment by hyfrey** [comment] 2018-04-24 04:34
We use Session in etcd client concurrency package.

If there is no problem, etcd server returns LeaseKeepAlive response
```
2018-04-23T11:26:40.839+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:26:41.027+0800	INFO	zap/payload_interceptors.go:132	server response payload logged as grpc.response.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.response.content": {"msg": {"header":{"clusterId":"13713797239736021387","memberId":"13437693390388995861","revision":"72664","raftTerm":"2"},"ID":"2816265784770672200","TTL":"600"}}}
```

According to current etcd client code, it will send LeaseKeepAlive request every 500 milliseconds if it does not receive response in 1/3 TTL time. We can see from the following log etcd client keep sending request every 500 milliseconds but does not receive LeaseKeepAlive response. However the following log shows  MemberList method returns in 188 milliseconds with current etcd server node members.
```
2018-04-23T11:30:53.050+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:30:53.550+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:30:54.050+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:30:54.206+0800	INFO	zap/payload_interceptors.go:132	client request payload logged as grpc.request.content	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Cluster", "grpc.method": "MemberList", "grpc.request.content": {"msg": {}}}
2018-04-23T11:30:54.394+0800	INFO	zap/payload_interceptors.go:132	client response payload logged as grpc.response.content	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Cluster", "grpc.method": "MemberList", "grpc.response.content": {"msg": {"header":{"clusterId":"13713797239736021387","memberId":"13437693390388995861","raftTerm":"2"},"members":[{"ID":"9315242867359955699","name":"etcd2","peerURLs":["http://0.0.0.1:2380"],"clientURLs":["http://0.0.0.1:2379"]},{"ID":"9816179579541572759","name":"etcd1","peerURLs":["http://0.0.0.2:2380"],"clientURLs":["http://0.0.0.2:2379"]},{"ID":"13437693390388995861","name":"etcd0","peerURLs":["http://0.0.0.3:2380"],"clientURLs":["http://0.0.0.3:2379"]}]}}}
2018-04-23T11:30:54.394+0800	DEBUG	zap/client_interceptors.go:48	finished client unary call	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Cluster", "grpc.method": "MemberList", "grpc.code": "OK", "grpc.time_ms": 188}
2018-04-23T11:30:54.551+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:30:55.051+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:30:55.551+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:30:56.051+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
```

Finally, lease is expired. Our code will call concurreny.Session.Close() to clean up etcd session. We can see from the following log LeaseRevoke method tells us lease is not found, which is right, since lease is probably expired on etcd server
```
2018-04-23T11:36:40.876+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:36:41.376+0800	INFO	zap/payload_interceptors.go:132	server request payload logged as grpc.request.content field	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseKeepAlive", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:36:41.549+0800	INFO	zap/payload_interceptors.go:132	client request payload logged as grpc.request.content	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseRevoke", "grpc.request.content": {"msg": {"ID":"2816265784770672200"}}}
2018-04-23T11:36:41.738+0800	DEBUG	zap/client_interceptors.go:48	finished client unary call	{"instance_id": "fymqy9774imo", "system": "grpc", "span.kind": "client", "grpc.service": "etcdserverpb.Lease", "grpc.method": "LeaseRevoke", "error": "rpc error: code = NotFound desc = etcdserver: requested lease not found", "grpc.code": "NotFound", "grpc.time_ms": 189}
```

**Comment by gyuho** [comment] 2018-05-03 17:54
@hyfrey Can you provide a simple snippet of code to reproduce this issue?

**Comment by spzala** [comment] 2019-10-11 16:32
Closing this per triage guidelines as can't reproduce without further information. Please reopen if needed. Thanks!

**Closed by spzala** 2019-10-11 16:32 UTC
Labels: area/question
