### ISSUE TITLE
gRPC code Unavailable instead Canceled

### ISSUE THREAD

**Issue by arslanbekov** [etcd-io/etcd#10289] opened 2018-11-29 15:44 UTC
After this PR https://github.com/etcd-io/etcd/pull/9178 we get:

It's in **etcd** running with parameter `--log-package-levels=debug`:

    ...
    etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 61; CANCEL")
    etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 78; CANCEL")
    ...
in my prometheus i see: 

    sum by(grpc_type, grpc_service, grpc_code) (grpc_server_handled_total{grpc_code="Unavailable", job="etcd", grpc_type="bidi_stream"}) = 4172

But it seems to me, this not error, and should not fall under [Unavailable Code](https://github.com/grpc/grpc-go/blob/master/codes/codes.go#L139)
> Unavailable indicates the service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff. See litmus test above for deciding between FailedPrecondition, Aborted, and Unavailable.

It looks like [Canceled Code](https://github.com/grpc/grpc-go/blob/master/codes/codes.go#L35)
> Canceled indicates the operation was canceled (typically by the caller).

Now everyone who uses prometheus operator + alertmanager, get [this](https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kube-etcd/templates/etcd3.rules.yaml#L29) alert, because **CANCEL** falls under [Unavailable](https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3rpc/util.go#L113)

#9725, #9576, #9166 https://github.com/openshift/origin/issues/20311, https://github.com/coreos/prometheus-operator/issues/2046, and in [google groups](https://groups.google.com/forum/#!topic/etcd-dev/ujWldr3ys9M)

**Comment by xiang90** [comment] 2018-11-29 16:24
@Arslanbekov From #9178, it seems that gRPC returned code is unavailable, but the description is canceled. Can you open an issue in grcp-go to ask?

**Comment by Arslanbekov** [comment] 2018-11-29 16:30
@xiang90 
> but the description is canceled

are you talking about it? 
https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3rpc/util.go#L113

I will create issue in `grpc-go`, thanks

**Comment by xiang90** [comment] 2018-11-29 16:47
yes. thank you.

**Comment by hexfusion** [comment] 2018-12-07 15:31
@Arslanbekov just touching base on this did you see @menghanl (grpc-go maintainer)  comment above?

**Comment by Arslanbekov** [comment] 2018-12-07 15:39
Yes, @hexfusion thanks for notifying, there is no free time to do it now. Maybe someone will help?

**Comment by hexfusion** [comment] 2018-12-07 17:08
> Yes, @hexfusion thanks for notifying, there is no free time to do it now. Maybe someone will help?

@Arslanbekov I will try to take a look soon.

**Comment by menghanl** [comment] 2019-01-17 21:21
@hexfusion Did you get time to try this? Thanks!

**Comment by hexfusion** [comment] 2019-01-17 21:23
@menghanl thanks for the reminder, I will work on it before the end of the week.

**Comment by hexfusion** [comment] 2019-01-21 20:46
@spzala could you please take a look?

**Comment by spzala** [comment] 2019-01-21 20:48
@hexfusion I sure will, thanks!

**Comment by spzala** [comment] 2019-01-30 04:01
So not sure if I am doing something incorrect or in a different way but I could not reproduce the issue exactly but I do see ```rpc error: code = Unavailable``` (i.e. https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3rpc/util.go#L108 instead of L113 as commented in the issue above) 
This is how I am testing:
Run this on server:
```./bin/etcd --data-dir=data.etcd --name ${ETCD_NAME} --advertise-client-urls ${ADVERTISE_CLIENT_URLS} --listen-client-urls ${LISTEN_CLIENT_URLS} --initial-cluster ${INITIAL_CLUSTER} --initial-cluster-state ${INITIAL_CLUSTER_STATE} --initial-cluster-token ${INITIAL_CLUSTER_TOKEN} --cert-file $CERT_FILE --trusted-ca-file $TRUSTED_CA_FILE --key-file $KEY_FILE --debug```
Run below commands on client (a separate VM) on two diff cli: 
```./bin/etcdctl --endpoints https://<ip>:2379 watch foo --cacert /root/cfssl/ca.pem --cert /root/cfssl/client.pem --key /root/cfssl/client-key.pem```
```./bin/etcdctl --endpoints https://<ip>:2379 put foo bar --cacert /root/cfssl/ca.pem --cert /root/cfssl/client.pem --key /root/cfssl/client-key.pem```
And then cancel the watch command (ctrl+c) which gives me following error most of the time, 
```2019-01-30 03:35:31.618639 D | etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = client disconnected”)``` 

Also, @menghanl thanks but I couldn't see the print output in the etcd log after I add the line to `mapRecvMsgError`. Is it logged somewhere other than etcd server output? I also tried adding  `GRPC_GO_LOG_VERBOSITY_LEVEL=2` and other flags in env. Since I couldn't reproduce issue as explained above, I also tried couple of other Println in different package functions just to play around but didn't see anything in the log.  Thanks!

**Comment by spzala** [comment] 2019-01-30 21:19
@menghanl thanks much for the great detail!! and yes etcds uses ```SetLoggerV2``` so that might be the reason. I will run again modifying it not to override default grpclog. Also for testing I used both, fmt.Printf and fmt.Println so as you guessed the problem might be something else but I will try again with grpclogger.  

About the etcd server flags and their values -  for the ones that I used here, I am copying below but you can find those and more flags at https://github.com/etcd-io/etcd/blob/master/etcdmain/help.go. With tls enabled, I have used https instead of http e.g. ADVERTISE_CLIENT_URLS=${HOST}:2379 where HOST is https://<fqdn>. 
```
--advertise-client-urls 'http://localhost:2379'
List of this member's client URLs to advertise to the public.
--listen-client-urls 'http://localhost:2379'
List of URLs to listen on for client traffic.
--initial-cluster 'default=http://localhost:2380'
Initial cluster configuration for bootstrapping.
--initial-cluster-state 'new'
Initial cluster state ('new' or 'existing').
--initial-cluster-token 'etcd-cluster'
Initial cluster token for the etcd cluster during bootstrap.
Specifying this can protect you from unintended cross-cluster interaction when running multiple clusters.
--cert-file ''
Path to the client server TLS cert file.
--key-file ''
Path to the client server TLS key file.
```
For the etcd client - https://github.com/etcd-io/etcd/tree/master/etcdctl 
```
--cacert=/tmp/ca.pem			
verify certificates of TLS-enabled secure servers using this CA bundle
--cert=/tmp/cert.pem				
identify secure client using this TLS certificate file
-key=/tmp/key.pem
identify secure client using this TLS key file
```

**Comment by jingyih** [comment] 2019-02-11 19:31
cc @jpbetz

**Comment by spzala** [comment] 2019-03-05 15:42
Thanks @hexfusion !!

**Comment by hexfusion** [comment] 2019-04-28 22:04
Update: @menghanl was right about the source of the issue the actual inbound error to mapRecvMsgError is.

`rpc error: code = Unknown desc = client disconnected`

I will connect the rest of the dots and come up with some resolution hopefully soon.

**Comment by hexfusion** [comment] 2019-04-29 04:24
I have thought about this for a while and although it does feel like there could be a middle ground between `Unknown` and `Unavailable` error codes in this situation. For example by allowing `Unknown` to conditionally remain as the error code similar to [1] vs forcing `Unavailable`. If we look at the gRPC spec [1] the client `Unavailable` seems sane vs server. So perhaps this is not a matter of using the wrong error code but a result of gRPC having 2 server transports [3]? @menghanl curious your thoughts?

/cc @brancz 

> 

Some data transmitted (e.g., request metadata written to TCP connection) before connection breaks | UNAVAILABLE | Client
-- | -- | --

Server shutting down ...................................................................................... | UNAVAILABLE | Server
-- | -- | --



[1]https://github.com/grpc/grpc-go/blob/66cd5249103cfe4638864f08462537504b07ff1d/internal/transport/handler_server.go#L426
[2] https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
[3] https://github.com/grpc/grpc-go/issues/1819#issuecomment-360648206 (won't fix)

**Comment by menghanl** [comment] 2019-04-29 20:37
@hexfusion Thanks for the findings!

> actual inbound error to mapRecvMsgError is.
> `rpc error: code = Unknown desc = client disconnected`

Do you know where this error is from? This looks like an error returned from a service handler with `fmt.Errorf`, instead of `status.Errorf` with an error code.
Also, the error reported originally is `rpc error: code = Unavailable desc = stream error: stream ID 61; CANCEL`, which has different description.

---

I think the issue raised here is not about which error code to return.
It more about the confusion caused by error code `Unavailable` while the error description says `CANCEL`.

What we want to figure out is why (how) `rpc error: code = Unavailable desc = stream error: stream ID 61; CANCEL` is generated.

**Comment by hexfusion** [comment] 2019-04-30 10:09
@menghanl thanks for the notes your questions are valid I will prioritize some time to get you those answers.

**Comment by hectorj2f** [comment] 2019-05-31 07:15
@hexfusion Is there any progress about this issue ? Certain etcd3 alert rules are being triggered because of this issue https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/etcd3_alert.rules.yml#L32 ?

**Comment by darwink** [comment] 2019-09-04 03:58
> @hexfusion Is there any progress about this issue ? Certain etcd3 alert rules are being triggered because of this issue https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/etcd3_alert.rules.yml#L32 ?

Any update or plan to fix it?

**Comment by siwyd** [comment] 2019-11-13 16:37
FYI, for those using the etcd mixin, I worked around this by tweaking the etcd selector:
```
        local etcd = import "etcd-mixin/mixin.libsonnet";

        etcd {
          _config+:: {
            etcd_selector: 'job="etcd",grpc_service!="etcdserverpb.Watch"'
          },
        }
```

**Comment by hexfusion** [comment] 2019-11-13 18:14
I am picking this back up now, hopefully for the last time to resolve.

**Comment by hexfusion** [comment] 2019-11-19 17:56
I have found the source of `Unavailable` instead of `Canceled`. 

https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3rpc/watch.go#L198-L201

When the watch is canceled we pass 

https://github.com/etcd-io/etcd/blob/63dd73c1869f1784f907b922f61571176a2802e8/etcdserver/api/v3rpc/rpctypes/error.go#L66

Which is not valid resulting in `codes.Unavailable` passed to status.New() resulting in the metrics also reporting Unavailable. In my local testing adding a new error using `codes.Canceled` allows the metrics to properly report.

I will raise a PR in a bit to resolve.

**Comment by Imunhatep** [comment] 2020-04-14 12:25
Any news on merging fixes?!

**Comment by immanuelfodor** [comment] 2020-12-12 18:31
This could solve some ongoing issues with Prometheus monitoring, will this PR be ever merged? 😃

**Closed** 2021-02-19 20:46 UTC
Labels: Investigating, area/question
