### ISSUE TITLE
v3 API get return unreadable content

### ISSUE THREAD

**Issue by daixiang0** [etcd-io/etcd#10510] opened 2019-03-01 03:41 UTC
```
$ ETCDCTL_API=3 etcdctl get /registry/deployments/kube-system/tiller-deploy --prefix 
2019-03-01 11:37:42.600462 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
/registry/deployments/kube-system/tiller-deploy
k8s

apps/v1
Deployment�
�
tiller-deploy
               kube-system"*$66fe12cc-357e-11e9-aa9e-1866dab41e2c28����Z

apphelmZ
nametillerb&
!deployment.kubernetes.io/revision1z�


apphelm

nametiller�
/
"*28BZ

apphelmZ
nametillerz��
tiller:v2.9.1*2
tiller��"TCP*2
http��"TCP*:
TILLER_NAMESPACE
                  kube-system:
TILLER_HISTORY_MAX0BR+

	/livenes��"HTTP 
(0Z,
 

/readines��"HTTP 
(0j/dev/termination-logr
                           IfNotPresent����FileAlways 2
                                                               ClusterFirst:"
node-role.kubernetes.io/masterBtillerJtillerRX`hr���default-scheduler�0
node-role.kubernetes.io/master"
NoSchedule�"!
RollingUpdate
(0
8H�� (2e
	AvailableTrue"MinimumReplicasAvailable*$Deployment has minimum availability��������2�

ProgressingTrue"NewReplicaSetAvailable*BReplicaSet "tiller-deploy-84d6787987" has successfully progressed��������8"
```

And with json fomat, the content is different:
```
$ ETCDCTL_API=3 etcdctl  get /registry/deployments/kube-system/tiller-deploy --prefix -w json
2019-03-01 11:40:37.905965 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
{"header":{"cluster_id":14841639068965178418,"member_id":10276657743932975437,"revision":1061051,"raft_term":4},"kvs":[{"key":"L3JlZ2lzdHJ5L2RlcGxveW1lbnRzL2t1YmUtc3lzdGVtL3RpbGxlci1kZXBsb3k=","create_revision":795,"mod_revision":22029,"version":7,"value":"azhzAAoVCgdhcHBzL3YxEgpEZXBsb3ltZW50EtoHCpsBCg10aWxsZXItZGVwbG95EgAaC2t1YmUtc3lzdGVtIgAqJDY2ZmUxMmNjLTM1N2UtMTFlOS1hYTllLTE4NjZkYWI0MWUyYzIAOAFCCAj+krjjBRAAWgsKA2FwcBIEaGVsbVoOCgRuYW1lEgZ0aWxsZXJiJgohZGVwbG95bWVudC5rdWJlcm5ldGVzLmlvL3JldmlzaW9uEgExegASvQQIARIdCgsKA2FwcBIEaGVsbQoOCgRuYW1lEgZ0aWxsZXIa7QMKLwoAEgAaACIAKgAyADgAQgBaCwoDYXBwEgRoZWxtWg4KBG5hbWUSBnRpbGxlcnoAErkDEpACCgZ0aWxsZXISDXRpbGxlcjp2Mi45LjEqADIVCgZ0aWxsZXIQABjm2AIiA1RDUCoAMhMKBGh0dHAQABjn2AIiA1RDUCoAOh8KEFRJTExFUl9OQU1FU1BBQ0USC2t1YmUtc3lzdGVtOhcKElRJTExFUl9ISVNUT1JZX01BWBIBMEIAUisKHxIdCgkvbGl2ZW5lc3MSCAgAEOfYAhoAGgAiBEhUVFAQARgBIAooATADWiwKIBIeCgovcmVhZGluZXNzEggIABDn2AIaABoAIgRIVFRQEAEYASAKKAEwA2oUL2Rldi90ZXJtaW5hdGlvbi1sb2dyDElmTm90UHJlc2VudIABAIgBAJABAKIBBEZpbGUaBkFsd2F5cyAeMgxDbHVzdGVyRmlyc3Q6Igoebm9kZS1yb2xlLmt1YmVybmV0ZXMuaW8vbWFzdGVyEgBCBnRpbGxlckoGdGlsbGVyUgBYAGAAaAByAIIBAIoBAJoBEWRlZmF1bHQtc2NoZWR1bGVysgEwCh5ub2RlLXJvbGUua3ViZXJuZXRlcy5pby9tYXN0ZXISABoAIgpOb1NjaGVkdWxlwgEAIiEKDVJvbGxpbmdVcGRhdGUSEAoGCAAQARoAEgYIABABGgAoADAKOABI2AQa+QEIARABGAEgASgAMmUKCUF2YWlsYWJsZRIEVHJ1ZSIYTWluaW11bVJlcGxpY2FzQXZhaWxhYmxlKiREZXBsb3ltZW50IGhhcyBtaW5pbXVtIGF2YWlsYWJpbGl0eS4yCAj+krjjBRAAOggI/pK44wUQADKDAQoLUHJvZ3Jlc3NpbmcSBFRydWUiFk5ld1JlcGxpY2FTZXRBdmFpbGFibGUqQlJlcGxpY2FTZXQgInRpbGxlci1kZXBsb3ktODRkNjc4Nzk4NyIgaGFzIHN1Y2Nlc3NmdWxseSBwcm9ncmVzc2VkLjIICImTuOMFEAA6CAj+krjjBRAAOAEaACIA"}],"count":1}

```

etcd version:
```
[root@skyaxe-app-0 ~]# ETCDCTL_API=3 etcdctl version
etcdctl version: 3.1.14
API version: 3.1

```

How get result without garbled character?

**Comment by hexfusion** [comment] 2019-03-01 03:44
First hit on google search

https://github.com/etcd-io/etcd/issues/7647


-- 
—

**Comment by daixiang0** [comment] 2019-03-01 04:04
@hexfusion it is not TLS issue. It has get expected key.

**Comment by hexfusion** [comment] 2019-03-01 13:11
@daixiang0 sorry misread. This is a duplicate of https://github.com/etcd-io/etcd/issues/7774 basically k8s stores the data in binary format `protobuf`. The referenced k8s issue points to a tool [1] which you could try.

[1] https://github.com/openshift/origin/tree/master/tools/etcdhelper

> And, why different format return different content, they should be same, right?

The JSON output shows the value which is base64 encoded. You will see the same output if you were to decode the value.
```
echo "azhzAAoVCgdhcHBzL3YxEgpEZXBsb3ltZW50EtoHCpsBCg10aWxsZXItZGVwbG95EgAaC2t1YmUtc3lzdGVtIgAqJDY2ZmUxMmNjLTM1N2UtMTFlOS1hYTllLTE4NjZkYWI0MWUyYzIAOAFCCAj+krjjBRAAWgsKA2FwcBIEaGVsbVoOCgRuYW1lEgZ0aWxsZXJiJgohZGVwbG95bWVudC5rdWJlcm5ldGVzLmlvL3JldmlzaW9uEgExegASvQQIARIdCgsKA2FwcBIEaGVsbQoOCgRuYW1lEgZ0aWxsZXIa7QMKLwoAEgAaACIAKgAyADgAQgBaCwoDYXBwEgRoZWxtWg4KBG5hbWUSBnRpbGxlcnoAErkDEpACCgZ0aWxsZXISDXRpbGxlcjp2Mi45LjEqADIVCgZ0aWxsZXIQABjm2AIiA1RDUCoAMhMKBGh0dHAQABjn2AIiA1RDUCoAOh8KEFRJTExFUl9OQU1FU1BBQ0USC2t1YmUtc3lzdGVtOhcKElRJTExFUl9ISVNUT1JZX01BWBIBMEIAUisKHxIdCgkvbGl2ZW5lc3MSCAgAEOfYAhoAGgAiBEhUVFAQARgBIAooATADWiwKIBIeCgovcmVhZGluZXNzEggIABDn2AIaABoAIgRIVFRQEAEYASAKKAEwA2oUL2Rldi90ZXJtaW5hdGlvbi1sb2dyDElmTm90UHJlc2VudIABAIgBAJABAKIBBEZpbGUaBkFsd2F5cyAeMgxDbHVzdGVyRmlyc3Q6Igoebm9kZS1yb2xlLmt1YmVybmV0ZXMuaW8vbWFzdGVyEgBCBnRpbGxlckoGdGlsbGVyUgBYAGAAaAByAIIBAIoBAJoBEWRlZmF1bHQtc2NoZWR1bGVysgEwCh5ub2RlLXJvbGUua3ViZXJuZXRlcy5pby9tYXN0ZXISABoAIgpOb1NjaGVkdWxlwgEAIiEKDVJvbGxpbmdVcGRhdGUSEAoGCAAQARoAEgYIABABGgAoADAKOABI2AQa+QEIARABGAEgASgAMmUKCUF2YWlsYWJsZRIEVHJ1ZSIYTWluaW11bVJlcGxpY2FzQXZhaWxhYmxlKiREZXBsb3ltZW50IGhhcyBtaW5pbXVtIGF2YWlsYWJpbGl0eS4yCAj+krjjBRAAOggI/pK44wUQADKDAQoLUHJvZ3Jlc3NpbmcSBFRydWUiFk5ld1JlcGxpY2FTZXRBdmFpbGFibGUqQlJlcGxpY2FTZXQgInRpbGxlci1kZXBsb3ktODRkNjc4Nzk4NyIgaGFzIHN1Y2Nlc3NmdWxseSBwcm9ncmVzc2VkLjIICImTuOMFEAA6CAj+krjjBRAAOAEaACIA" | base64 -d
```

Feel free to read more on the output formats here. [etcdctl/README.md#output-formats](https://github.com/etcd-io/etcd/blob/3e0f0ba40ecb009cd6edccd4053ae6b1acc6b4c7/etcdctl/README.md#output-formats)

**Closed** 2019-03-01 13:33 UTC

**Comment by daixiang0** [comment] 2019-03-04 07:38
@hexfusion thanks very much!

**Comment by weisongf** [comment] 2019-10-02 08:09
I also encountered garbled problems.
```
root@master2:/var/log# ETCDCTL_API=3 etcdctl version
etcdctl version: 3.2.26
API version: 3.2

```
```
PATH>/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/: 
DEPENDENCY_SERVICE: 
DEPENDENCY_DAEMONSET: 
DEPENDENCY_CONTAINER: 
DEPENDENCY_POD_JSON: 
DEPENDENCY_CUSTOM_RESOURCE: 
COMMAND	echo doneBJR
ariadb-mariadb-token-h8rzl-/var/run/secrets/kubernetes.io/serviceaccount"2j/dev/termination-logr
                                                                                                IfNotPresentz þÿ08JDefault¢File¢؂ 
mariadb-permsKregistry.icp.com:5000/library/os/openstackhelm/mariadb:latest-ubuntu_bionicchown-R 
                                                                                                mysql:mysql/var/lib/mysql*BJ 
pod-tmp/tmp"2J"

mysql-data/var/lib/mysql"2JR
ariadb-mariadb-token-h8rzl-/var/run/secrets/kubernetes.io/serviceaccount"2j/dev/termination-logr
 0JDefault¢File²6                                                                               IfNotPresentz
node.kubernetes.io/not-readyExists"	NoExecute(¬²8
node.kubernetes.io/unreachableExists"	NoExecute(¬Ɓց񾿚 

Running#

InitializedTru¬©¡ꎪ2 
ReadyTru¬¡ꎪ2'
ContainersReadyTru¬¡ꎪ2$

PodScheduledTru´¡ꎪ2"*
172.31.162.7ª¡ꏂ·     172.16.2.1112
mariadb 
        
                                                                                                                                                                                             ®©¡ꎚoÿError³¡䨡ꎺIdocker://fb6745bc09604c2ae8e85e774e5fafd98c8e36ebe05577a2b0411c4510fb1dbd 
```

**Comment by jingyih** [comment] 2019-10-02 20:53
The issue was already addressed by https://github.com/etcd-io/etcd/issues/10510#issuecomment-468659901. PTAL.
