### ISSUE TITLE
etcdctl false-negative "unhealthy cluster" when unauthenticated

### ISSUE THREAD

**Issue by udf2457** [etcd-io/etcd#13692] opened 2022-02-12 11:09 UTC
### What happened?

`etcdctl --write-out=table --endpoints=https://foo.example.com:2379 endpoint health` gives a false-negative cluster health indication:

> +------------------------------+--------+-------------+--------------------------------+
> |           ENDPOINT           | HEALTH |    TOOK     |             ERROR              |
> +------------------------------+--------+-------------+--------------------------------+
> | https://etc2.example.com:2379 |  false | 47.552071ms | etcdserver: user name is empty |
> | https://etc1.example.com:2379 |  false | 48.137024ms | etcdserver: user name is empty |
> | https://etc3.example.com:2379 |  false | 48.444852ms | etcdserver: user name is empty |
> +------------------------------+--------+-------------+--------------------------------+
> Error: unhealthy cluster

This is unhelpful and misleading.  If `ectdctl` was unable to determine the health of a cluster due to failed or missing authentication, it should not fallback to delivering an "unhealthy cluster" (or "false" in the  node health).

### What did you expect to happen?

Not report "false" on individual node health.
Not conclude "Error: unhealthy cluster"

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.2
Git SHA: 99018a77b
Go Version: go1.16.3
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.2
API version: 3.5
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by spzala** [comment] 2022-04-08 15:37
An endpoint is considered unhealthy when it cannot participate in consensus with the rest of the cluster. Inaccessible endpoints, for whatever reason, is considered unhealthy in general and a related log message is provide per it's documented https://github.com/etcd-io/etcd/tree/main/etcdctl#output-15. 
Another example of unreachable endpoint, 
+-----------------------------+--------+-------------+---------------------------+
|          ENDPOINT           | HEALTH |    TOOK     |           ERROR           |
+-----------------------------+--------+-------------+---------------------------+
| http://foo.example.com:2379 |  false | 5.00937926s | context deadline exceeded |
+-----------------------------+--------+-------------+---------------------------+
Error: unhealthy cluster

The cause of error is provided clearly, whether it's a missing credential, connection etc. Closing this issue as this logging behavior is documented and expected. Please reopen if needed. Thanks! 
cc @serathius @ahrtr @ptabor

**Closed by spzala** 2022-04-08 15:37 UTC
Labels: area/bug

**Comment by ahrtr** [comment] 2022-04-08 21:22
Agreed or at least it's a minor one which doesn't need to be fixed at all.
