### ISSUE TITLE
A reliable way to get latest event soon after it's created

### ISSUE THREAD

**Issue by jsong-oracle** [etcd-io/etcd#14417] opened 2022-09-01 22:22 UTC
### What happened?

I had a 3-node cluster, the node-2 was the leader.
all client requests were sent to node-1 via API.

1. Created a new event and committed it, say, the event number = 10, revision = 12345 -- OK
2. To find the latest event from the store -- it should return above event (number = 10, revision = 12345)
    2.1) send a dummy range request with a zero-byte key to get the latest revision (header.revision), returned 12345
    2.2) use above revision 12345 as maxModRevision to search for the last event

The problem is that, if the step-2 is executed very soon after step-1, we might end up with nothing:

  in 2.1) it could return a revision 12344
  in 2.2) it would return empty with maxModRevision = 12344 (and another criteria)

Is there a better way to get the last event without caching it?
or is there a better way to guarantee step 2.1 will always return the last revision from the store via non-leader node?

### What did you expect to happen?

We can always get the last stored event object from store right after it's created. 

### How can we reproduce it (as minimally and precisely as possible)?

1. put an object
2. search for it right after its cerated 

### Anything else we need to know?

After the failure with maxModRevision = 12344, it kept failing when repeating step 2.2.
However it succeeded when stated over step-2 since it got a newer revision at step 2.1.  

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.4.14
Git SHA: dd22fb7
Go Version: go1.15.10 BoringCrypto
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.4.14
API version: 3.4
```
</details>

### Etcd configuration (command line flags or environment variables)

<details>

etcd --name otec-etcd3-red-1 --data-dir /dir/etcd-db/db  --advertise-client-urls http://otec-etcd3-red-1:2380 --listen-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --max-txn-ops 1000 --auto-compaction-mode periodic --auto-compaction-retention 30m

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
+------------------+---------+------------------+------------------------------+------------------------------+------------+
|        ID        | STATUS  |       NAME       |          PEER ADDRS          |         CLIENT ADDRS         | IS LEARNER |
+------------------+---------+------------------+------------------------------+------------------------------+------------+
| 4d607cd5890ca581 | started | otec-etcd3-red-3 | http://otec-etcd3-red-3:2380 | http://otec-etcd3-red-3:2380 |      false |
| 61240db68312d4d9 | started | otec-etcd3-red-2 | http://otec-etcd3-red-2:2380 | http://otec-etcd3-red-2:2380 |      false |
| f43bd775cdf6808e | started | otec-etcd3-red-1 | http://otec-etcd3-red-1:2380 | http://otec-etcd3-red-1:2380 |      false |
+------------------+---------+------------------+------------------------------+------------------------------+------------+

$ etcdctl --endpoints=<member list> endpoint status -w table
+-----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|    ENDPOINT     |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 240.0.1.23:2379 | f43bd775cdf6808e |  3.4.14 |   31 MB |     false |      false |        28 |    4430084 |            4430084 |        |
| 240.0.2.23:2379 | 61240db68312d4d9 |  3.4.14 |   32 MB |     false |      false |        28 |    4430084 |            4430084 |        |
| 240.0.3.23:2379 | 4d607cd5890ca581 |  3.4.14 |   31 MB |      true |      false |        28 |    4430084 |            4430084 |        |
+-----------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

```

</details>

**Comment by ahrtr** [comment] 2022-09-02 20:32
Is this issue reproducible on `main` or `release-3.5`?

**Comment by jsong-oracle** [comment] 2022-09-02 21:51
We will try it.

**Comment by jsong-oracle** [comment] 2022-09-06 17:53
We tested it on main (version 3.6.0-alpha.0) and 3.5.4 and have seen similar issue only on 3.5.4:

With version 3.5.4, we hit the same issue on node-1 which was the leader at that time:  we committed ab event with revision 765379, a few seconds later:
    2022-09-03_02:33:07.68995  committed
    2022-09-03_02:33:12.05798  latest revision: effective: 765378
again it failed to get the event with revision 765379 when it set MaxModRevision=765379

**Comment by serathius** [comment] 2022-09-07 07:23
@jsong-oracle Can you clarify if the issues exists only when you use MaxModRevision? Have you maybe been able to reproduce it by not setting MaxModRevision, or setting Revision?

Could you maybe provide more details about how to reproduce it? For example, script or code that we can run.

**Comment by ahrtr** [comment] 2022-09-07 08:14
I can't reproduce this issue with program against 3.5.4 below. Note that the clients always connects to a follower in a 3-node cluster, and can always get the latest revision immediately after putting a k/v. Please show me your code and the detailed steps on how to reproduce this issue. 

```
package main

import (
	"context"
	"fmt"
	"time"

	clientv3 "go.etcd.io/etcd/client/v3"
)

func main() {
	//etcdHosts := []string{"127.0.0.1:2379", "127.0.0.1:22379", "127.0.0.1:32379"}
	etcdHosts := []string{"127.0.0.1:2379"}
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   etcdHosts,
		DialTimeout: 5 * time.Second,
		AutoSyncInterval: 5*time.Second,
	})
	if err != nil {
		panic (err)
	}
	defer cli.Close()

	resp, err := cli.Get(context.TODO(), "dummy")
	if err != nil {
		panic(err)
	}
	initRev := resp.Header.Revision
	fmt.Printf("Initial revision = %d\n", initRev)

	for i:=0; i<1000; i++ {
		fmt.Printf("#%d\n", i)
		_, err = cli.Put(context.TODO(), fmt.Sprintf("key_%d", i), fmt.Sprintf("val_%d", i))
		if err != nil {
			panic(err)
		}

		resp, err := cli.Get(context.TODO(), "dummy")
		if err != nil {
			panic(err)
		}

		fmt.Printf("    resp.Header.Revision = %d\n", resp.Header.Revision)

		if resp.Header.Revision != int64(i)+initRev+1 {
			fmt.Printf("    Founc mismatch, i = %d, resp.Header.Revision = %d", i, resp.Header.Revision)
		}
	}
}


```

**Comment by serathius** [comment] 2022-09-07 12:58
ok, I think I understand the issue. This is not correct way to use `maxModRevision`, please use `Revision` instead.
maxModRevision is used to filter out key value pairs based on their modRevision, if the key was modified after it will not be returned at all. So in your case, if hey was modified between 2.1 and 2.2 step by other client, it will not be returned. 

> We can always get the last stored event object from store right after it's created.

This question is not correctly stated as you don't have guarantee that object will not be imminently overridden. If you want to double check if your write succeeded then you can use `Revision`, in which case etcd will return you state of the object at this revision and ignore writes that happen later.

**Comment by serathius** [comment] 2022-09-07 12:58
Closing as this is intended behavior

**Closed by serathius** 2022-09-07 12:58 UTC
Labels: area/bug

**Comment by jsong-oracle** [comment] 2022-09-07 14:18
> ok, I think I understand the issue. This is not correct way to use `maxModRevision`, please use `Revision` instead. maxModRevision is used to filter out key value pairs based on their modRevision, if the key was modified after it will not be returned at all. So in your case, if hey was modified between 2.1 and 2.2 step by other client, it will not be returned.
> 
> > We can always get the last stored event object from store right after it's created.
> 
> This question is not correctly stated as you don't have guarantee that object will not be imminently overridden. If you want to double check if your write succeeded then you can use `Revision`, in which case etcd will return you state of the object at this revision and ignore writes that happen later.

Agreed. There is a problem to use MaxModReivision here. I don't think the it's needed in step 2.2. In fact, I tested with MaxModReivision = 0. it was able to get the last event since no filter was applied.

However, in step 2.1, it failed to get the latest revision, is it still an issue or somewhat performance related?

In the real code, there were two range requests in step 2.2: the first one was to get the latest index (with the same MaxModRevision), it didn't fail and the response header had the latest revision as well. When the 2nd range request failed to get the event table, I cannot see how it was modified during the time period. But it might be the case since there was a filter for MaxModRevision and step 2.1 didn't get the last one.  

On the other hand, if step 2.1 got an older revision - 12344, would step 2.2 also fail if I changed "MaxModRevison" to "Revision"  and a revision filter was applied sine the event had a revision 12345? (lol, I didn't see revision filter in the server code)

**Comment by serathius** [comment] 2022-09-07 14:24
> Agreed. There is a problem to use MaxModReivision here. I don't think the it's needed in step 2.2. In fact, I tested with MaxModReivision = 0. it was able to get the last event since no filter was applied.

`MaxModReivision = 0` is equivalent to request without option.
Please stop using MaxModReivision

**Comment by ahrtr** [comment] 2022-09-08 01:53
> On the other hand, if step 2.1 got an older revision - 12344, would step 2.2 also fail if I changed "MaxModRevison" to "Revision" and a revision filter was applied sine the event had a revision 12345?

Agreed. Note that `Revision` vs `MaxModRevison` isn't the point. 



> It seems to happen only in a stress condition. I don't think it's easy to reproduce and am not sure if it can be seen with above code by @ahrtr. In fact, we also thought about to see if we can simplify the steps to reproduce the issue.

It would be helpful if you can reproduce this issue with simplified code & steps.
