### ISSUE TITLE
TXN order of requests inside SUCCESS part matters => BUG

### ISSUE THREAD

**Issue by socketpair** [etcd-io/etcd#14490] opened 2022-09-19 18:10 UTC
### What happened?

etcd answers with unexpected ResponseHeader revision values inside TXN response for DeleteRange part

### What did you expect to happen?

I expect all revisions in all three places equal (see attached JSON in reproduction section):

If it is expected behavior, PLEASE describe (document) what all the places mean. https://etcd.io/docs/v3.3/learning/api/ does not say anything about meaning of these parts in TXN context.

### How can we reproduce it (as minimally and precisely as possible)?

.sh script:

```sh
set -e -u -x

etcdctl del --prefix /xxx/
etcdctl -w json txn <<<'
del --prefix /xxx/r/
put /xxx/a b

' | jq
```

gives (useless fields removed):

```json
{
  "header": {
    "revision":7,
  },
  "responses": [
    {
      "Response": {
        "response_delete_range": {
          "header": {
            "revision": 6
          }
        }
      }
    },
    {
      "Response": {
        "response_put": {
          "header": {
            "revision": 7
          }
        }
      }
    }
  ]
}
```

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.0
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.17
Go OS/Arch: linux/amd64


$ etcdctl version
etcdctl version: 3.5.0
API version: 3.5

```
</details>

**Comment by socketpair** [comment] 2022-09-19 18:13
Especially, I can't understand what  `"revision": 6` means if I never put data at the prefix I delete from.

**Comment by socketpair** [comment] 2022-09-19 18:20
Reordering requests in TXN (i.e. `put`, and then `del`) makes all revision equal. Since order of request in single TXN section was never deocumented as important, I consider it a bug.

**Comment by ahrtr** [comment] 2022-09-21 13:29
Thanks @socketpair raising this discussion. It's expected behavior based on [current implementation](https://github.com/etcd-io/etcd/blob/026794495f66edfc72b4d8c55b6f6b9d23f2064b/server/storage/mvcc/kvstore_txn.go#L161). Both deletion and range operations may have smaller revision based on their position in the list. 

For a TXN, the client application should only check the revision in the top level header instead of each sub response's revision. 

Does this have any impact on your application?

**Comment by socketpair** [comment] 2022-09-21 15:50
Yes, it does. I triggered assertion failure in a library. Please fix documentation about applications, that they should not check corresponding revision in txn responses.

And even better, remove these fields from txn response if no one should consider them.

**Comment by ahrtr** [comment] 2022-09-21 22:37
We have two choice:
1. Keep it as it's, and only update the doc to mention that for responses corresponding to range and deletion operations may have a smaller revision based on their position in the transaction operation list;
2. Fix it to make sure all [responses in a TxnResponse](https://github.com/etcd-io/etcd/blob/026794495f66edfc72b4d8c55b6f6b9d23f2064b/api/etcdserverpb/rpc.pb.go#L1375) have the same revision.  Does this have any impact on Kubernetes. cc @liggitt @dims 

What's your opinion? cc @ptabor @serathius @spzala

**Comment by socketpair** [comment] 2022-09-22 03:51
I would suggest changing protocol of response if it does not affect old versions of libraries

**Comment by liggitt** [comment] 2022-09-22 13:45
> 2\. Fix it to make sure all [responses in a TxnResponse](https://github.com/etcd-io/etcd/blob/026794495f66edfc72b4d8c55b6f6b9d23f2064b/api/etcdserverpb/rpc.pb.go#L1375) have the same revision.  Does this have any impact on Kubernetes. cc @liggitt @dims

if the issue is scoped to DeleteRange requests, then it does not impact Kubernetes (we only delete individual keys)

**Comment by socketpair** [comment] 2022-09-22 18:09
@liggitt no, it actually about any case when there are mix of read-only and read-write queries.

And even then, everything works, problem may raise in theory, at TXN response parsing stage.

**Comment by ahrtr** [comment] 2022-09-23 01:42
> > 2. Fix it to make sure all [responses in a TxnResponse](https://github.com/etcd-io/etcd/blob/026794495f66edfc72b4d8c55b6f6b9d23f2064b/api/etcdserverpb/rpc.pb.go#L1375) have the same revision.  Does this have any impact on Kubernetes. cc @liggitt @dims
> 
> if the issue is scoped to DeleteRange requests, then it does not impact Kubernetes (we only delete individual keys)

Thanks for the feedback. I just searched the K8s repo, and confirmed that the proposed change doesn't impact Kubernetes. The only place that K8s might delete a key inside a TXN is [store.go#L308](https://github.com/kubernetes/kubernetes/blob/91a9ce28ac2486c50222aeeec1f76e664155d769/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L308), but it doesn't use the revision in the response at all.  K8s also uses the range operations inside a TXN in a couple of places, abut they do not use the revision either.  So no any impact on K8s.

**Comment by ahrtr** [comment] 2022-09-25 00:03
> And even better, remove these fields from txn response if no one should consider them.

Agreed. For a TXN, it doesn't make sense for each inner response have a separate [ResponseHeader](https://github.com/etcd-io/etcd/blob/4513671b6902f22a443439d7e2872e42b9629730/api/etcdserverpb/rpc.pb.go#L273). Removing it may have impact on existing applications which depends on etcd.  Deprecating it might be a feasible approach, but I'd like keep it as it is for now, because it seems not like a big deal. 

Correcting the revision in each inner response may have some performance impact on TXN, because we need to iterate all inner responses again. 

Points from my side:
1. Just as I mentioned previously, For a TXN, the client application should only check the revision in the top level header instead of each inner response's header (e.g. revision).
2. The revision in each inner response is just the the latest revision at the moment when the inner operation is performed. 

We can update the [doc](https://etcd.io/docs/v3.5/learning/api/#transaction) if there is no any objections.

**Comment by ahrtr** [comment] 2022-09-26 07:18
FYI. https://github.com/etcd-io/website/pull/615

**Comment by ahrtr** [comment] 2022-09-28 21:04
Resolved in https://github.com/etcd-io/website/pull/615

**Closed by ahrtr** 2022-09-28 21:04 UTC
Labels: area/documentation
