### ISSUE TITLE
fmt Test failures

### ISSUE THREAD

**Issue by srajmane** [etcd-io/etcd#10474] opened 2019-02-14 10:44 UTC
I am working with v 3.3.11 and I am facing same issue as mentioned in 
https://github.com/etcd-io/etcd/issues/10130

https://github.com/etcd-io/etcd/blob/v3.3.11/test#L47

```
 if [ -z "$PASSES" ]; then
-       PASSES="fmt bom dep build unit"
+       PASSES="bom dep build unit"
 fi

 USERPKG=${PKG:-}
```

Can I apply above change to run test using **./test** command ?

OR

Is it okay to run test cases using **make test** command?

**Comment by jingyih** [comment] 2019-02-23 09:53
According to #10130, this is fixed in master branch. Are you using a different branch?

/cc @hexfusion

**Comment by srajmane** [comment] 2019-02-25 06:54
I have tried with etcd v 3.3.11 and 3.3.12 (latest version) . Facing same issue on both version.
Is it okay to run test cases using **make test** command?

**Comment by jingyih** [comment] 2019-02-25 20:46
When you do make test, do you see the same error? I personally have not tried make test, but looks like it is using the same test script:
https://github.com/etcd-io/etcd/blob/2cf9e51d2a78003b164c2998886158e60ded1cbb/Makefile#L144-L148

"fmt" is a test to check language formatting. If your development is stuck on this particular test, please feel free to A) temporarily remove fmt (like you suggested), B) fix the error, it is likely caused by a 'tab' or extra 'space'.

**Comment by srajmane** [comment] 2019-02-26 05:07
Okay I will temporarily remove fmt.

1.  I have tried **make test**, it is running only **unit test** as mentioned in makefile, so it is not giving any error.

2. fix the error, it is likely caused by a 'tab' or extra 'space'. --After removing tab,  it gives another error  as mentioned in 
https://github.com/etcd-io/etcd/issues/10130
`
'govet' started at Tue Oct 23 13:36:58 UTC 2018
#github.com/coreos/etcd/auth
gopath/src/github.com/coreos/etcd/auth/store_test.go:675: github.com/coreos/etcd/etcdserver/etcdserverpb.AuthUserAddRequest composite literal uses unkeyed fields
gopath/src/github.com/coreos/etcd/auth/store_test.go:682: github.com/coreos/etcd/etcdserver/etcdserverpb.AuthRoleAddRequest composite literal uses unkeyed fields
gopath/src/github.com/coreos/etcd/auth/store_test.go:687: github.com/coreos/etcd/etcdserver/etcdserverpb.AuthUserGrantRoleRequest composite literal uses unkeyed fields
gopath/src/github.com/coreos/etcd/auth/store_test.go:693: github.com/coreos/etcd/etcdserver/etcdserverpb.AuthUserGetRequest composite literal uses unkeyed fields
`

Thank you.

**Comment by jingyih** [comment] 2019-02-27 00:26
If you want to run unit test only, you can either:
```
TEST_OPTS="PASSES='unit'" make test
```
or
```
PASSES=unit ./test
```

By the way, I just ran 'fmt' test in master branch. It did not report any error.

**Closed** 2019-03-11 20:59 UTC
