### ISSUE TITLE
How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### ISSUE THREAD

**Issue by luomengY** [etcd-io/etcd#14467] opened 2022-09-14 13:39 UTC
### What happened?

How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### What did you expect to happen?

How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### How can we reproduce it (as minimally and precisely as possible)?

How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### Etcd version (please run commands below)

How does etcd query the value of configuration parameters? For example, how to query the "auto-compaction-retention" value of the currently running etcd.

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by serathius** [comment] 2022-09-14 18:52
Duplicate of https://github.com/etcd-io/etcd/discussions/14466

**Closed by serathius** 2022-09-14 18:52 UTC
Labels: type/bug
