### ISSUE TITLE
ETCD data gets corrupted with error "walpb: crc mismatch"

### ISSUE THREAD

**Issue by neeral** [etcd-io/etcd#11488] opened 2019-12-31 12:25 UTC
I am using etcd as a library embedded inside an application. Etcd version is 3.3.0+git, commit hash https://github.com/etcd-io/etcd/commit/688043a7c2ac8bbb0e73ca5694c7815275865e24

One node had a hard reboot. Node is running on bare metal, ubuntu 16.04. Data directory resides in an lvm partition. After the reboot, etcd was unable to read the WAL due to crc mismatch.
```
walpb: crc mismatch, can only repair unexpected EOF
```
I recovered the system by deleting the etcd data directory and then adding that node back to the cluster.

I ran the last WAL (I took a backup of them before deleting the data directory) through `od` and it showed many of the final entries were zeroes.

```
10723340    133327  121271  135321  014001  172233  001701  000000  000000
10723360    000074  000000  000000  102000  001010  165420  120712  004320
10723400    031032  000010  016020  116030  140764  021003  005047  004045
10723420    170640  001701  145020  111361  102751  143267  012762  012032
10723440    006012  033461  027062  033461  034056  030456  030470  002022
10723460    033465  033466  000000  000000  000034  000000  000000  102000
10723500    001410  104020  123737  000607  011032  016010  111020  120227
10723520    133327  121271  135321  014001  172234  001701  000000  000000
10723540    000074  000000  000000  102000  001010  146020  115201  000642
10723560    031032  000010  016020  116430  140764  021003  005047  004045
10723600    170641  001701  143420  151755  110377  143267  012762  012032
10723620    006012  033461  027062  033461  034056  030456  030470  002022
10723640    137772  100214  037074  170402  130176  142213  127736  123207
10723660    000000  000000  000000  000000  000000  000000  000000  000000
*
10724660    057102  166146  102253  050031  020072  144406  074531  074507
10724700    000000  000000  000000  000000  000000  000000  000000  000000
*
10725340    153571  005036  114556  052056  050256  175374  175204  151005
10725360    000000  000000  000000  000000  000000  000000  000000  000000
*
10725500    176247  033026  041237  064305  046201  121331  067444  034460
10725520    064223  151130  105463  024524  064667  007763  067143  103704
10725540    000000  000000  000000  000000  000000  000000  000000  000000
*
10725740    045370  133761  037715  076165  170713  161150  117457  136003
10725760    000000  000000  000000  000000  000000  000000  000000  000000
10726000    103342  102312  071003  142726  022222  004200  043423  066130
10726020    000000  000000  000000  000000  000000  000000  000000  000000
*
10726460    145412  124564  066427  145377  124760  041530  165533  045160
10726500    163620  144250  063543  131115  115335  017360  010724  125127
10726520    000000  000000  000000  000000  000000  000000  000000  000000
*
10726600    064557  115341  142701  024517  020023  066001  014522  072215
10726620    000000  000000  000000  000000  000000  000000  000000  000000
*
10727200    173632  011424  005476  063773  106006  013516  010274  036144
10727220    000000  000000  000000  000000  000000  000000  000000  000000
*
10727460    154672  175701  074502  013432  102267  100472  016250  016621
10727500    000000  000000  000000  000000  000000  000000  000000  000000
*
10727720    020647  170000  066064  063222  062430  032032  164377  146417
10727740    000000  000000  000000  000000  000000  000000  000000  000000
*
75022000
```

I've attached the data directory here [data-dir.zip](https://github.com/etcd-io/etcd/files/4012654/data-dir.zip). 

I found #6191 that looked similar to this but is very old and that specific problem (reading length of entry from WAL) had been fixed in v3.0.

Questions:
1. What does the output of `od` indicate?
2. Is the issue known, has it already been fixed? I looked through changelogs for releases 3.4, 3.5 but couldn't find anything similar.
3. Is it possible that some writes are not being flushed by etcd to the kernel?

**Comment by xiang90** [comment] 2020-01-01 17:02
can you reliably reproduce this problem?

**Comment by neeral** [comment] 2020-01-02 10:10
Unfortunately no, we're unable to reproduce. There must have been many hard reboots of our nodes over the past year but this has only occurred once.

**Comment by xiang90** [comment] 2020-01-02 15:30
then probably the data is indeed corrupted since the disk might fail to flush all data from buffer to permanent storage.

**Comment by xiang90** [comment] 2020-01-02 15:30
closing since there is no way to reproduce :(

**Closed by xiang90** 2020-01-02 15:30 UTC

**Comment by neeral** [comment] 2020-01-08 19:02
Upon further investigation, discovered this was due to bad disk causing EXT4 to panic and fail, losing writes.

**Comment by xiang90** [comment] 2020-01-09 00:36
@neeral thanks for the update.

**Comment by lojies** [comment] 2020-12-24 03:12
> Upon further investigation, discovered this was due to a bad disk causing EXT4 to panic and fail, losing writes.

I met the same problem. How to find out that this was caused by disk？

**Comment by neeral** [comment] 2020-12-24 11:51
@lojies, I can't remember the details as it was some time ago. There were probably log messages in `kern.log` and `syslog` indicating something was fishy together with additional evidence from other components on that node.

**Comment by lojies** [comment] 2020-12-24 11:58
@neeral , thanks for the reply, i will check these log files.
