### ISSUE TITLE
`MemberList` doesn't work after adding a new member to one-node cluster

### ISSUE THREAD

**Issue by justinsb** [etcd-io/etcd#15243] opened 2023-02-04 17:11 UTC
### What happened?

etcdadm automates bringing up a cluster, and has a test where it brings up a cluster node-by-node.  That test regressed when we updated the client from 3.4 to 3.5, seemingly a reintroduction of #9949

### What did you expect to happen?

No regression

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/kubernetes-sigs/etcdadm/pull/364 demonstrates the problem.

The failing test is relatively simple: https://github.com/kubernetes-sigs/etcdadm/blob/master/test/e2e/cluster_phases.sh

A failing run can be seen [here](https://github.com/kubernetes-sigs/etcdadm/actions/runs/4092492086/jobs/7057270193)

```
+ docker exec etcdadm-1 /etcdadm/etcdadm join phase membership https://172.17.0.2:2379/ --name etcdadm-1
time="2023-02-04T16:42:58Z" level=info msg="[membership] Checking if this member was added"
time="2023-02-04T16:42:58Z" level=info msg="[membership] Member was not added"
time="2023-02-04T16:42:58Z" level=info msg="Removing existing data dir \"/var/lib/etcd\""
time="2023-02-04T16:42:58Z" level=info msg="[membership] Adding member"
time="2023-02-04T16:42:58Z" level=info msg="[membership] Checking if member was started"
time="2023-02-04T16:42:58Z" level=info msg="[membership] Member was not started"
time="2023-02-04T16:42:58Z" level=info msg="[membership] Removing existing data dir \"/var/lib/etcd\""
+ docker exec etcdadm-1 /etcdadm/etcdadm join phase install https://172.17.0.2:2379/ --name etcdadm-1
2023/02/04 16:42:58 [install] Artifact not found in cache. Trying to fetch from upstream: https://github.com/coreos/etcd/releases/download
time="2023-02-04T16:42:58Z" level=info msg="[install] Downloading & installing etcd https://github.com/coreos/etcd/releases/download from 3.5.7 to /var/cache/etcdadm/etcd/v3.5.7\n"
time="2023-02-04T16:42:58Z" level=info msg="[install] downloading etcd from https://github.com/coreos/etcd/releases/download/v3.5.7/etcd-v3.5.7-linux-amd64.tar.gz to /var/cache/etcdadm/etcd/v3.5.7/etcd-v3.5.7-linux-amd64.tar.gz\n"
...
######################################################################## 100.0%
time="2023-02-04T16:42:59Z" level=info msg="[install] extracting etcd archive /var/cache/etcdadm/etcd/v3.5.7/etcd-v3.5.7-linux-amd64.tar.gz to /tmp/etcd560302720\n"
time="2023-02-04T16:43:00Z" level=info msg="[install] verifying etcd 3.5.7 is installed in /opt/bin/\n"
+ docker exec etcdadm-1 /etcdadm/etcdadm join phase configure https://172.17.0.2:2379/ --name etcdadm-1
time="2023-02-04T16:43:00Z" level=info msg="[membership] Checking if this member was added"
{"level":"warn","ts":"2023-02-04T16:43:05.267Z","logger":"etcd-client","caller":"v3@v3.5.7/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0004d0c40/172.17.0.2:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
time="2023-02-04T16:43:05Z" level=fatal msg="[membership] error listing members: context deadline exceeded"
```

So we have a single node cluster with etcadm-0.  We add etcdadm-1 to the cluster but do not start it.  On etcdadm-1 we do a MemberList query against etcdadm-0.  That query times out, which looks like a regression on #9949

### Etcd version (please run commands below)

3.5.1

**Comment by justinsb** [comment] 2023-02-04 17:12
#9949 mentions a CI test, but I couldn't see it in the PR.  Is there an etcd test that covers #9949?

**Comment by ahrtr** [comment] 2023-02-04 21:02
Could you double check whether it can be reproduced on 3.5.7, and provide the etcd log and etcd configuration (CLI parameters)? 

Just to double confirm, it's 3 node cluster, correct?

**Comment by ahrtr** [comment] 2023-02-04 21:48
We have [a failover test case](https://github.com/etcd-io/etcd/blob/65aa0fa3050ebc28793cb07a6b9efc8f464c9e1b/tests/integration/v3_failover_test.go#L32), but all members locate on the same host and accordingly have the same hostname "`localhost`", so the test case may not cover this case.

**Comment by justinsb** [comment] 2023-02-05 16:21
Ah, we actually updated to etcd 3.5.7 recently, so it is in fact 3.5.7.  Sorry!  Thanks also for the link to the failover test case, I'll see if I can reproduce there...

In terms of the cluster size: we are growing a cluster from 1 to 3 nodes, one node at a time.  The problem comes when trying to GetMembers, when we have just added a second membership but etcd hasn't started yet on that node.  In other words: we had a happy one-node cluster, then we added a membership but that node is not healthy / not running yet.  (Aside: should that even be allowed - the new cluster didn't have a quorum approve the new configuration?)  At that point GetMembers fails against the first node.

I tried to extract a semi-minimal repro from `test/e2e/cluster_phases.sh` , though it still uses etcdadm.  Running from the main branch (which is still using etcdclient 3.4, but we can reproduce the failure with etcdctl...)

```
git clone https://github.com/kubernetes-sigs/etcdadm
cd etcdadm
make # or make container-build to build in docker
```

Now we can start a single-node cluster, the full test then adds two nodes to form a 3 node cluster:

```
DATA_VOLUME_NAME="etcdadm-volume"
DATA_VOLUME_MOUNT_PATH="/opt/etcd/pki"
IMAGE="kindest/node:v1.26.0"

# Prepare etcdadm CA certificates temporary local volume
docker volume create ${DATA_VOLUME_NAME}

docker run --name etcdadm-0 --detach --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run --volume ${DATA_VOLUME_NAME}:${DATA_VOLUME_MOUNT_PATH} --volume ${PWD}:/etcdadm ${IMAGE}

# Run init
docker exec etcdadm-0 /etcdadm/etcdadm init phase install
docker exec etcdadm-0 /etcdadm/etcdadm init phase certificates
docker exec etcdadm-0 /etcdadm/etcdadm init phase snapshot
docker exec etcdadm-0 /etcdadm/etcdadm init phase configure
docker exec etcdadm-0 /etcdadm/etcdadm init phase start
docker exec etcdadm-0 /etcdadm/etcdadm init phase etcdctl
docker exec etcdadm-0 /etcdadm/etcdadm init phase health
docker exec etcdadm-0 /etcdadm/etcdadm init phase post-init-instructions

# Verify that all endpoints are healthy
docker exec etcdadm-0 /opt/bin/etcdctl.sh endpoint health

# Verify the init container ip address
etcdadm_0_ip=$(docker inspect --format {{.NetworkSettings.Networks.bridge.IPAddress}} etcdadm-0)

# Copy CA certs from etcdadm-0 container to bin directory
docker exec etcdadm-0 cp /etc/etcd/pki/ca.crt ${DATA_VOLUME_MOUNT_PATH}/
docker exec etcdadm-0 cp /etc/etcd/pki/ca.key ${DATA_VOLUME_MOUNT_PATH}/
```

This is a healthy one-node cluster; we can list members at this point, using etcdctl
```
docker exec -it etcdadm-0 /bin/bash -c ". /etc/etcd/etcdctl.env && /opt/bin/etcdctl member list"
```

Now let's add a second node.  The "problem" here is that we add the membership for the second node before we start etcd on that second node, but I believe that's equivalent to an unfortunately-timed crash (?):

```
docker run --name etcdadm-1 --detach --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run --volume ${DATA_VOLUME_NAME}:${DATA_VOLUME_MOUNT_PATH} --volume ${PWD}:/etcdadm ${IMAGE}


echo "Copying CA certs to container etcdadm-1"
# Copy CA certs to container
# Copy CA certs to container
docker exec etcdadm-1 mkdir -p /etc/etcd/
docker exec etcdadm-1 cp -r ${DATA_VOLUME_MOUNT_PATH} /etc/etcd/pki

echo "Joining etcd member etcdadm-1"
#docker exec etcdadm-1 /etcdadm/etcdadm join phase stop https://${etcdadm_0_ip}:2379 --name etcdadm-1
docker exec etcdadm-1 /etcdadm/etcdadm join phase certificates https://${etcdadm_0_ip}:2379 --name etcdadm-1
docker exec etcdadm-1 /etcdadm/etcdadm join phase membership https://${etcdadm_0_ip}:2379 --name etcdadm-1
#    docker exec etcdadm-1 /etcdadm/etcdadm join phase install https://${etcdadm_0_ip}:2379 --name etcdadm-1
#    docker exec etcdadm-1 /etcdadm/etcdadm join phase configure https://${etcdadm_0_ip}:2379 --name etcdadm-1
#    docker exec etcdadm-1 /etcdadm/etcdadm join phase start https://${etcdadm_0_ip}:2379 --name etcdadm-1
#    docker exec etcdadm-1 /etcdadm/etcdadm join phase etcdctl https://${etcdadm_0_ip}:2379 --name etcdadm-1
#    docker exec etcdadm-1 /etcdadm/etcdadm join phase health https://${etcdadm_0_ip}:2379 --name etcdadm-1

```

(I commented out the steps that weren't necessary to show the problem, they show the full flow that works with client 3.4):

Now if we try to list members:

```
> docker exec -it etcdadm-0 /bin/bash -c ". /etc/etcd/etcdctl.env && /opt/bin/etcdctl member list"
{"level":"warn","ts":"2023-02-05T16:01:19.429Z","logger":"etcd-client","caller":"v3@v3.5.7/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000458a80/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded
```

We also can't `get /`, but we can `get /` with --consistency=s

When I try to remove the member, I also get an error:

```
> docker exec -it etcdadm-0 /bin/bash -c ". /etc/etcd/etcdctl.env && /opt/bin/etcdctl member remove f20a12dd0a9b"
{"level":"warn","ts":"2023-02-05T16:15:56.045Z","logger":"etcd-client","caller":"v3@v3.5.7/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000412a80/127.0.0.1:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
Error: etcdserver: re-configuration failed due to not enough started members
```

To cleanup:
```
docker rm -f etcdadm-0
docker rm -f etcdadm-1
docker volume rm ${DATA_VOLUME_NAME}
```

I've attached the etcd logs, and the systemd configuration env vars for etcd (etcdadm runs with env vars, not flags):

[journalctl-etcd.log](https://github.com/etcd-io/etcd/files/10611509/journalctl-etcd.log)

[etcd.env.txt](https://github.com/etcd-io/etcd/files/10611513/etcd.env.txt)

**Comment by justinsb** [comment] 2023-02-05 16:36
So based on the observation that the cluster didn't have quorum (and that "We also can't get /, but we can get / with --consistency=s"), I realized that the MemberList call is probably doing a quorum check.

I can confirm that this hack allows the test to pass (I'm happy to submit a PR if desired, but I'm sure we'd want to discuss what the behaviour should be here, and maybe expose both options).  So I'm assuming that we made the linearizable MemberList in the 3.5 client and that's why the behaviour differs by client version...

```
diff --git a/client/v3/cluster.go b/client/v3/cluster.go
index 92d7cdb56..027d9f4b0 100644
--- a/client/v3/cluster.go
+++ b/client/v3/cluster.go
@@ -124,7 +124,7 @@ func (c *cluster) MemberUpdate(ctx context.Context, id uint64, peerAddrs []strin
 
 func (c *cluster) MemberList(ctx context.Context) (*MemberListResponse, error) {
        // it is safe to retry on list.
-       resp, err := c.remote.MemberList(ctx, &pb.MemberListRequest{Linearizable: true}, c.callOpts...)
+       resp, err := c.remote.MemberList(ctx, &pb.MemberListRequest{Linearizable: false}, c.callOpts...)
        if err == nil {
                return (*MemberListResponse)(resp), nil
        }
```

So probably not a regression of #9949, but rather that the linearizable default has changed in the 3.5 client.

I think a few things we should figure out here:

1) Should the default be true or false on MemberList?
2) Do we want to expose it in the client lib and in etcdctl?
3) Should we allow a second node to be added when it is not running?

Thanks for the great hints BTW @ahrtr !

**Comment by ahrtr** [comment] 2023-02-06 00:05
It's expected behavior.

Points:
1. MemberList operation[ needs quorum being satisfied](https://github.com/etcd-io/etcd/blob/65aa0fa3050ebc28793cb07a6b9efc8f464c9e1b/client/v3/cluster.go#L127) by default. It's exactly the reason why `MemberList` failed when the second new added node wasn't started yet.
2. There is a flag [--strict-reconfig-check](https://github.com/etcd-io/etcd/blob/65aa0fa3050ebc28793cb07a6b9efc8f464c9e1b/server/etcdmain/config.go#L190), it can prevent users from adding member when it isn't safe. But one-node cluster is a special case, otherwise you will never add new member for one-node cluster.  Please read [cluster.go#L585-L602](https://github.com/etcd-io/etcd/blob/65aa0fa3050ebc28793cb07a6b9efc8f464c9e1b/server/etcdserver/api/membership/cluster.go#L585-L602)


Please let me know if you still have any concerns or comments.

**Comment by ahrtr** [comment] 2023-02-06 23:17
I am thinking probably we can update the signature from
```
func (c *cluster) MemberList(ctx context.Context) (*MemberListResponse, error) 
```
to 
```
func (c *cluster) MemberList(ctx context.Context, opts ...OpOption) (*MemberListResponse, error) 
```

Users can use `c.MemberList(ctx, clientv3.WithSerializable)` in this case.

It isn't a breaking change anymore. The only minor concern is that it reuse the same [Op](url) as KV Range operation. 

any comments? @ptabor @serathius @spzala

**Comment by tjungblu** [comment] 2023-02-07 09:52
that would be a pretty awesome addition, we do have a carry patch in our fork for this for a long time that we wanted to get rid of.

https://github.com/openshift/etcd/commit/26d7d842f6fb968e55fa5dbbd21bd6e4ea4ace50

**Comment by ahrtr** [comment] 2023-02-08 06:27
cc @wojtek-t @wojtek-t @liggitt @dims as well.

**Comment by ahrtr** [comment] 2023-02-08 08:23
Resolved in https://github.com/etcd-io/etcd/pull/15261

**Comment by serathius** [comment] 2023-02-08 10:55
Haven't dig into history of why we introduced disabling linearizability on member list, however before we start changing it I would prefer to first address the original issue. The answer is: *growing etcd cluster from 1 to 3 members is not safe without using learners*

Please consider using learners in your tests.

**Comment by ahrtr** [comment] 2023-02-08 21:24
Adding member as learner can resolve this issue, but we shouldn't ignore this issue just because there is another way bypassing the issue.

The Get/Range operation supports serializable operation, I think it makes sense to support serializable operation for `MemberList` as well.

**Comment by serathius** [comment] 2023-02-09 08:08
Fact that MemberList is fragile on 2 node cluster is not the problem. The underlying problem is that users don't have a safe way to scale up their cluster. Serializable memberlist is just a workaround that we should not encourage users to do. 

Original proposal for MemberList to be linearizable is in https://github.com/etcd-io/etcd/pull/11639, sad that it was not really discussed. Looks like leaving a serializable option was considered by @jingyih I think we can consider making it available in client. 

cc @ptabor WDYT?

**Comment by tjungblu** [comment] 2023-02-09 09:08
> Still would be good to hear from @tjungblu if there was any reason for not using Learners. Maybe they are not well documented or are missing something.

We are using learners successfully for adding members for a while now. We're using the serialized member listing to do some pre-flight checks before starting up etcd:

https://github.com/openshift/etcd/blob/openshift-4.13/openshift-tools/pkg/discover-etcd-initial-cluster/initial-cluster.go#L135-L181

I believe this has to do with all the different installation scenarios of OpenShift that we're supporting, plainly installing from another bootstrap etcd node, then we also have single node and so on and so forth.

I don't have the full context since I wasn't part of the team back then, but maybe @deads2k remembers why he introduced it in https://github.com/openshift/etcd/pull/120#issue-1211472561

**Comment by chaochn47** [comment] 2023-02-13 21:59
As a temporary workaround, [peerMembersHandler](https://github.com/etcd-io/etcd/blob/main/server/etcdserver/api/etcdhttp/peer.go#L105-L120) can be used as a somewhat `serialized member list` and used to grow 1 member cluster to 2 members. 

See more in https://github.com/etcd-io/etcd/issues/14174

```
$ curl -sL http://localhost:2380/members

[{"id":10276657743932975437,"peerURLs":["http://localhost:2380"],"name":"default","clientURLs":["http://localhost:2379"]}]
```

**Closed** 2023-02-27 22:26 UTC
Labels: type/bug
