### ISSUE TITLE
Rejected connection in ETCD logs from localhost every 10 seconds

### ISSUE THREAD

**Issue by KashifSaadat** [etcd-io/etcd#9285] opened 2018-02-06 13:45 UTC
Hi,

I've recently been testing out a Kubernetes Cluster deployment with ETCD v3.3.0, and noticed the following messages in the logs:
```
2018-02-06 12:41:06.905234 I | embed: rejected connection from "127.0.0.1:35574" (error "EOF", ServerName "")
2018-02-06 12:41:07.211189 I | embed: rejected connection from "127.0.0.1:35578" (error "EOF", ServerName "")
2018-02-06 12:41:16.905274 I | embed: rejected connection from "127.0.0.1:35602" (error "EOF", ServerName "")
2018-02-06 12:41:17.211320 I | embed: rejected connection from "127.0.0.1:35606" (error "EOF", ServerName "")
```

There are two of these log lines generated every 10 seconds. The cluster itself is operating without any issues, I can create / delete resources and I haven't noticed/experienced any problems so far. Just curious if anyone has an idea what may be making the requests or if it's even anything of concern?

**Additional notes:**
- I haven't managed to recreate the issue with ETCD v3.2.15.
- There are no additional deployments in the cluster, aside from what kops may create on a standard install

**Versions:**
ETCD Version: [v3.3.0](https://github.com/coreos/etcd/releases/tag/v3.3.0)
Kubernetes Version: [v1.8.7](https://github.com/kubernetes/kubernetes/releases/tag/v1.8.7)
Kops Version: [master + PR](https://github.com/kubernetes/kops/pull/4371)
CoreOS Version: [v1632.2.1](https://coreos.com/releases/#1632.2.1)

**Comment by hexfusion** [comment] 2018-02-06 13:50
Hi @KashifSaadat I assume you are using TLS? Can we see your full etcd startup flags?

**Comment by hexfusion** [comment] 2018-02-06 13:51
> I haven't managed to recreate the issue with ETCD v3.2.15.

So are you saying you can recreate the issue with v3.3.0? Can you provide full steps?

**Comment by KashifSaadat** [comment] 2018-02-06 14:25
Hi @hexfusion, apologies forgot to include that info! ETCD is started up with the following env vars (pulled from one of the hosts):
```
ETCD_ADVERTISE_CLIENT_URLS='https://etcd-a2.internal.<KOPS-CLUSTER-NAME>:4001'
ETCD_CERT_FILE='/srv/kubernetes/etcd.pem'
ETCD_DATA_DIR='/var/etcd/data'
ETCD_INITIAL_ADVERTISE_PEER_URLS='https://etcd-a2.internal.<KOPS-CLUSTER-NAME>:2380'
ETCD_INITIAL_CLUSTER='etcd-a1=https://etcd-a1.internal.<KOPS-CLUSTER-NAME>:2380,etcd-a2=https://etcd-a2.internal.<KOPS-CLUSTER-NAME>:2380,etcd-b1=https://etcd-b1.internal.<KOPS-CLUSTER-NAME>:2380,etcd-b2=https://etcd-b2.internal.<KOPS-CLUSTER-NAME>:2380,etcd-c1=https://etcd-c1.internal.<KOPS-CLUSTER-NAME>:2380'
ETCD_INITIAL_CLUSTER_STATE='new'
ETCD_INITIAL_CLUSTER_TOKEN='etcd-cluster-token-etcd'
ETCD_KEY_FILE='/srv/kubernetes/etcd-key.pem'
ETCD_LISTEN_CLIENT_URLS='https://0.0.0.0:4001'
ETCD_LISTEN_PEER_URLS='https://0.0.0.0:2380'
ETCD_NAME='etcd-a2'
ETCD_PEER_CERT_FILE='/srv/kubernetes/etcd.pem'
ETCD_PEER_KEY_FILE='/srv/kubernetes/etcd-key.pem'
ETCD_PEER_TRUSTED_CA_FILE='/srv/kubernetes/ca.crt'
ETCD_TRUSTED_CA_FILE='/srv/kubernetes/ca.crt'
```
I've attached an example Kops ClusterSpec you can use for testing: 
[example-clusterSpec.yaml](https://github.com/coreos/etcd/files/1699328/example-clusterSpec.yaml.txt)

^ Will need some tweaking such as setting the kops state bucket, cluster name, tightening down Kube API & SSH Access, etc.. General guide on this here: https://github.com/kubernetes/kops/blob/master/docs/aws.md#creating-your-first-cluster

As mentioned in the initial post I've built kops from source, to make use of particular contributions. A guide on building kops from source is here: https://github.com/kubernetes/kops/blob/master/docs/development/building.md

In particular, you would need to build new versions of `kops`, `nodeup` & `protokube`. This can be done by running similar to the following:
```bash
go get k8s.io/kops
cd go/src/k8s.io/kops
git remote add appvia git@github.com:appvia/kops.git
git checkout appvia/bootstrapscript-etcdClusterSpec
make upload S3_BUCKET=s3://<KOPS-S3-BUCKET>
```

Then to build a cluster using kops (make sure you use the kops binary that is built in the above steps, located in `go/src/k8s.io/kops/.build/upload/kops/1.8.0/`):
```bash
export NODEUP_URL=https://s3.<REGION>.amazonaws.com/<KOPS-S3-BUCKET>/<PATH-TO-NODEUP>
export PROTOKUBE_IMAGE=https://s3.<REGION>.amazonaws.com/<KOPS-S3-BUCKET>/<PATH-TO-PROTOKUBE>
kops create -f clusterSpec.yaml # based off the attached file with your amendments
kops create secret --name <KOPS-CLUSTER-NAME> sshpublickey admin -i ~/.ssh/id_rsa.pub
kops update cluster <KOPS-CLUSTER-NAME> --yes
```

Once the cluster has started, you'll be able to ssh into one of the master instances using the default user (`core` for the CoreOS AMI I've used in the attached ClusterSpec), and the etcd logs are located at:
- /var/log/etcd.log
- /var/log/etcd-events.log

**Comment by hexfusion** [comment] 2018-02-06 18:04
@KashifSaadat great details thanks for that.

> There are two of these log lines generated every 10 seconds.

I wonder if this is some kind of health check failing to connect? Also can you provide more logging?

**Comment by hexfusion** [comment] 2018-02-06 18:18
Actually, the 10 seconds could be `TLSHandshakeTimeout: 10 * time.Second`. We will want probably logs for all peers. You also should verify your certs. It seems that it perhaps should also include 127.0.0.1 in your SAN?

`openssl x509 -in $cert_name.pem -text -noout`

**Comment by gyuho** [comment] 2018-02-06 18:23
Probably there are other client requests coming with wrong certs, thus being closed.
Still the error message is not descriptive, which seems addressed in https://go-review.googlesource.com/c/go/+/86715/7/src/crypto/tls/tls.go.

**Comment by gyuho** [comment] 2018-02-09 18:11
> I ran curl http://127.0.0.1:8080/healthz on a master node. On both, I get a HTTP 200 OK response and the response content ok is returned. By making this curl request, ETCD v3.3.0 returns the logs:

@xiang90 Does api server probes ping etcd?

**Comment by KashifSaadat** [comment] 2018-02-14 14:40
Been doing a little more debugging, it appears to be this call here:
- https://github.com/kubernetes/kubernetes/blob/v1.8.7/cmd/kube-apiserver/app/server.go#L278
- https://github.com/kubernetes/apiserver/blob/kubernetes-1.8.7/pkg/storage/etcd3/preflight/checks.go#L44

My kops master nodes start kube-apiserver up with the flag `--etcd-servers=https://127.0.0.1:4001`. Trawling through the code, the request ends up as my below example:
```go
import (
	"fmt"
	"net"
	"time"
)

func main() {
	conn, err := net.DialTimeout("tcp", "127.0.0.1:4001", 1*time.Second)
	if err != nil {
		fmt.Printf("failed, %v", err)
	} else {
		defer conn.Close()
		fmt.Printf("successful\n") // I return successfully here, no errors.
	}
}
```

I can execute that to replicate the behaviour and logs in etcd exactly, where the above code gets a successful response however etcd reports the rejected connection.

**Comment by yangunang** [comment] 2018-03-06 02:43
I run etcd 3.3.1  have the same problem on log : etcd: rejected connection from "localIP:54124" (error "EOF", ServerName "")

**Comment by jpiper** [comment] 2018-03-14 15:21
I've noticed that this happens when you hit the "/healthz" endpoint on the kubernetes API Server for some reason. It doesn't seem to be an issue but when you're trying to debug something it wastes a few hours of your time ha

**Comment by JinsYin** [comment] 2018-05-29 05:58
Solved.

 I replaced the **server certificate** with the **peer certificate**. Although it seems unreasonable. 

#9785

**Comment by eugene-chow** [comment] 2018-06-07 03:34
I can confirm that the errors occur on kubernetes v1.10.3 with etcd v3.3.5. The error appears when kubelet calls apiserver's healthz endpoing like what @KashifSaadat said. Manually calling `curl -k https://localhost:6443/healthz` triggers this as well.

Does anyone know why this is happening?

**Comment by hectorj2f** [comment] 2018-06-12 09:58
We see the same log entries here with Kubernetes `1.10.4` and etcd`v3.3.7`.

**Comment by ttyS0** [comment] 2018-06-24 21:54
I'm still seeing this with Kubernetes `1.10.5` and etcd `v3.3.8`.

**Comment by cflee** [comment] 2018-06-26 09:55
See [kubernetes/kubernetes#63316](https://github.com/kubernetes/kubernetes/issues/63316) and [kubernetes/kubernetes#64909](https://github.com/kubernetes/kubernetes/issues/64909).

It looks like the PR [kubernetes/kubernetes#65027](https://github.com/kubernetes/kubernetes/pull/65027) "Use actual etcd client for /healthz/etcd checks" will replace apiserver's TCP dial with an actual etcd client trying to list etcd members, so I guess this will be resolved in Kubernetes v1.12.

**Comment by akutz** [comment] 2018-09-27 16:00
Thank you for this issue. I've been tolling for two days to understand why kubectl exec fails on my 1.10 deployment (works on 11, 12, 13..). Kept seeing the EOF errors regarding health checks. Really bad when an AWS ALB is fronting your cluster, hitting the health checks every few seconds. If this is a false positive, it's a doozy! Put me on a deep-dive this morning that sounds like I can ignore. Back to the other issue :)

**Comment by n0made1** [comment] 2018-10-04 14:10
I also see this with Kubernetes 1.11.1 and etcd 3.3.9. 
Is there any known workaround ?

**Comment by KashifSaadat** [comment] 2018-10-04 15:12
No worries @akutz, glad it helped!

@n0made1 the above Kubernetes PR was released and available in [v1.12.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.12.0) ([changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#other-notable-changes-6)), I've not yet got around to testing it.

**Comment by n0made1** [comment] 2018-10-04 17:38
Thanks but I can't manage to upgrade to 1.12, so I was wondering if there
would any workaround for 1.11.

Le jeu. 4 oct. 2018 à 17:15, Kashif Saadat <notifications@github.com> a
écrit :

**Comment by wenjiaswe** [comment] 2018-10-23 22:13
Just talked to the author @liggitt  of the fix mentioned, as we need to balance between the severity of the issue vs. the risk of back porting, we are not planning to back port it k8s 1.10 and 1.11. If you have a strong use case that really need the back port in k8s, please open an issue in [kubernetes](https://github.com/kubernetes/kubernetes/issues), so we could have more experts evaluating it. Otherwise I am closing this issue since it's not an etcd issue.

**Closed** 2018-10-23 22:13 UTC
Labels: Investigating, Support/Question, TLS
