### ISSUE TITLE
etcd cluster continues to leader election

### ISSUE THREAD

**Issue by DavidLiuXh** [etcd-io/etcd#10902] opened 2019-07-17 07:51 UTC
etcd version:  3.3.9
Git SHA: fca8add78
Go Version: go1.10.3
Go OS/Arch: linux/amd64
etcdserver: heartbeat = 100ms
etcdserver: election = 1000ms
etcdserver: snapshot count = 100000

1. The etcd cluster consists of three nodes A,B,C and A is leader;
2.  Send lots of leasekeeplive and leasegrant request;
3.  The node A  has a large number of logs as follows
`    etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 40.577204ms)` 
    `2019-07-16 21:38:27.513061 W | etcdserver: server is likely overloaded `
4. The etcd cluster continues to leader election;
5. Stop all leasekeeplive and leasegrant requests, but the cluster still contines to leader election:
`2019-07-17 15:42:21.355258 I | raft: f1d74eb7f5870412 became follower at term 21286`
`2019-07-17 15:42:21.355274 I | raft: f1d74eb7f5870412 [logterm: 21285, index: 1821758901, vote: 0] rejected MsgVote from 5cfb6d1a708a462c [logterm: 323, index: 1821741405] at term 21286`
`2019-07-17 15:42:22.478021 I | raft: f1d74eb7f5870412 [logterm: 21285, index: 1821758901, vote: 0] rejected MsgVote from b14a000f2375a85b [logterm: 21278, index: 1821769406] at term 21286`
`2019-07-17 15:42:22.896614 I | raft: f1d74eb7f5870412 is starting a new election at term 21286`
`2019-07-17 15:42:22.896643 I | raft: f1d74eb7f5870412 became candidate at term 21287`
`2019-07-17 15:42:22.896665 I | raft: f1d74eb7f5870412 received MsgVoteResp from f1d74eb7f5870412 at term 21287`
`2019-07-17 15:42:22.896679 I | raft: f1d74eb7f5870412 [logterm: 21285, index: 1821758901] sent MsgVote request to 5cfb6d1a708a462c at term 21287`
`2019-07-17 15:42:22.896691 I | raft: f1d74eb7f5870412 [logterm: 21285, index: 1821758901] sent MsgVote request to b14a000f2375a85b at term 21287`
`2019-07-17 15:42:24.341797 I | raft: f1d74eb7f5870412 received MsgVoteResp from b14a000f2375a85b at term 21287`
`2019-07-17 15:42:24.341828 I | raft: f1d74eb7f5870412 [quorum:2] has received 2 MsgVoteResp votes and 0 vote rejections`
`2019-07-17 15:42:24.342809 I | raft: f1d74eb7f5870412 became leader at term 21287`
`2019-07-17 15:42:24.342832 I | raft: raft.node: f1d74eb7f5870412 elected leader f1d74eb7f5870412 at term 21287`
`2019-07-17 15:42:25.296644 W | raft: f1d74eb7f5870412 stepped down to follower since quorum is not active`
`2019-07-17 15:42:25.296681 I | raft: f1d74eb7f5870412 became follower at term 21287`
`2019-07-17 15:42:25.296694 I | raft: raft.node: f1d74eb7f5870412 lost leader f1d74eb7f5870412 at term 21287`
`2019-07-17 15:42:27.880738 I | raft: f1d74eb7f5870412 [term: 21287] received a MsgVote message with higher term from b14a000f2375a85b [term: 21288]`
`2019-07-17 15:42:27.880807 I | raft: f1d74eb7f5870412 became follower at term 21288`
`2019-07-17 15:42:27.880825 I | raft: f1d74eb7f5870412 [logterm: 21287, index: 1821758903, vote: 0] rejected MsgVote from b14a000f2375a85b [logterm: 21278, index: 1821769406] at term 21288`
`2019-07-17 15:42:28.225985 I | raft: f1d74eb7f5870412 [logterm: 21287, index: 1821758903, vote: 0] rejected MsgVote from 5cfb6d1a708a462c [logterm: 323, index: 1821741405] at term 21288`
`2019-07-17 15:42:29.196632 I | raft: f1d74eb7f5870412 is starting a new election at term 21288`
`2019-07-17 15:42:29.196661 I | raft: f1d74eb7f5870412 became candidate at term 21289`
`2019-07-17 15:42:29.196674 I | raft: f1d74eb7f5870412 received MsgVoteResp from f1d74eb7f5870412 at term 21289`
`2019-07-17 15:42:29.196688 I | raft: f1d74eb7f5870412 [logterm: 21287, index: 1821758903] sent MsgVote request to 5cfb6d1a708a462c at term 21289`
`2019-07-17 15:42:29.196700 I | raft: f1d74eb7f5870412 [logterm: 21287, index: 1821758903] sent MsgVote request to b14a000f2375a85b at term 21289`
`2019-07-17 15:42:29.223031 I | raft: f1d74eb7f5870412 [logterm: 21287, index: 1821758903, vote: f1d74eb7f5870412] rejected MsgVote from 5cfb6d1a708a462c [logterm: 323, index: 1821741405] at term 21289`
`2019-07-17 15:42:30.656353 I | raft: f1d74eb7f5870412 received MsgVoteResp rejection from 5cfb6d1a708a462c at term 21289`
`2019-07-17 15:42:30.656401 I | raft: f1d74eb7f5870412 [quorum:2] has received 1 MsgVoteResp votes and 1 vote rejections`
6. It seems that the follower node cannot send hb to leader:
`f1d74eb7f5870412 stepped down to follower since quorum is not active`

all etcd logs:
  
[log.tar.gz](https://github.com/etcd-io/etcd/files/3400699/log.tar.gz)

**Comment by DavidLiuXh** [comment] 2019-07-17 07:54
I confirm the network is fine

**Comment by DavidLiuXh** [comment] 2019-07-17 09:10
@xiang90 @gyuho Please help me

**Comment by jimwek** [comment] 2019-12-27 01:03
Frequent elections, I have the same problem and am looking for a solution.

**Comment by xiang90** [comment] 2019-12-31 16:21
> 2019-07-16 21:38:27.513061 W | etcdserver: server is likely overloaded

This log line already told you the reason, no?

**Comment by DavidLiuXh** [comment] 2020-01-02 01:50
@xiang90 
Is this server still overloaded when  top all leasekeeplive and leasegrant requests?

**Comment by xiang90** [comment] 2020-01-02 15:32
it depends on your machine configuration, the request rate, etc.. hard to say exactly why. you have to benchmark it yourself on the environment. closing since the problem is identified.

**Closed by xiang90** 2020-01-02 15:32 UTC

**Comment by jimwek** [comment] 2020-01-03 02:15
全是中文名字
