### ISSUE TITLE
error in etcdctl 

### ISSUE THREAD

**Issue by pengmhm** [etcd-io/etcd#15635] opened 2023-04-04 03:40 UTC
### What happened?

when expanding versions above V3.5, it is default to join as a learner, but the status found by etcdctl is follower?

### What did you expect to happen?

continuous expansion cannot confirm consistency status

### How can we reproduce it (as minimally and precisely as possible)?

when the database has a largeamount of data, perform expansion operations, add and start new nodes, and use etcdctl to query status and roles

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
V3.5.5
# paste output here

$ etcdctl version
# paste output here
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

# paste your configuration here

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
# paste output here

$ etcdctl --endpoints=<member list> endpoint status -w table
# paste output here
```

</details>

**Comment by jmhbnz** [comment] 2023-04-22 20:05
Hey @pengmhm - Thanks for reporting this issue, are you able to recreate this with etcd compiled from the `main` aka 3.6 branch?

If you can re-create it there can you please provide the steps you followed so we can reproduce and work out a fix?

**Comment by ahrtr** [comment] 2023-04-22 22:39
> when expanding versions above V3.5, it is default to join as a learner, but the status found by etcdctl is follower?

I couldn't reproduce this issue. Please provide the detailed steps to reproduce this issue.

```
$ etcdctl endpoint status -w table --cluster
+------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|        ENDPOINT        |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://127.0.0.1:42379 | 24a5b0f4c635ed65 |   3.5.8 |   25 kB |     false |       true |         2 |         10 |                 10 |        |
|  http://127.0.0.1:2379 | 8211f1d0f64f3269 |   3.5.8 |   25 kB |     false |      false |         2 |         10 |                 10 |        |
| http://127.0.0.1:22379 | 91bc3c398fb3c146 |   3.5.8 |   25 kB |     false |      false |         2 |         10 |                 10 |        |
| http://127.0.0.1:32379 | fd422379fda50e48 |   3.5.8 |   25 kB |      true |      false |         2 |         10 |                 10 |        |
+------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

**Comment by jmhbnz** [comment] 2023-05-24 09:32
Closing this issue in line with our issue triage policy: https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/triage_issues.md#close-incomplete-issues

@pengmhm If you still encounter issues with this please create a new issue with the detailed steps we can follow to reproduce it.

**Closed by jmhbnz** 2023-05-24 09:32 UTC
Labels: area/etcdctl, type/support
