### ISSUE TITLE
This flag -- client-cert-auth=false has a bug in etcd 

### ISSUE THREAD

**Issue by coderchuan** [etcd-io/etcd#16663] opened 2023-09-29 08:13 UTC
### What happened?

When I use the -- trusted-ca-file option in ETCD, even if I set -- client-cert-auth=false, I still cannot connect to ETCD in ETCDCTL. However, if I specify -- cert and -- key in ETCDCTL, I can connect

### What did you expect to happen?

As a switch, --client-cert-auth should be made functional. When set to false, etcdctl should not specify the -- cert and -- key options. When set to true, etcdctl should specify the -- cert and -- key options

### How can we reproduce it (as minimally and precisely as possible)?
` etcd --name=single --initial-advertise-peer-urls=http://10.21.200.146:1200 --advertise-client-urls=https://10.21.200.146:1300 --initial-cluster=single=http://10.21.200.146:1200 --initial-cluster-state=new --cert-file=/etc/etcd/ssl/server.crt --key-file=/etc/etcd/ssl/server.key --trusted-ca-file=/etc/etcd/ssl/ca.crt --listen-peer-urls=http://0.0.0.0:1200 --listen-client-urls=https://0.0.0.0:1300 --data-dir=/var/etcd/data --quota-backend-bytes=4294967296 --initial-cluster-token=abcdef --log-outputs=stdout,/var/log/etcd/log.txt --client-cert-auth=false`

Note that --client-cert-auth=false is set to false in the above code，the following is an example of an inability to connect

`etcdctl --endpoints='https://10.21.200.146:1300' --cacert=/etc/etcd/ssl/ca.crt  put name config_center`

The following is an example that can be connected

`etcdctl --endpoints='https://10.21.200.146:1300' --cacert=/etc/etcd/ssl/ca.crt  --cert=/etc/etcd/ssl/client.crt --key=/etc/etcd/ssl/client.key put name config_center`

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
etcd Version: 3.5.9
Git SHA: bdbbde998
Go Version: go1.19.9
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.5.9
API version: 3.5
```

</details>

**Comment by jmhbnz** [comment] 2023-09-29 08:18
Duplicate of https://github.com/etcd-io/etcd/issues/11124.  I proposed a code fix in https://github.com/etcd-io/etcd/pull/16585 however the current behavior has been present for a very long time and it was decided a documentation update was the preferred way to handle this.

Documentation is being updated under: https://github.com/etcd-io/website/pull/724

> ### --trusted-ca-file
>  Path to the client server TLS trusted CA cert file.
>  default: ""
>  env variable: ETCD_TRUSTED_CA_FILE

>  Note setting this parameter will also automatically enable client cert authentication no matter what value is set for `--client-cert-auth`.

**Comment by coderchuan** [comment] 2023-09-29 09:58
> Duplicate of #11124.
> 
> I proposed a code fix in #16585 however the current behavior has been present for a very long time and it was decided a documentation update was the preferred way to handle this.
> 
> Documentation is being updated under: [etcd-io/website#724](https://github.com/etcd-io/website/pull/724)
> 
> > --trusted-ca-file ''
> > Path to the client server TLS trusted CA cert file.
> > Note setting this parameter will also automatically enable client cert authentication no matter what value is set for `--client-cert-auth`.

So does it also mean that using the -- peer trusted ca file option will also force the setting of -- peer client ert auth=true ?

**Comment by jmhbnz** [comment] 2023-09-29 10:18
> Thanks . So does it also mean that using the -- peer-trusted-ca-file option will also force the setting of -- peer-client-ert-auth=true ?

I don't believe so though I haven't tested it, below is the current logic and unless I am missing something it only appears to reference server trusted ca?

```go
if info.TrustedCAFile != "" || info.ClientCertAuth {

	cfg.ClientAuth = tls.RequireAndVerifyClientCert
}
```

**Comment by coderchuan** [comment] 2023-09-29 10:31
> > 谢谢。那么这是否也意味着使用 -- peer-trusted-ca-file 选项也将强制设置 -- peer-client-ert-auth=true ？
> 
> 我不这么认为，尽管我没有测试过它，下面是当前的逻辑，除非我缺少某些内容，否则它似乎只引用服务器受信任的ca？
> 
> ```go
> if info.TrustedCAFile != "" || info.ClientCertAuth {
> 
> 	cfg.ClientAuth = tls.RequireAndVerifyClientCert
> }
> ```



> > 谢谢。那么这是否也意味着使用 -- peer-trusted-ca-file 选项也将强制设置 -- peer-client-ert-auth=true ？
> 
> 我不这么认为，尽管我没有测试过它，下面是当前的逻辑，除非我缺少某些内容，否则它似乎只引用服务器受信任的 ca。
> 
> ```go
> if info.TrustedCAFile != "" || info.ClientCertAuth {
> 
> 	cfg.ClientAuth = tls.RequireAndVerifyClientCert
> }
> ```
I think if setting --trusted-ca-file will force --client-cert-auth=true, then --peer-trusted-ca-file and --trusted-ca-file should have the same behavior because -peer - trusted-ca-file and --trusted-ca-file are two options with exactly the same logic. Do you think this is appropriate?

**Comment by jmhbnz** [comment] 2023-10-07 10:54
> I think if setting --trusted-ca-file will force --client-cert-auth=true, then --peer-trusted-ca-file and --trusted-ca-file should have the same behavior because -peer - trusted-ca-file and --trusted-ca-file are two options with exactly the same logic. Do you think this is appropriate?

Hmm, interesting suggestion, after thinking it over I disagree that `--trusted-ca-file` and `--peer-trusted-ca-file` should have the same behaviour in relation to forcing `--client-cert-auth`.

 `--client-cert-auth` and `--trusted-ca-file` are certainly linked as they both relate to client-to-server communication. However `--peer-trusted-ca-file` relates only to peer (server-to-server) communication and has nothing to do with clients.

We can see this separation being called out in the etcd security model here: https://etcd.io/docs/v2.3/security.

---

On a separate note I can see our documentation fix for this issue has been merged in https://github.com/etcd-io/website/pull/724 so I will close this now.

**Closed by jmhbnz** 2023-10-07 10:54 UTC
Labels: type/bug, area/tls
