### ISSUE TITLE
Data inconsistency in etcd version 3.4.16

### ISSUE THREAD

**Issue by rahulbapumore** [etcd-io/etcd#13580] opened 2022-01-05 15:09 UTC
etcdctl get command returns values sometimes and sometimes it does not return a value even if key value is present in etcd.

got the same data inconsistency issue with etcd version 3.4.16(already reported bug can be found here - https://github.com/etcd-io/etcd/issues/13503)

Can anyone help with this issue?

**Comment by rahulbapumore** [comment] 2022-01-06 12:43
Hii,
Any updates?

**Comment by hexfusion** [comment] 2022-01-06 14:06
Please bump the previous issue, I understand your concern but adding additional issues impedes resolution.

Duplicate of: https://github.com/etcd-io/etcd/issues/13503

**Closed by hexfusion** 2022-01-06 14:06 UTC
