### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by jianpingjwang** [etcd-io/etcd#10741] opened 2019-05-20 01:33 UTC
Please read https://github.com/etcd-io/etcd/blob/master/Documentation/reporting_bugs.md.

goroutine 129 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*DB).page(...)
    /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/db.go:859
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).rollback(0xc420b4ddc0)
    /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:267 +0xe9
github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc420b4ddc0, 0x2cdd20bac1e3d, 0x165d340)
    /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/bbolt/tx.go:186 +0x4fe
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTx).commit(0xc4203d5ce0, 0x0)
    /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:167 +0x8f
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.(*batchTxBuffered).unsafeCommit(0xc4203d5ce0, 0xc42023ca00)
    /tmp/etcd-release-3.3.10/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend/batch_tx.go:239 +0x49
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/

**Comment by jianpingjwang** [comment] 2019-05-20 01:34
Can anybody help me?

etcd-release-3.3.10

It seems to be a bug about txn.

**Comment by WIZARD-CXY** [comment] 2019-05-21 03:09
seems the known bug in tx rollback @jianpingjwang

**Comment by jianpingjwang** [comment] 2019-05-21 03:13
> seems the known bug in tx rollback @jianpingjwang

when fixed, pls let me know, thanks

**Comment by jingyih** [comment] 2019-05-21 03:51
Duplicate of #10399.

As @WIZARD-CXY said, it is the known bug when rolling back a writable Tx in bbolt with NoFreelistSync set to true.

Ref: https://github.com/etcd-io/bbolt/issues/152

**Closed by jingyih** 2019-05-21 03:51 UTC
