### ISSUE TITLE
etcd db initializes when new. Subsequent member add is successful but etcdctl calls fail; new member will not start

### ISSUE THREAD

**Issue by pgodfrin-nov** [etcd-io/etcd#13730] opened 2022-02-22 16:18 UTC
### What happened?

Create new cluster, single node:
postgres@devudb01:/postgres/admin/etcd=> ssc start etcd
```
postgres@devudb01:/postgres/admin/etcd=> eee member list
+------------------+---------+---------------+---------------------------+---------------------------+------------+
|        ID        | STATUS  |     NAME      |        PEER ADDRS         |       CLIENT ADDRS        | IS LEARNER |
+------------------+---------+---------------+---------------------------+---------------------------+------------+
| 75e6d59d7b36ac12 | started | etcd-devudb01 | http://172.21.61.224:2380 | http://172.21.61.224:2379 |      false |
+------------------+---------+---------------+---------------------------+---------------------------+------------+
```
Add new member:
```
postgres@devudb01:/postgres/admin/etcd=> eew member add etcd-devewt01 --peer-urls=http://172.21.58.245:2380
Member  a906cab36d19caf added to cluster 3b96513055e383dc

ETCD_NAME="etcd-devewt01"
ETCD_INITIAL_CLUSTER="etcd-devewt01=http://172.21.58.245:2380,etcd-devudb01=http://172.21.61.224:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://172.21.58.245:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"

```
subsequent member list times out:

```
postgres@devudb01:/postgres/admin/etcd=> eee member list
{"level":"warn","ts":"2022-02-22T09:26:20.323-0600","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003b0700/172.21.58.245:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded

```
Curl provides this:

```
postgres@devudb01:/postgres/admin/etcd=> curl -L -s http://172.21.61.224:2379/v3/cluster/member/list -X POST  | jq
{
  "header": {
    "cluster_id": "4293708562785600476",
    "member_id": "8495712619434781714",
    "raft_term": "2"
  },
  "members": [
    {
      "ID": "761227819640528047",
      "peerURLs": [
        "http://172.21.58.245:2380"
      ]
    },
    {
      "ID": "8495712619434781714",
      "name": "etcd-devudb01",
      "peerURLs": [
        "http://172.21.61.224:2380"
      ],
      "clientURLs": [
        "http://172.21.61.224:2379"
      ]
    }
  ]
}
```
new member startup fails:
```
Feb 22 09:45:03 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:03.674Z","caller":"etcdmain/config.go:339","msg":"loaded server configuration, other configuration command line flags and environment variables will be ignored if provided","path":"/postgres/admin/etcd/devewt01-etcd.yaml"}
Feb 22 09:45:03 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:03.675Z","caller":"etcdmain/etcd.go:72","msg":"Running: ","args":["/usr/local/bin/etcd","--config-file","/postgres/admin/etcd/devewt01-etcd.yaml","--auto-tls","--peer-auto-tls"]}
Feb 22 09:45:03 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:03.675Z","caller":"etcdmain/etcd.go:115","msg":"server has been already initialized","data-dir":"/dcs/etcd/data","dir-type":"member"}
Feb 22 09:45:03 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:03.677Z","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["http://172.21.58.245:2380"]}
Feb 22 09:45:03 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:03.678Z","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["http://172.21.58.245:2379"]}
Feb 22 09:45:03 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:03.678Z","caller":"embed/etcd.go:599","msg":"pprof is enabled","path":"/debug/pprof"}
Feb 22 09:45:03 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:03.678Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.2","git-sha":"99018a77b","go-version":"go1.16.3","go-os":"linux","go-arch":"amd64","max-cpu-set":2,"max-cpu-available":2,"member-initialized":false,"name":"etcd-devewt01","data-dir":"/dcs/etcd/data","wal-dir":"/dcs/etcd/wal","wal-dir-dedicated":"/dcs/etcd/wal","member-dir":"/dcs/etcd/data/member","force-new-cluster":false,"heartbeat-interval":"1s","election-timeout":"10s","initial-election-tick-advance":true,"snapshot-count":10000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://172.21.58.245:2380"],"listen-peer-urls":["http://172.21.58.245:2380"],"advertise-client-urls":["http://172.21.58.245:2379"],"listen-client-urls":["http://172.21.58.245:2379"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"etcd-devewt01=http://172.21.58.245:2380,etcd-devudb01=http://172.21.61.224:2380","initial-cluster-state":"existing","initial-cluster-token":"etcd-devewt01","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"periodic","auto-compaction-retention":"1h0m0s","auto-compaction-interval":"1h0m0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
Feb 22 09:45:03 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:03.680Z","caller":"etcdserver/backend.go:81","msg":"opened backend db","path":"/dcs/etcd/data/member/snap/db","took":"1.155792ms"}
Feb 22 09:45:13 ip-172-21-60-149 etcd[98039]: {"level":"warn","ts":"2022-02-22T15:45:13.681Z","caller":"etcdserver/cluster_util.go:79","msg":"failed to get cluster response","address":"http://172.21.61.224:2380/members","error":"Get \"http://172.21.61.224:2380/members\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}
Feb 22 09:45:13 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:13.682Z","caller":"embed/etcd.go:368","msg":"closing etcd server","name":"etcd-devewt01","data-dir":"/dcs/etcd/data","advertise-peer-urls":["http://172.21.58.245:2380"],"advertise-client-urls":["http://172.21.58.245:2379"]}
Feb 22 09:45:13 ip-172-21-60-149 etcd[98039]: {"level":"info","ts":"2022-02-22T15:45:13.682Z","caller":"embed/etcd.go:370","msg":"closed etcd server","name":"etcd-devewt01","data-dir":"/dcs/etcd/data","advertise-peer-urls":["http://172.21.58.245:2380"],"advertise-client-urls":["http://172.21.58.245:2379"]}
Feb 22 09:45:13 ip-172-21-60-149 etcd[98039]: {"level":"fatal","ts":"2022-02-22T15:45:13.682Z","caller":"etcdmain/etcd.go:203","msg":"discovery failed","error":"cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdmain/etcd.go:203\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/tmp/etcd-release-3.5.2/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/usr/local/google/home/siarkowicz/.gvm/gos/go1.16.3/src/runtime/proc.go:225"}
```

### What did you expect to happen?

After adding the remote member, the etcdctl command should work, returning the local member in and the remotes info as 'not started'

### How can we reproduce it (as minimally and precisely as possible)?

unknown

### Etcd version (please run commands below)

<details>

```
postgres@devewt01:/postgres/admin/etcd=> etcd --version
etcd Version: 3.5.2
Git SHA: 99018a77b
Go Version: go1.16.3
Go OS/Arch: linux/amd64
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

name: 'etcd-devewt01'
data-dir: '/dcs/etcd/data'
wal-dir: "/dcs/etcd/wal"
snapshot-count: 10000
heartbeat-interval: 1000
election-timeout: 10000
quota-backend-bytes: 0
listen-peer-urls: http://172.21.58.245:2380
listen-client-urls: http://172.21.58.245:2379
max-snapshots: 1000
max-wals: 1000
cors:
initial-advertise-peer-urls: http://172.21.58.245:2380
advertise-client-urls: http://172.21.58.245:2379
discovery:
discovery-fallback: 'proxy'
discovery-proxy:
discovery-srv:
initial-cluster: 'etcd-devewt01=http://172.21.58.245:2380,etcd-devudb01=http://172.21.61.224:2380'
initial-cluster-token: 'etcd-devewt01'
initial-cluster-state: 'existing'
strict-reconfig-check: false
enable-v2: false
enable-pprof: true
proxy: 'off'
proxy-failure-wait: 5000
proxy-refresh-interval: 30000
proxy-dial-timeout: 1000
proxy-write-timeout: 5000
proxy-read-timeout: 0
client-transport-security:
cert-file:
key-file:
client-cert-auth: false
trusted-ca-file:
auto-tls: false
peer-transport-security:
cert-file:
key-file:
client-cert-auth: false
trusted-ca-file:
auto-tls: false
debug: true 
log-level: debug
logger: zap
log-outputs: [stderr]
force-new-cluster: false
auto-compaction-mode: periodic
auto-compaction-retention: "1"
enable-grpc-gateway: true

</details>

### Etcd debug information (please run commands blow, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
postgres@devudb01:/postgres/admin/etcd=> etcdctl --endpoints=$ENDPOINTS endpoint status -w table
{"level":"warn","ts":"2022-02-22T10:24:27.807-0600","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000354380/172.21.58.245:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Failed to get the status of endpoint 172.21.58.245:2379 (context deadline exceeded)
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+-----------------------+
|      ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX |        ERRORS         |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+-----------------------+
| 172.21.61.224:2379 | 75e6d59d7b36ac12 |   3.5.2 |   20 kB |     false |      false |         2 |          5 |                  5 | etcdserver: no leader |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+-----------------------+
postgres@devudb01:/postgres/admin/etcd=> nslookup devudb01.novcds.io
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   devudb01.novcds.io
Address: 172.21.61.224

```

</details>

**Comment by pgodfrin-nov** [comment] 2022-02-22 17:41
Pilot error. Static IP ports not setup.

**Comment by pgodfrin-nov** [comment] 2022-02-22 17:55
UPDATE:
Something is still not right. When adding the second member and not starting it, member list fails. After starting the remote member, member list works. Adding the thrid member? This is weird:




```
postgres@devudb01:/postgres/admin/etcd=> eee member list
+------------------+---------+---------------+---------------------------+--------------------------------+------------+
|        ID        | STATUS  |     NAME      |        PEER ADDRS         |          CLIENT ADDRS          | IS LEARNER |
+------------------+---------+---------------+---------------------------+--------------------------------+------------+
| 75e6d59d7b36ac12 | started | etcd-devudb01 | http://172.21.61.224:2380 | http://devudb01.novcds.io:2379 |      false |
| d8b9762ebf4430a3 | started | etcd-devewt01 | http://172.21.58.245:2380 | http://devewt01.novcds.io:2379 |      false |
+------------------+---------+---------------+---------------------------+--------------------------------+------------+

```
```
postgres@devudb01:/postgres/admin/etcd=> eew member add etcd-devewt02 --peer-urls=http://172.21.69.253:2380
Member 950443008f8de983 added to cluster 3b96513055e383dc

ETCD_NAME="etcd-devewt02"
ETCD_INITIAL_CLUSTER="etcd-devudb01=http://172.21.61.224:2380,etcd-devewt02=http://172.21.69.253:2380,etcd-devewt01=http://172.21.58.245:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://172.21.69.253:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"
postgres@devudb01:/postgres/admin/etcd=> eee member list
+------------------+-----------+---------------+---------------------------+--------------------------------+------------+
|        ID        |  STATUS   |     NAME      |        PEER ADDRS         |          CLIENT ADDRS          | IS LEARNER |
+------------------+-----------+---------------+---------------------------+--------------------------------+------------+
| 75e6d59d7b36ac12 |   started | etcd-devudb01 | http://172.21.61.224:2380 | http://devudb01.novcds.io:2379 |      false |
| 950443008f8de983 | unstarted |               | http://172.21.69.253:2380 |                                |      false |
| d8b9762ebf4430a3 |   started | etcd-devewt01 | http://172.21.58.245:2380 | http://devewt01.novcds.io:2379 |      false |
+------------------+-----------+---------------+---------------------------+--------------------------------+------------+

```
```
postgres@devudb01:/postgres/admin/etcd=> eew member add etcd-devudb02 --peer-urls=http://172.21.67.12:2380
Member b19f3886ba86a259 added to cluster 3b96513055e383dc

ETCD_NAME="etcd-devudb02"
ETCD_INITIAL_CLUSTER="etcd-devudb01=http://172.21.61.224:2380,=http://172.21.69.253:2380,etcd-devudb02=http://172.21.67.12:2380,etcd-devewt01=http://172.21.58.245:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://172.21.67.12:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"
postgres@devudb01:/postgres/admin/etcd=> eee member list
{"level":"warn","ts":"2022-02-22T11:49:59.803-0600","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00044e1c0/172.21.58.245:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded

```

Take a look at this:
##ETCD_INITIAL_CLUSTER="etcd-devudb01=http://172.21.61.224:2380**,=http://172.21.69.253:2380**,etcd-devudb02=http://172.21.67.12:2380,etcd-devewt01=http://172.21.58.245:2380"

**Comment by pgodfrin-nov** [comment] 2022-02-22 17:56
accidentally closed

**Comment by ahrtr** [comment] 2022-02-24 06:55
It is expected behavior. 

When there is only one member, and you want to add a new member, then the workflow should be:
1. Execute command `etcdctl member add .....`;
2. Start the new member;
3. Execute any commands, such as `etcdctl member list` or `etcdctl get key`

The key point is that the third step can only work after the second step succeeds.  Otherwise, the quorum isn't satisfied. 

If there are already two members in the cluster, and now you want to add the third member. The quorum still holds, so you can perform the `etcdctl member list `command successfully even without starting the third member.

**Comment by ahrtr** [comment] 2022-02-26 05:46
Since it isn't an issue, so closing this ticket.

**Closed by ahrtr** 2022-02-26 05:46 UTC
