### ISSUE TITLE
Regression in gRPC-gateway in v3.4.23 

### ISSUE THREAD

**Issue by CyberDem0n** [etcd-io/etcd#15256] opened 2023-02-07 13:10 UTC
### What happened?

When authentication is enabled Etcd closes connection without sending any data when http requests without `authorization` header or with invalid token are received.
Examples:
```
$ curl -v -X POST -d '{"key":"L3NlcnZpY2UvYmF0bWFuLw=="}' http://localhost:2379/v3/kv/range
*   Trying 127.0.0.1:2379...
* Connected to localhost (127.0.0.1) port 2379 (#0)
> POST /v3/kv/range HTTP/1.1
> Host: localhost:2379
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Length: 34
> Content-Type: application/x-www-form-urlencoded
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server

$ curl -v -H 'Authorization: KzlMPwIMqjQEEJjs.1' -X POST -d '{"key":"L3NlcnZpY2UvYmF0bWFuLw=="}' http://localhost:2379/v3/kv/range
*   Trying 127.0.0.1:2379...
* Connected to localhost (127.0.0.1) port 2379 (#0)
> POST /v3/kv/range HTTP/1.1
> Host: localhost:2379
> User-Agent: curl/7.81.0
> Accept: */*
> Authorization: KzlMPwIMqjQEEJjs.1
> Content-Length: 34
> Content-Type: application/x-www-form-urlencoded
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

### What did you expect to happen?

A normal HTTP response with error message should be returned:

Example:
```
$ curl -v -H 'authorization: KzlMPwIMqjQEEJjs.1' -X POST -d '{"key":"L3NlcnZpY2UvYmF0bWFuLw=="}' http://localhost:2379/v3/kv/range
*   Trying 127.0.0.1:2379...
* Connected to localhost (127.0.0.1) port 2379 (#0)
> POST /v3/kv/range HTTP/1.1
> Host: localhost:2379
> User-Agent: curl/7.81.0
> Accept: */*
> authorization: KzlMPwIMqjQEEJjs.1
> Content-Length: 74
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Access-Control-Allow-Headers: accept, content-type, authorization
< Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Date: Tue, 07 Feb 2023 12:49:07 GMT
< Content-Length: 95
< 
* Connection #0 to host localhost left intact
{"error":"etcdserver: invalid auth token","code":16,"message":"etcdserver: invalid auth token"}
```

### How can we reproduce it (as minimally and precisely as possible)?

Enable authorization and perform POST HTTP request via gRPC-gateway as it is described in "What happened?"

### Anything else we need to know?

Only v3.4.23 is affected, v3.5.7, v3.5.6, and v3.4.22 don't have this problem.

### Etcd version (please run commands below)

<details>

```console
$ etcd --version
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
        A future release of golang/protobuf will delete this package,
        which has long been excluded from the compatibility promise.

etcd Version: 3.4.23
Git SHA: c8b7831
Go Version: go1.17.13
Go OS/Arch: linux/amd64

$ etcdctl version
etcdctl version: 3.4.23
API version: 3.4
```

</details>

### Etcd configuration (command line flags or environment variables)

<details>

Nothing, just enough to start etcd without config files, flags, or environment variables.

</details>

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

<details>

```console
$ etcdctl member list -w table
+------------------+---------+---------+-----------------------+-----------------------+------------+
|        ID        | STATUS  |  NAME   |      PEER ADDRS       |     CLIENT ADDRS      | IS LEARNER |
+------------------+---------+---------+-----------------------+-----------------------+------------+
| 8e9e05c52164694d | started | default | http://localhost:2380 | http://localhost:2379 |      false |
+------------------+---------+---------+-----------------------+-----------------------+------------+


$ etcdctl --endpoints=<member list> endpoint status -w table
+-----------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|       ENDPOINT        |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+-----------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://localhost:2379 | 8e9e05c52164694d |  3.4.23 |   45 kB |      true |      false |         9 |        116 |                116 |        |
+-----------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

```

</details>

### Relevant log output

```shell
2023-02-07 13:56:23.293072 W | auth: invalid auth token: KzlMPwIMqjQEEJjs.1
2023-02-07 13:59:47.283586 W | auth: invalid auth token: KzlMPwIMqjQEEJjs.1
```

**Comment by ahrtr** [comment] 2023-02-09 06:23
Thanks @CyberDem0n for raising this issue. 

Confirmed that only 3.4.23 can reproduce this issue, it should have nothing to do with gRPC proxy.  The first commit introducing this issue is https://github.com/etcd-io/etcd/commit/40566d943a9b16f2ee34b77b5679535bd7332fa1. It may be caused by incompatibility between some dependencies. However, it can't be reproduced any more in the latest code in release-3.4. Please let me know if you still can reproduce it in the latest code in release-3.4.

I am going to release 3.4.24 in the following two weeks.

**Comment by ahrtr** [comment] 2023-02-09 06:43
Could anyone help to add a test to prevent this issue in the future?

**Comment by fuweid** [comment] 2023-02-09 06:49
@ahrtr I think it has been fixed in https://github.com/etcd-io/etcd/pull/15088 for release 3.4
and current testcase has covered this.

**Comment by ahrtr** [comment] 2023-02-09 07:59
Thanks @fuweid for the confirmation.

**Closed by ahrtr** 2023-02-09 07:59 UTC
Labels: type/bug, area/testing, help wanted
