### ISSUE TITLE
Etcd corruption detection triggers during in-place cluster recovery

### ISSUE THREAD

**Issue by serathius** [etcd-io/etcd#15548] opened 2023-03-22 08:59 UTC
### What happened?

During in-place cluster recovery etcd started reporting data corruption problems even though none existed. Problem disappears after all members are recovered.

By in-pace cluster recover I mean we recovered etcd snapshot but didn't change IP of members. In multi member cluster such recovery is done as a rolling update. This allows old and new members are able to maintain communication. Recovered members will get new cluster id preventing creating a quorum with old members. However cluster id is not checked during data corruption detection and potentially other operations done via non-raft communication.

During cluster recovery list of members doesn't change, so with in-place IPs, member belonging to new cluster might be still talking to members from old one and reverse. Recovered cluster usually recovers from older snapshot and then branches out their raft log, resulting in different hashes for the same revision. So when a member compares their hash to other member it might mistake it for corruption.

This affects all types of data corruption detection. For initial corruption detection recovered member will crashloop. For periodic corruption detection leader might mark whole cluster as corrupted. 

### What did you expect to happen?

Non-raft operations should give same safety as raft ones in regards to cluster recovery, meaning they should always check clusterid.

### How can we reproduce it (as minimally and precisely as possible)?

TODO

### Etcd version (please run commands below)

v3.4.21

### Etcd configuration (command line flags or environment variables)

N/A

### Etcd debug information (please run commands below, feel free to obfuscate the IP address or FQDN in the output)

N/A

**Comment by ahrtr** [comment] 2023-03-23 01:45
> By in-pace cluster recover I mean we recovered etcd snapshot but didn't change IP of members. In multi member cluster such recovery is done as a rolling update.

This isn't correct to me. During a disaster recovery, 
1. users should restore all members' data directories using the same snapshot **offline** firstly, 
2. and secondly start the members. Please read [op-guide/recovery](https://etcd.io/docs/v3.5/op-guide/recovery/)

The `in-pace cluster recover` makes no sense to me. If the cluster is already running, why do you need to perform a recovery? Usually a slow follower may recover from a snapshot, but there is no cluster level recovery.

So I don't think this is a bug.

**Comment by serathius** [comment] 2023-03-23 08:52
As mentioned before etcd already supports in-place restore. Problem is only when data corruption detection is enabled. Restoring member changes it's cluster id specifically to avoid restored members forming a quorum with non-restored ones.

**Comment by chaochn47** [comment] 2023-03-24 01:51
> As mentioned before etcd already supports in-place restore.

I don't think etcd supports such member restart from db snapshot. A different cluster ID means there are 2 clusters. 

Taking look at the raft http code path, it rejects any raft communication in 
- streamHandler
- snapshotHandler
- ...

https://github.com/etcd-io/etcd/blob/e522ce02b83a4746f6b88a7c56bdba492595d01a/server/etcdserver/api/rafthttp/http.go#L499-L512

**Comment by ahrtr** [comment] 2023-03-24 01:59
> Restoring member changes it's cluster id specifically to avoid restored members forming a quorum with non-restored ones.

Note that [restoring cluster from a snapshot](https://etcd.io/docs/v3.5/op-guide/recovery/) is actually creating/starting a new cluster instead of "in-place restoring a cluster".

**Comment by ptabor** [comment] 2023-03-24 09:42
If I understand correctly we have 2 orthogonal discussions here: 

1) Is it a good practice to restore new variant of cluster (with different cluster ID, but the same peer IPs) side by side to already existing one ? 

I agree it carries risks so from operational perspective it's safer to turn off one cluster and create a new one after. 

But even if we assume it carries risks, the etcd should put a bar high on not doing anything 'stupid' in such a situation. So we can think about this as a test-case for isolation (2).

2) The reason for cluster's to have cluster_id is to be able to distinguish and isolate different clusters. And a restored cluster is a DIFFERENT cluster by design than the original one. 
What Marek is reporting is that there are cases we missed in implementation the isolation aspect and we don't look at cluster_id when we perform cross-node communication. 

@ahrtr @chaochn47  I assume you agree that checking cluster_id for cross-node communication is a good thing to have, 
but you challange the issues priority: there exists workaround if the best practices are followed. Is it fair summary ?

**Comment by ahrtr** [comment] 2023-03-24 23:20
> 1. Is it a good practice to restore new variant of cluster (with different cluster ID, but the same peer IPs) side by side to already existing one ?

It is not about good/bad practice. It isn't supported by etcd at all. Of course, I agree we should add some protection for such case.

> I assume you agree that checking cluster_id for cross-node communication is a good thing to have,

Agreed. Please anyone feel free to deliver a PR for this. thx

**Comment by lbllol365** [comment] 2023-04-24 09:08
I think i can try to do this. @ahrtr

**Comment by ahrtr** [comment] 2023-04-24 09:45
@lbllol365 assigned to you, thx

**Comment by vianamjr** [comment] 2023-07-18 23:16
Is this issue open?

**Comment by jmhbnz** [comment] 2023-07-18 23:23
> Is this issue open?

Hey @vianamjr - This was assigned out in late April and I don't recall seeing any updates since so I think you would be welcome to start working on it.

Perhaps let's check in with @lbllol365 - did you make any progress on this or is it ok to reassign?

**Comment by CaojiamingAlan** [comment] 2023-07-18 23:24
@jmhbnz @vianamjr This is already solved by #15924. Someone with permission can close this.

**Comment by jmhbnz** [comment] 2023-07-18 23:25
Thanks for the clarification @CaojiamingAlan - closing.

**Closed by jmhbnz** 2023-07-18 23:25 UTC
Labels: help wanted, good first issue

**Comment by serathius** [comment] 2023-10-27 12:39
Should this be backported to v3.4?
