### ISSUE TITLE
tests/v3/e2e/watch_delay_test.go TestWatchDelayForEvent

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [etcd-io/etcd#16319] opened 2023-07-27 12:21 UTC
### Which github workflows are flaking?

Jobs in our internal CI are flaking

### Which tests are flaking?

tests/v3/e2e/watch_delay_test.go TestWatchDelayForEvent

### Reason for failure (if possible)

This test is probably failing at https://github.com/etcd-io/etcd/blob/main/tests/e2e/watch_delay_test.go#L178. The log shows messages of below kind:
```
watch_delay_test.go:178: Unexpected watch response delayed over allowed threshold 150ms, delay: 174.333395ms
```
Please find the attached file for the complete log trace.

[go-stress-20230727T031533-2383126183.txt](https://github.com/etcd-io/etcd/files/12183139/go-stress-20230727T031533-2383126183.txt)

### Anything else we need to know?

Steps to reproduce:
1. git clone https://github.com/etcd-io/etcd
2. cd etcd
3. go test -v go.etcd.io/etcd/tests/v3/e2e -c -count=1
4. go install [golang.org/x/tools/cmd/stress@latest](http://golang.org/x/tools/cmd/stress@latest)
5. /root/go/bin/stress -p=1 ./e2e.test -test.run TestWatchDelayForEvent

```
[root@toad1 etcd]# /root/go/bin/stress -p=1 ./e2e.test -test.run TestWatchDelayForEvent
5s: 0 runs so far, 0 failures
10s: 0 runs so far, 0 failures
15s: 0 runs so far, 0 failures
20s: 0 runs so far, 0 failures
25s: 0 runs so far, 0 failures
30s: 1 runs so far, 0 failures
35s: 1 runs so far, 0 failures
40s: 1 runs so far, 0 failures
45s: 1 runs so far, 0 failures
50s: 1 runs so far, 0 failures
55s: 1 runs so far, 0 failures
1m0s: 2 runs so far, 0 failures
1m5s: 2 runs so far, 0 failures
1m10s: 2 runs so far, 0 failures
1m15s: 2 runs so far, 0 failures
1m20s: 2 runs so far, 0 failures
1m25s: 3 runs so far, 0 failures
1m30s: 3 runs so far, 0 failures
1m35s: 3 runs so far, 0 failures
1m40s: 3 runs so far, 0 failures
1m45s: 3 runs so far, 0 failures
1m50s: 4 runs so far, 0 failures
1m55s: 4 runs so far, 0 failures
2m0s: 4 runs so far, 0 failures
2m5s: 4 runs so far, 0 failures
2m10s: 4 runs so far, 0 failures

/tmp/go-stress-20230727T031533-523042225
{"level":"warn","ts":"2023-07-27T03:17:29.249389-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00059a1e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:17:29.249612-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00059a1e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:17:29.249643-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00059a1e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:17:29.249661-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00059a1e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:17:29.24968-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00059a1e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:17:29.249699-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00059a1e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn"
…
2m15s: 5 runs so far, 1 failures (20.00%)
2m20s: 5 runs so far, 1 failures (20.00%)
2m25s: 5 runs so far, 1 failures (20.00%)
2m30s: 5 runs so far, 1 failures (20.00%)
2m35s: 5 runs so far, 1 failures (20.00%)
2m40s: 5 runs so far, 1 failures (20.00%)
2m45s: 6 runs so far, 1 failures (16.67%)
2m50s: 6 runs so far, 1 failures (16.67%)
2m55s: 6 runs so far, 1 failures (16.67%)
3m0s: 6 runs so far, 1 failures (16.67%)
3m5s: 6 runs so far, 1 failures (16.67%)
3m10s: 6 runs so far, 1 failures (16.67%)
3m15s: 7 runs so far, 1 failures (14.29%)
3m20s: 7 runs so far, 1 failures (14.29%)
3m25s: 7 runs so far, 1 failures (14.29%)
3m30s: 7 runs so far, 1 failures (14.29%)
3m35s: 7 runs so far, 1 failures (14.29%)
3m40s: 8 runs so far, 1 failures (12.50%)
3m45s: 8 runs so far, 1 failures (12.50%)
3m50s: 8 runs so far, 1 failures (12.50%)
3m55s: 8 runs so far, 1 failures (12.50%)
4m0s: 8 runs so far, 1 failures (12.50%)
4m5s: 8 runs so far, 1 failures (12.50%)

/tmp/go-stress-20230727T031533-2383126183
{"level":"warn","ts":"2023-07-27T03:19:20.034023-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002a61e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:19:20.034403-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002a61e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:19:20.034754-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002a61e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:19:20.037318-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002a61e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:19:20.031564-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002a61e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn","ts":"2023-07-27T03:19:20.040781-0700","logger":"etcd-client","caller":"v3/retry_interceptor.go:65","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002a61e0/localhost:20000","method":"/etcdserverpb.KV/Range","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
{"level":"warn
…
4m10s: 9 runs so far, 2 failures (22.22%)
4m15s: 9 runs so far, 2 failures (22.22%)
^C
[root@toad1 etcd]#
```

```
[root@toad1 etcd]# uname -m
x86_64
[root@toad1 etcd]#
```

**Comment by Rajalakshmi-Girish** [comment] 2023-07-27 12:36
@lavacat @jmhbnz Thoughts on this please?

**Comment by Rajalakshmi-Girish** [comment] 2023-08-16 05:15
@jmhbnz Can you please let us know, if it is possible to assign this issue to someone?
We are constantly seeing this flakiness.

**Comment by serathius** [comment] 2023-08-17 10:36
Contributions are welcomed!

**Comment by riendeau** [comment] 2023-08-25 20:52
It looks like this test was previously identified as flaky in https://github.com/etcd-io/etcd/issues/15634, and the timeouts were adjusted in response via https://github.com/etcd-io/etcd/pull/15636.

The `delay: 174.333395ms` being reported here isn't so far over the current threshhold of 150ms as to make me think it indicates something conclusively wrong. I wonder if another bump to the `maxWatchDelay` values (perhaps to 200ms?) might be appopriate?

**Comment by Rajalakshmi-Girish** [comment] 2023-08-28 05:04
> It looks like this test was previously identified as flaky in #15634, and the timeouts were adjusted in response via #15636.
> 
> The `delay: 174.333395ms` being reported here isn't so far over the current threshhold of 150ms as to make me think it indicates something conclusively wrong. I wonder if another bump to the `maxWatchDelay` values (perhaps to 200ms?) might be appropriate?

Yes, that should probably help.

**Comment by serathius** [comment] 2023-08-29 09:23
This test was introduced to detect performance degradation in grpc code https://github.com/etcd-io/etcd/issues/15402. It is expected to flake if you run it with `stress`. As long as it doesn't flake to frequently on CI, we should leave it as it is.

**Comment by Rajalakshmi-Girish** [comment] 2023-09-20 04:45
> This test was introduced to detect performance degradation in grpc code #15402. It is expected to flake if you run it with `stress`. As long as it doesn't flake to frequently on CI, we should leave it as it is.

@serathius 
The stress command used above has flag `-p=1` indicating only one parallel process and thereby does seem to mimic sequential execution by only looping the test runs.

And yes we are frequently seeing this flakiness in our CI that runs on ppc64le. The delay is somewhere between >200ms to 450ms.

Can you please throw some light on how this can be debugged and improve the performance?

**Comment by Rajalakshmi-Girish** [comment] 2024-01-19 12:26
@serathius we have been seeing this flake now and then. Last seen 10 days ago on 9th Jan 2024.

As I mentioned above, the stress command used above has a flag -p=1 indicating only one parallel process,
and thereby does that seem to mimic sequential execution?

**Comment by serathius** [comment] 2024-02-23 16:10
> I tried executing this test on x86 setup with threshold values as high as 350ms and the failure can be seen. I used stress command with flag -p=1 as suggested above.

Like said before, this is performance regression test. It is expected to fail if you run it under stress or on low performance hardware. That's ok as long as it doesn't flake in CI. I recommend to improve performance of your hardware or disable it in your CI . 

The best what we can do on etcd side is to move it to separate directory or tag it, so it's clearer that it's a performance and not correctness test.

**Comment by Rajalakshmi-Girish** [comment] 2024-03-11 06:19
@serathius I see this flaking in amd64 CI too.

https://testgrid.k8s.io/sig-etcd-periodics#ci-etcd-e2e-amd64
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-etcd-e2e-amd64/1766591764048646144

Seems like we might further need to increase maxWatchDelay to prevent flakiness, like in https://github.com/etcd-io/etcd/pull/15636/files @lavacat

![image](https://github.com/etcd-io/etcd/assets/63038004/da3c6a87-4680-4ba7-b6fa-f7b1c645eb7d)

**Comment by jmhbnz** [comment] 2024-11-07 19:09
Discussed during sig-etcd triage meeting. We are not seeing flakes in testgrid for tier1 supported platforms i.e. `amd64` and `arm64`. It is expected these performance oriented tests could fail in other architectures with different performance charecteristics. Closing as it is not a priority to investigate this further currently.

**Closed by jmhbnz** 2024-11-07 19:09 UTC
Labels: area/testing, type/flake
